### ISSUE TITLE
Layout problem when using the image ListItem component with is-selectable class

### ISSUE THREAD

**Issue by ilyalehrman** [OfficeDev/Office-UI-Fabric#100]
Combining the image ListItem component with the is-selectable class leads to selection checkmark overlap with the image...

<img width="297" alt="2015-09-07_17-09-53" src="https://cloud.githubusercontent.com/assets/14168583/9722883/757c3988-5583-11e5-8389-ef8c3fc29ef6.png">

**Comment by wdo3650** [comment]
Thanks for the issue. We'll look into this.

**Comment by wdo3650** [comment]
This should be fixed.

**Comment by mikewheaton** [comment]
This seems to be fixed as of Fabric 1.2.1. See **[the repro of this issue](http://codepen.io/mikewheaton/pen/mVMNVB)**.
