### ISSUE TITLE
Add "Push and pull" documentation

### ISSUE THREAD

**Issue by martellaj** [OfficeDev/Office-UI-Fabric#101]
"Push and pull" for the grid is mentioned [here](https://github.com/OfficeDev/Office-UI-Fabric/blob/79fc7053bc16063b1165623af7b705dd202152a9/ghdocs/FEATURES.md#push-and-pull), but not documented. Some guidance on how to use would be helpful.

**Comment by Jahnp** [comment]
You're totally right, this (and the grid in general) should be better documented. Thanks for the catch--we'll get on it asap!

**Comment by andrewconnell** [comment]
Could we get a little clarification on what the syntax should be? I've got a Plunker that demonstrates how one would expect it works... but definitely have something wrong.

http://plnkr.co/edit/Yej1sF16nCsK7Wv5zzbY

**Comment by dkreitz** [comment]
I think I've got it figured out. The use of Push or Pull only shifts the column right or left respectively by the number of 12-column units. You still need to give a width to the column by using the ms-u-* column size classes.

Here's a fork from @andrewconnell code with what I believe is the solution.
http://plnkr.co/edit/tVIK2ZBSKMaytu1H1bSC

**Comment by andrewconnell** [comment]
LGTM

**Comment by ericthompson** [comment]
You've got it, @dkreitz! We've got our official interactive documentation site up that includes an image to help explain it. If this is still a bit lacking, let us know. Thanks!
