### ISSUE TITLE
CommandBar Search item doesn't work in mobile / narrow pages

### ISSUE THREAD

**Issue by ilyalehrman** [OfficeDev/Office-UI-Fabric#102]
The CommandBar component's Search item only seems to work on large displays with enough real estate to show the search item text box. When collapsed, the search item doesn't do anything.

**Comment by wdo3650** [comment]
Thanks for creating this issue. Does the search box fail to expand when the magnifying glass icon is selected or does the search box not do anything after text is entered?

**Comment by ilyalehrman** [comment]
The search box fails to expand when you click on the magnifying glass.


________________________________

**Comment by wdo3650** [comment]
Thanks for the clarification. Which browsers and OS's are you seeing this in?

**Comment by ilyalehrman** [comment]
Windows 10: IE 11/ Edge / FF 40.0.4 / Chrome 45.0.2454.85 m.

Furthermore, after re-expanding the page, --mainArea CommandItems do not come back into view (with the occasional exception of the first CommandItem. If this isn't related I can log it in a separate issue...

**Comment by wdo3650** [comment]
Thanks for letting us know about this other issue. We've resolved both of these issues in the develop branch and are in the process of merging these fixes into master.

**Comment by ilyalehrman** [comment]
Good deal! Looking forward to the update!
