### ISSUE TITLE
Link to React components project

### ISSUE THREAD

**Issue by kmees** [OfficeDev/Office-UI-Fabric#106]
I started implementing the Office UI Fabric components in React a few days ago since we'll most likely be using those in future projects. The basic input components are mostly [done](https://github.com/kmees/react-fabric/issues/1) and [tested](https://travis-ci.org/kmees/react-fabric). The [documentation](http://kmees.github.io/react-fabric/) is also being worked on but it's more of a demo/sample at the moment. 

Anyway, in case somebody wants to contribute, feel free to drop me a message. There's still much left to do!

**Comment by Jahnp** [comment]
Wow--this is *really* cool, and is very much in line with our aspirations and plans for extending Fabric. Thanks for getting this started--keep it up! We're looking into how MS could start to prop up or support similar efforts, but have no concrete ETA yet. This will help kickstart and add fuel to those conversations.

**Comment by mikewheaton** [comment]
Let's get a link to this project in the community section of our [Resources and FAQ](http://dev.office.com/fabric/resources-and-faq) page. We can then close this issue, as it's being worked on in a separate repository and is not actionable here.

**Comment by mikewheaton** [comment]
I've created a pull request to our internal documentation repo with a link to this project. You should see it on our [resources page](http://dev.office.com/fabric/resources-and-faq) soon. Closing this issue as the work is tracked elsewhere.
