### ISSUE TITLE
Command Bar Search Field Unable to Close

### ISSUE THREAD

**Issue by wdo3650** [OfficeDev/Office-UI-Fabric#107]
On smaller screens and browser sizes the command bar search field is unable to be closed if text is not entered into the field.

**Comment by battletoilet** [comment]
We have some fixes for this that will be released very soon.

**Comment by mikewheaton** [comment]
This issue is still present in Fabric 1.2.1 (see **[the repro](http://codepen.io/mikewheaton/pen/EPvqVj)**). On small screens there is no search text or icon, and once the search area is clicked it expands to fill the Command Bar but cannot be closed without first entering text.

**Comment by battletoilet** [comment]
In your codepen the icon isn't showing up at all.

**Comment by mikewheaton** [comment]
Yup, the search icon is missing (I haven't seen the designs but it seems there should be one...) across all screen sizes.

**Comment by mikewheaton** [comment]
Now I see why you mentioned it @battletoilet, I didn't realize the icon was working correctly on our [Command Bar demo page](http://dev.office.com/fabric/components/commandbar) (see below). I'll look into why my repro isn't loading the icon.

![image](https://cloud.githubusercontent.com/assets/1382445/12341178/a7d42ed4-bad4-11e5-82cc-9c9e56c433e7.png)

**Comment by mikewheaton** [comment]
Fixed by PR #615. The search field now closes on all screen sizes.
