### ISSUE TITLE
CommandBarItem does not show command text in mobile / narrow view

### ISSUE THREAD

**Issue by ilyalehrman** [OfficeDev/Office-UI-Fabric#108]
The CommandBarItem does not show commandText, either in UI or via Tooltip, when the page is narrow. There doesn't seem to be a way to force commandText to show, either (unless I missed that somewhere).

It'd be nice if i could specify (similarly to --iconOnly) that i only want to show commandText, or that i want to force commandText to show even if the screen format suggests otherwise.

**Comment by battletoilet** [comment]
That's a great point. The original intention was for the commands to only have an icon in Small-Medium screen sizes. We will look into adding a modifier for keeping the command text at all times.

**Comment by mikewheaton** [comment]
It looks like @battletoilet must have fixed this in a previous release. Here is a [demonstration where it doesn't repro](http://codepen.io/mikewheaton/full/JGyVvW/) – watch the "Junk" button and notice that it doesn't disappear as you shrink the window down.
