### ISSUE TITLE
DatePicker wrong z-index when using 1 directly below another

### ISSUE THREAD

**Issue by casvaniersel** [OfficeDev/Office-UI-Fabric#109]
When using 2 DatePicker directly above each other then the textField below comes through the DatePicker at the top when the DatePicker is open. Luckily there is an easy fix!

Fix: .ms-DatePicker-picker--focused.ms-DatePicker-picker--opened { position:relative; z-index:10; }

**Comment by LezaMax** [comment]
Thanks @casvaniersel, we'll take a look.

**Comment by casvaniersel** [comment]
I added a fix for this with Pull Request 111

**Comment by wdo3650** [comment]
The pull request has been approved. Thanks for the input and taking the initiative on this. It's great to see members of the community contributing.
