### ISSUE TITLE
request new icons

### ISSUE THREAD

**Issue by johnnliu** [OfficeDev/Office-UI-Fabric#113]
https://twitter.com/johnnliu/status/641814696111173632

I noted we have:
.ms-Icon--coffee
.ms-Icon--circleCoffee

But we don't have
.ms-Icon--pint
.ms-Icon--beer
.ms-Icon--tea

What would be the process to request new icons and get them in for the next major release? e.g. /v2/ 

 (not an urgent task, just asking about the process)

**Comment by johnnliu** [comment]
There are also no icons for the main Office products: Word, Excel, Outlook, PowerPoint.  Sites, Delve, PowerBI...  etc.  

But there is PDF
.ms-Icon--documentPDF

**Comment by LezaMax** [comment]
Thanks @johnnliu. Do you have a list of the icons you need? We can take a look and see if we can incorporate them.  Doubt we will have .ms-Icon-beer but how knows :)

**Comment by ericthompson** [comment]
Definitely good to know what kinds of icons you'd need @johnnliu. We get our icons from the official sets used within Office/O365/Microsoft, so we'll need to work with those teams directly. Once I get your list, I can pass it along and see. I, for one, can find a lot of uses for a .ms-Icon--beer :beer:

**Comment by StfBauer** [comment]
It would be also nice to have more of the default office 365 icons in the font. I created a small documentation on the following web site. http://lab.n8d.at/o365glyph/index.html

**Comment by casvaniersel** [comment]
Yes it would be nice to have all the logo's (Word, Excel, Office etc.) as well!

**Comment by SPParseError** [comment]
Hi, +1 it would be very nice to have document type's logos, as in Delve's Office365Icons font.

**Comment by mikewheaton** [comment]
I'm not familiar with the details, but it seems we're unable to include the product logos (Word, Excel, Office, etc.) in an open source release. See Peter's comment in #79.

**Comment by mikewheaton** [comment]
I've added these icon requests to [our roadmap](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md). If you need other icons please open a new issue and we'll get them added to the list.
