### ISSUE TITLE
when one dropdown is opened close another

### ISSUE THREAD

**Issue by gkht** [OfficeDev/Office-UI-Fabric#118]
i think when you open one, then another should be closed.

**Comment by Jester98x** [comment]
+1 for this.

Any update when we might see a fix?

**Comment by ericthompson** [comment]
Sorry about the delay on this one - we're looking into it!

**Comment by jonahkirangi** [comment]
Dropdowns now auto-close when another dropdown is opened. Resolved in pull request https://github.com/OfficeDev/Office-UI-Fabric/pull/176.
