### ISSUE TITLE
Make AMD compliant

### ISSUE THREAD

**Issue by brijeshb** [OfficeDev/Office-UI-Fabric#120]
Would be nice to support require

**Comment by mikewheaton** [comment]
We'll have to discuss this to determine how much work is involved, and if this is useful to enough consumers of Fabric to justify the investment.

**Comment by mikewheaton** [comment]
When we move to TypeScript (see [the roadmap](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md)) we can set it to compile to AMD compliant.

**Comment by patrick-rodgers** [comment]
You can fake this, at least partially. If you wrap the entire js file contents in a define and return the fabric variable you can use it in require. Unfortunately the way this was implemented you will only then have access to Spinner, ProgressIndicator, Breadcrumb and MessageBanner off of the global fabric var in your require.

define(['jquery'], function() { ///all the file contents; return fabric; });

If would be nice to provide clean support for AMD modules.

**Comment by mikewheaton** [comment]
I've added this request to [our roadmap](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md) as a possible future improvement.
