### ISSUE TITLE
Vertical NavBar

### ISSUE THREAD

**Issue by git-sdavidpaul** [OfficeDev/Office-UI-Fabric#122]
Hi,

Is there sample for vertical NavBar? The one in the current demo shows only a horizontal layout. Option to switch it vertical or Horizontal would be great.

**Comment by robi26** [comment]
+1 needing it right now ;)

**Comment by ericthompson** [comment]
You're right - currently we only have the horizontal one. We're looking into the vertical one! Switching between the layouts is an interesting idea...

**Comment by mikewheaton** [comment]
Do we have a design for this that's ready to be implemented, or is it a future request?

**Comment by mikewheaton** [comment]
We don't have any designs for this or plans to build it in the near future, so I've added it to [our roadmap](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md).
