### ISSUE TITLE
Using Office UI Fabric for web Applications

### ISSUE THREAD

**Issue by git-sdavidpaul** [OfficeDev/Office-UI-Fabric#123]
Hi,

Will you be able to confirm if the Office UI Fabric can be used for applications other than Office Add-In developments i.e. general web application development (using ASP.NET). 

I see a specific clause in the Font license that it must be used for Add-In development only. Is Office UI Fabric ready public, general usage in license perspective?

**Comment by git-sdavidpaul** [comment]
@ericthompson: Can anyone answer this please?

**Comment by ericthompson** [comment]
Sorry for the delay, David - still looking into this one. I'm escalating it so we can get an answer asap.

**Comment by LezaMax** [comment]
Hi @git-sdavidpaul. All Fabric assets distributed via GitHub are licensed under the MIT license which means you can use them on any projects provided you follow the MIT license. Specifically for the fonts, as stated by their license, you can use them only on Office Add-Ins. In this context Office Add-Ins include any web applications that extend the Office User Experience including: Office Add-Ins (previously known as Apps for Office), SharePoint Add-Ins (previously known ad Apps for SharePoint) and Office 365 Apps (those launched from within the Office launcher).

**Comment by LezaMax** [comment]
I believe my latest answer addresses the question. Please let me know if it doesn't and we can reopen. Thanks!

**Comment by gautamsi** [comment]
Hi @LezaMax, what about css and other Fabric assets? see license terms at http://aka.ms/fabric-font-license
MICROSOFT SOFTWARE LICENSE TERMS
MICROSOFT WINDOWS USER INTERFACE FONT FAMILY: “SEGOE UI”, 
MICROSOFT OFFICE: “FABRIC ASSETS” (including CSS)

Can we have clarifying post in FAQ about what can be used universally and what can not. My understanding is that I can still use the font name and family (css class names), if font is present (Windows/Office on mac) it will work, and if Font is unavailable system will substitute.

**Comment by gautamsi** [comment]
After I dig in to release css files, it feels like it will be useless framework to be used in other than Office 365 add-ins. you can not use icons because of font limitation. You can not use CSS as it is fabric asset.  All the files has this header, making everything under Fabric Asset, use of which is restricted. 

````css
/* Copyright (c) Microsoft. All rights reserved. Licensed under the MIT license. See LICENSE in the project root for license information. */
/**
 * Office UI Fabric 1.1.3
 * The front-end framework for building experiences for Office 365.
 **/
````
Licensing source code under MIT is useless. It should have better used Microsoft Reference Source. it is like saying here is the free code, you can do what you want BUT only for Microsoft Office 365 add-ins.

**Comment by Nojj02** [comment]
Hi @LezaMax. I've a follow-up question also for the CSS files.  Inside are found the sections stating that icons and such are not licensed under MIT. So if we were to use this in a non-Office context, what would be the proper approach of handling these CSS files? Should we create new CSS files with basically every content copied but these sections omitted? What other alternatives are there?

**Comment by aamir-pk** [comment]
It's silly (perhaps deceiving) that code is being released under MIT license but assets are using very restrictive license. It simply means the framework should only be used in Office context. So let's stick with Bootstrap (and https://adminlte.io/).

**Comment by igbenic** [comment]
Sad
