### ISSUE TITLE
Sortable tables

### ISSUE THREAD

**Issue by git-sdavidpaul** [OfficeDev/office-ui-fabric#129]
How to use sortable tables? Can you please add samples/documentation for it?

**Comment by ericthompson** [comment]
Good question - I'll work with the team to see what we can do.

**Comment by ericthompson** [comment]
Since Fabric is currently focused on styling, we're looking into what "sorting" would look like for the table. Adding richer table interactions aren't immediately on our roadmap, but we'll leave this open so we can be sure to track it as the project grows.

**Comment by git-sdavidpaul** [comment]
Styles for tables with sort options is what I was looking for. I would like to highlight the column header of the table by which it is sorted along with the sort direction indicator. 

A JS for doing client side sorting would be a valuable component but the styles for implementing table with sort is common requirement with any table implementation.

**Comment by pbjorklund** [comment]
Any ideas or recommendations on this from the team?

**Comment by ericthompson** [comment]
Unfortunately, not yet. We'll comment back if there are any updates.

**Comment by andrewconnell** [comment]
This is actually on the plans for the table that we're building in the angular directives we're working on. Hope to have a initial release of a few directives in the first drop... sortable tables won't be in it, but it's definitely in the plans: ngofficeuifabric.com.

**Comment by andrewconnell** [comment]
We have sortable table now with the htto://ngofficeuifabric.com. You can grab our library from npm, bower or nuget.

You can see it in action here: 
htto://ngofficeuifabric.com/demos/uifTable

**Comment by mikewheaton** [comment]
We'll need some design review before adding this to Fabric.

**Comment by mikewheaton** [comment]
To start with, we're going to add a style for the header of a column that is sorted. We're working with design now to make sure we have this right. In future updates we may add JavaScript support for sorting columns.

**Comment by johnnyongesa** [comment]
Hi all, has row sorting been added to office ui fabric? i need to add row sorting to my office ui fabric table

**Comment by andrewconnell** [comment]
@johnnyongesa Sorting isn't in the Office UI Fabric component… there isn’t functionality per-say within the components. 

However the Angular port of Office UI Fabric, [ngOfficeUiFabric](https://github.com/ngOfficeUIFabric/ng-officeuifabric/) does have column sorting as well as selectable rows in the table implementation. Check out a demo here: http://ngofficeuifabric.com/demos/uifTable/

**Comment by mikewheaton** [comment]
The functionality of sorting rows is not yet in Fabric, and is not planned for inclusion in the upcoming 3.0 release. However, we are going to release TypeScript for table component (to allow for selection of rows) and this could be extended to add sorting. As Eric mentioned above, we just need to get official designs for how sortable tables should look before adding it to Fabric.

**Comment by johnnyongesa** [comment]
Home you consider sorting in next releases, this is a very important component of table component and almost every user of table component uses sorting

**Comment by andrewconnell** [comment]
@mikewheaton will the TypeScript additions that you are "releasing" also going to be in the CDN releases or like they are today where only CSS is in the CDN but JS is something you have to add to the project?

**Comment by mikewheaton** [comment]
We're finally going to start hosting all of the JS on the CDN, so that functional components can be added to an app without any downloading or local building of the project. 😄

**Comment by ericthompson** [comment]
@johnnyongesa - we'll make a note for the work item on our end.

**Comment by andrewconnell** [comment]
Great news… will the time from a release to getting it up on the CDN shorten as well? Right now looks like it’s a 2 month + delay from a new release to it showing up on the CDN.

**Comment by mikewheaton** [comment]
Well, it can't get any worse. We're working with the CDN team on a new process that should allow us to push through a new version in 1 to 2 weeks. Stay tuned.

**Comment by johnnyongesa** [comment]
Hi guys, is there a way to re-size the ms-Dialog component? i would want to increase the width of ms-Dialog compoenent

**Comment by mikewheaton** [comment]
@johnnyongesa: Please open a new issue next time, so we can keep each issue on topic. 😄  Here is a [quick demo](http://plnkr.co/edit/tPZ8GJ?p=preview) of overriding the `max-width` value of `ms-Dialog-main` to change the width of the dialog.

**Comment by johnnyongesa** [comment]
Thank you mike for the response, but the link you shared does not give any idea of what to do. It just has a html file with <h1> tag and a blank css file

**Comment by mikewheaton** [comment]
@johnnyongesa: I've opened a [new issue](https://github.com/OfficeDev/Office-UI-Fabric/issues/608) for this and posted a more detailed response there.

**Comment by mikewheaton** [comment]
There are no plans to update the current Table component with sortable columns. We will, however, be adding a new details list component that will include this functionality. This is now included in [our roadmap](https://github.com/OfficeDev/office-ui-fabric/blob/master/ghdocs/ROADMAP.md).
