### ISSUE TITLE
Searchable Dropdowns

### ISSUE THREAD

**Issue by git-sdavidpaul** [OfficeDev/Office-UI-Fabric#130]
Can you please add Dropdowns with search feature (like jQuery chosen)?

**Comment by ericthompson** [comment]
We don't currently have plans for this, but it's a really good idea. We could imagine something like this as a variant of the SearchBox or TextField with a contextual menu for the "searching feature."

**Comment by git-sdavidpaul** [comment]
Or it can be a variant of dropdown too. Sometimes we have a very long list of items added to a dropdown and a searchbox within the dropdown that can quickly give me a filtered list would be of great value.

**Comment by mikewheaton** [comment]
@wdo3650 is working on a feature like this in product, but the design doesn't match our standard textbox or dropdown. This will need design.

**Comment by ichpuchtli** [comment]
I would recommend using https://selectize.github.io/selectize.js/ it allows you to specify how the option  and selections are rendered. See the ~Remote Source — Github~ example.

**Comment by ericthompson** [comment]
Thanks for the extra example, @ichpuchtli!
