### ISSUE TITLE
Pagination styles

### ISSUE THREAD

**Issue by git-sdavidpaul** [OfficeDev/Office-UI-Fabric#131]
Can you please add pagination styles for tables?

**Comment by ericthompson** [comment]
Makes sense - thanks. Currently don't have a design pattern for it, but we'll look into adding it.

**Comment by mikewheaton** [comment]
I found some design patterns for this that we may be able to build from, but they are old so a review from our current designers first would be helpful.

**Comment by mikewheaton** [comment]
I've added this to [our backlog](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md) as something we plan to release in a future version of Fabric. Thank you for your patience here.
