### ISSUE TITLE
Timer control

### ISSUE THREAD

**Issue by git-sdavidpaul** [OfficeDev/Office-UI-Fabric#132]
Can you please add timer control?

**Comment by ericthompson** [comment]
Interesting... could you elaborate on what this might look like?

**Comment by git-sdavidpaul** [comment]
This could be a JS plugin that would accept a start event with options of pre-set time to start from and end event that would stop the timer and display total time elapsed between start and stop. It could have variants like count down timer, count up timer. 

Does that help?

**Comment by ericthompson** [comment]
Makes sense - thanks for the clarification. There aren't any patterns for this at the moment on our side, so this would probably get looked at a bit further out. We'll keep it open and let you know when it comes up.

**Comment by casvaniersel** [comment]
+1 I was looking for something like this as well. I've now combined it with this bootstrap-clockpicker 
http://weareoutman.github.io/clockpicker maybe something that can be transformed to match Office UI Fabric look and feel ?

**Comment by mikewheaton** [comment]
We don't have designs or a need for this in product at this time, so I've added it to [our roadmap](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md) as a potential feature for later.
