### ISSUE TITLE
Input masks

### ISSUE THREAD

**Issue by git-sdavidpaul** [OfficeDev/Office-UI-Fabric#133]
Can you please add input masks for currency, date, time etc.?

**Comment by ericthompson** [comment]
In what form do you think this would make sense? JS or additional styles for current components?

**Comment by git-sdavidpaul** [comment]
JS would be preferable.

**Comment by ericthompson** [comment]
After poking around, this is an interesting one for us. Not something we had originally thought of doing, but we'll keep it open.

**Comment by timschoch** [comment]
It would be very helpful if the masks could be localized to accomodate for different local styles. (eg currencies are written differently in Germany and in Switzerland)

**Comment by mikewheaton** [comment]
This is a potentially useful feature, but not something we have a need for or the resources to pursue at this time. I've added it to [our roadmap](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md). We're always open to pull requests, so if you do build this feature please let us know and we may be able to get it into Fabric.
