### ISSUE TITLE
Fileupload with drag and drop

### ISSUE THREAD

**Issue by git-sdavidpaul** [OfficeDev/Office-UI-Fabric#134]
Can you please add component for drag and drop file upload control?

**Comment by ericthompson** [comment]
This is an interesting request - we'd need to look into what would be involved with doing something like this. 

What kind of component would you want from this? We can see ourselves having styling for something like this, but would want to know what you're looking for.

**Comment by git-sdavidpaul** [comment]
Hi Eric,

A simple looking multiple file drag and drop control which would also provide control over progress indicators and progress animations along with control over the upload progress.

Something like DropzoneJs (http://www.dropzonejs.com/). The problem with using dropzone along with Office UI Fabric would be deviation from the design language. 

Hope this helps.

thanks

**Comment by mikewheaton** [comment]
This is a good suggestion, but not something we have designs for or an immediate need for. I've added it to [our roadmap](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md) so that we can track it as a potential feature.

**Comment by russgove** [comment]
Hey . I  could use thjs too. where is it on your roadmap?

**Comment by russgove** [comment]
Seems to have been droped. 
Im creating a new issue.

**Comment by ImenTurki** [comment]
hello ,please any one found a solution for office-ui-fabric-react for upload file ? 
how do you satisfy this .

**Comment by makafsal** [comment]
+1
