### ISSUE TITLE
Support bower install

### ISSUE THREAD

**Issue by wcarson** [OfficeDev/Office-UI-Fabric#135]
I didn't see this mentioned anywhere, but it would be nice to support installing the framework via bower by name (e.g. bower install office-ui-fabric or as a dependency in bower.json).

**Comment by Jahnp** [comment]
Yes! We absolutely plan to do this--both in Bower and NPM eventually. Initially we'll do this manually, but the plan is to [use Travis](https://github.com/OfficeDev/Office-UI-Fabric/issues/89) to automate the deployment and publish process.

In the meantime, you can actually still install Fabric via Bower by linking directly to the repo:

bower install ‘git://github.com/OfficeDev/Office-UI-Fabric#1.0.0’

And in bower.json:

{
  "dependencies": {
    "Office-UI-Fabric": "git://github.com/OfficeDev/Office-UI-Fabric#1.0.0"
  }
}

Does this help? Thanks!

**Comment by wcarson** [comment]
My newness to bower is showing. I didn't realize you could specify a repository directly. Works great. Thanks!

**Comment by andrewconnell** [comment]
To pile on, if you use this method to only include the compiled CSS, you can add the following to your .gitignore to commit the compiled CSS in that release to your source.

```
!bower_components/
bower_components/*
!bower_components/Office-UI-Fabric/
bower_components/Office-UI-Fabric/*
!bower_components/Office-UI-Fabric/dist/
bower_components/Office-UI-Fabric/dist/*
!bower_components/Office-UI-Fabric/dist/css/
```

**Comment by Jahnp** [comment]
Alright, installing by Bower and [NPM](https://www.npmjs.com/package/office-ui-fabric) should work now. Try running `npm i office-ui-fabric` or `bower i office-ui-fabric` and let us know if there any kinks. Thanks!

**Comment by wcarson** [comment]
Worked great! Thanks.

**Comment by Jahnp** [comment]
Awesome! I'll go ahead and close this, then. Cheers!

**Comment by andrewconnell** [comment]
SWEET!!!!!

![killerpostman](https://cloud.githubusercontent.com/assets/2068657/10255180/a183cb08-6916-11e5-82e0-2ae031fa42a4.gif)
