### ISSUE TITLE
List Grid doesn't render correctly on screen widths between 480px and 1025px

### ISSUE THREAD

**Issue by waldekmastykarz** [OfficeDev/Office-UI-Fabric#138]
On screen widths between 480px and 1025px items in a List Grid are not rendered properly due to limited space. Currently the only responsive state is below 480px width where items are rendered using 100% width in a single column. Other than that items are rendered in three columns which causes to poor UX on screen widths below 1050px and even worse below 800px.

From what I've seen the 100% width should be applied already below 850px so that a list item has sufficient space for actions and primary text. Between 850px and 1050px items in a grid could be displayed in two columns and above 1050px in three columns. These dimensions are excluding any paddings and margins that might be around a List Grid so you might want to include them in the media queries.

**Comment by mikewheaton** [comment]
At what point we should go from three columns to one column (or maybe even two columns first?) will largely depend on the specific app that's displaying in the list. The current behavior might be acceptable in some cases but not others.

For reference, here's what [our example list](http://dev.office.com/fabric/components/list) looks like with about 630px of width:
![image](https://cloud.githubusercontent.com/assets/1382445/12281529/bbb42952-b94b-11e5-9579-8bb493e379c2.png)

We do offer the standard non-responsive list, which always has a single column. But we may want to consider additional variants that specify the number of columns for various breakpoints.

@waldekmastykarz: For the time being, the best option is to use a standard `ms-List` (don't add the `ms-List--grid` class) and then create an override class with behaviors specific to your app. It would look something like this:

```
@media (min-width: 850px)
.ms-List.ms-List--myCustomClassName .ms-ListItem {
    width: 50%;
    float: left;
    border-width: 0 1px 1px 0;
}

@media (min-width: 1050px)
.ms-List.ms-List--myCustomClassName .ms-ListItem {
    width: 33.33333333333333%;
    float: left;
    border-width: 0 1px 1px 0;
}
```

**Comment by mikewheaton** [comment]
Closing this for now. If we receive more requests for different responsive behaviors we can investigate changing the design.
