### ISSUE TITLE
Incomplete Button implementation in src folder

### ISSUE THREAD

**Issue by StfBauer** [OfficeDev/Office-UI-Fabric#140]
The documentation list four different variants of buttons, while in the source or after build dist folder only one button can be found.

**Comment by Jahnp** [comment]
Good catch! This seems to have been [fixed](https://github.com/OfficeDev/Office-UI-Fabric/pull/61) on our `develop` branch ([which will soon be merged into `master`](https://github.com/OfficeDev/Office-UI-Fabric/issues/145)), but is not yet included in a release. Try building off of `develop` and see if that gives you what you'd expect.

Note that we do plan to have a 1.1 release out shortly--most likely this week or early next week at the absolute latest--so expect to see this fixed there for sure. Thanks again for catching this!

**Comment by StfBauer** [comment]
I think this also matches to the media query definition. Now they are included but the haven't been there in the early first release.

**Comment by ericthompson** [comment]
This has been fixed - closing for now!
