### ISSUE TITLE
No Nuget Package

### ISSUE THREAD

**Issue by SyntaxGeek** [OfficeDev/Office-UI-Fabric#141]
Any chance this will make it to a nuget package for ease of use in Visual Studio?

**Comment by notandrew** [comment]
I'm looking into this -- I'm not sure of any time frames just yet though.

**Comment by SyntaxGeek** [comment]
Ok, thanks for the reply.

**Comment by Jahnp** [comment]
We're now published to [Nuget.org](https://www.nuget.org/packages/OfficeUIFabric/), thanks to @zkoehne and #164 ! Thanks for the PR! I'll go ahead and close this now. Thanks for your patience!
