### ISSUE TITLE
Datetime picker - Click on the month name and it breaks.

### ISSUE THREAD

**Issue by rolandoldengarm** [OfficeDev/Office-UI-Fabric#150]
When you click in the Date/time picker, it expands (correctly). When you click on the month name (top left, e.g. September 2015), the month picker disappears and doesn't come back

http://i.imgur.com/Kgr5fHa.png

Can be tested here easily: http://officeuifabric.com/components/date-picker/

If I remove the class "ms-DatePicker-headerToggleView" from that header, it doesn't break anymore. Is there a reason that class was there?

**Comment by andrewconnell** [comment]
You used my demo site in your repo... LOL... sweet!!! 

![itshappening](https://cloud.githubusercontent.com/assets/2068657/10089121/fe11cb60-62d4-11e5-8cd7-2b9b050838c3.gif)

**Comment by wdo3650** [comment]
Thanks for noting this issue. This should be fixed it in the latest version of Fabric which was released on Friday.

**Comment by ericthompson** [comment]
Still borked - we're working on it.

**Comment by wdo3650** [comment]
This should be fixed in master.
