### ISSUE TITLE
Add card as a component

### ISSUE THREAD

**Issue by waldekmastykarz** [OfficeDev/Office-UI-Fabric#152]
Add Delve-like cards as a component. It would be very helpful if the card came in two sizes so it can be used both with full-page applications and Office Add-ins.

**Comment by ericthompson** [comment]
Definitely a good and useful one. We're actually doing work on this side to bring one in, but we don't have an ETA yet.

I'm curious - can you give me some examples of the two sizes? It would be great for us to know as we think through the designs on our side.

**Comment by waldekmastykarz** [comment]
Great to hear that it's on your radar! One would be the regular Delve-card size. The order would be smaller so it would be embeddable. You can see the example of a smaller card in a sample lab I've built around it at https://github.com/waldekmastykarz/lab-officegraph-trendinginthissite. In there the card is 140px wide if I'm correct.

**Comment by mikewheaton** [comment]
I've added this to [our roadmap](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md), as we definitely plant to get the Card component added in the near future.

**Comment by waldekmastykarz** [comment]
Awesome! Looking forward to it and please let me know if there is anything I could help with.

**Comment by JyotsnaWadhwani** [comment]
Hi,
I have made my custom card similar to that appears on the new site contents page. I have made it using the ms-callout box. 
![callout](https://cloud.githubusercontent.com/assets/20122732/16520615/db1326d8-3fae-11e6-9377-db644fee6326.png)
You can have a look at the screenshot.

**Comment by anhldbk** [comment]
Is the component ready yet?

**Comment by mikewheaton** [comment]
@anhldbk: This repository no longer contains components, but we do have a [DocumentCard in Fabric React](http://dev.office.com/fabric#/components/documentcard) that may suit your needs. If not, please [open an issue on Fabric React](https://github.com/OfficeDev/office-ui-fabric-react/issues) with details on what you're looking for in a Card component. Thanks!
