### ISSUE TITLE
Increase size of action icons on mobile devices

### ISSUE THREAD

**Issue by waldekmastykarz** [OfficeDev/Office-UI-Fabric#156]
On mobile devices the action icons displayed on a list item are too small and too close to each other to be able to use them using touch effectively. A better idea to present these actions would be to introduce swipe behavior similar to the mail app on iOS.

**Comment by git-sdavidpaul** [comment]
+1 Can it be a bit bigger with different alignment?

**Comment by ericthompson** [comment]
Let us check with our Design team and get back to you!

**Comment by ericthompson** [comment]
Checked with some of our Designers and you're right - although the List Item is responsive, it's not terribly touch friendly. We'll keep this issue open as a placeholder and put an item on our backlog to address making the List Item touch friendly.

**Comment by waldekmastykarz** [comment]
Awesome @ericthompson! Please let me know if there is anything that I could help with.

**Comment by mikewheaton** [comment]
We've confirmed with the design team that the current ListItem was not designed to be touch friendly. There are plans to create some generic list item templates, one of which might include action(s) with touch-friendly sizes. This has been added to [our backlog](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md).

**Comment by waldekmastykarz** [comment]
:+1:
