### ISSUE TITLE
Enhanced Icon Font Overview

### ISSUE THREAD

**Issue by timschoch** [OfficeDev/Office-UI-Fabric#157]
I had to do some Mockups in Photoshop the other day and could not get the icons working. The problem is, that I can't copy and paste them from the icon overview.
Over here http://fortawesome.github.io/Font-Awesome/cheatsheet/ you can select an icon and copy it to photoshop. This could be achieved by adding the unicode char to the markup and styling it with the font family. I know this is not how the icons work, but it makes the list just so much more usable.

Additionally it would be awesome if you could add a search box to the icon inventory 
http://officeuifabric.com/features/icons.html#IconInventory
I've added the search box in a fork of your code pen: http://codepen.io/anon/pen/VvPYYr
(btw, the classes on the icons in your codepen itself do not correspond with the labels)

**Comment by pascalberger** [comment]
http://officeuifabric.com is a community based site, the issue/PR should therefore be opened at https://github.com/ngOfficeUIFabric/officeuifabric.github.io

**Comment by ericthompson** [comment]
Correct, @pascalberger! We have [our own site](http://dev.office.com/fabric) in the works, but opening an issue at the other repo is the right way to go - @andrewconnell can help you out! Closing.
