### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by unindented** [OfficeDev/Office-UI-Fabric#162]
Would it be possible to publish this to npm? A big chunk of the frontend development community seems to have moved on from bower, and all dependencies are expected to live in npm...

**Comment by Jahnp** [comment]
Definitely! Like I mention in https://github.com/OfficeDev/Office-UI-Fabric/issues/135, we'll be publishing to both NPM and Bower shortly. We also intend to have [Travis](https://github.com/OfficeDev/Office-UI-Fabric/issues/89) set up to automate the publishing of new releases soon.

Though 135 speaks to this issue as well, I'll keep this open in the meantime--the more incentive the better :) Thanks!

**Comment by unindented** [comment]
Ah awesome, thank you! Any way I can help?

**Comment by Jahnp** [comment]
I think we're good for now, but thank you for the offer! We have the Travis work is slotted for the next few weeks, so there will be that to look forward to.

In the meantime, we just published to [NPM](https://www.npmjs.com/package/office-ui-fabric) and Bower--try running `npm i office-ui-fabric` or `bower i office-ui-fabric` and let us know if there any kinks!

**Comment by unindented** [comment]
My only issue when running `npm i office-ui-fabric` was that it required `bower` to be installed in order to execute its post-install step. Why is this necessary?

**Comment by Jahnp** [comment]
Good catch--we still have a `bower install` postinstall command from when we were using some external packages prior to 1.0. It's definitely not necessary anymore, so we can do a quick release asap to remove that step.

**Comment by unindented** [comment]
Awesome!

**Comment by Jahnp** [comment]
Ok, this should be fixed now as of #170 , which is included in the 1.1.3 release. Thanks for helping keep the house clean!
