### ISSUE TITLE
Init DatePicker with a Date

### ISSUE THREAD

**Issue by seriewe** [OfficeDev/Office-UI-Fabric#163]
Hello,

I didn't find any possibilities to set a Date to the DatePicker dynamically. In the first version I was able to use the value attribute. But now it seems to be a wrong approach if I set the value like this:  $(".ms-DatePicker input.ms-TextField-field").val("2016-04-20");
How can I do this? Are there some examples?

And do you use this http://amsul.ca/pickadate.js/ pickadate Plugin?

Thanks

**Comment by ericthompson** [comment]
Thanks for your feedback, @seriewe. The team talked and decided to revert the DatePicker to help deal with issues like yours. You can check out the response in #71.

To answer your question, yes - we use pickadate to prop up our Date Picker. Closing for now!

**Comment by knom** [comment]
Is there any solution to this atm?
How do I prepopulate date picker with a default value?

**Comment by bpringe** [comment]
I am also having a problem setting the default date for the DatePicker component. Is there a solution?

**Comment by leddie24** [comment]
Hi @bpringe , is this for the js component? If so, as of version 1.3.0, we've fixed DatePicker to allow the user to utilize pickadate's API methods.  You can see the PR here: https://github.com/OfficeDev/office-ui-fabric-js/pull/191

Here's a code snippet for example:

```
datepicker = new fabric['DatePicker']('.ms-Datepicker');
// Change selected date
datepicker.picker.set('select', [2012, 0, 1]);

// Change highlighted date
datepicker.picker.set('highlight', [2015, 3, 20])
```

**Comment by bpringe** [comment]
Thank you for the information. I realized my problem was with the way I was setting the value of the DatePicker (as a string instead of a Date). I was setting it as value="2017/02/08" instead of value={new Date("2017/02/08")}. Changing it to the latter worked.
