### ISSUE TITLE
Anchor with class button and href shows text as link

### ISSUE THREAD

**Issue by VeldMuijz** [OfficeDev/Office-UI-Fabric#166]
When someone uses an `anchor` element as a button with the button classes and adds a `href` to the `anchor` it shows the button text as a link.

[See this pen](http://codepen.io/VeldMuijz/pen/RWKvbE) for the issue.
[See this pen](http://codepen.io/VeldMuijz/pen/VvPgYE) for the fix.

**Comment by ericthompson** [comment]
Good catch - your fix looks great. Submit a PR and we'll review it!

**Comment by ericthompson** [comment]
Merged in, closing!
