### ISSUE TITLE
DatePicker databinding and localization not ideal after commit f3e3d8a

### ISSUE THREAD

**Issue by PFAR** [OfficeDev/Office-UI-Fabric#167]
The databinding possibilities for DatePicker are gone after commit f3e3d8a.
Also for localization purposes you could expose and centralize usage of the DatePicker.defaults (http://amsul.ca/pickadate.js/) to avoid inconsistencies like with optionMonths and weekdaysShort, initializing them in different places and subsequently not passing on any changes of optionMonths values in the pickadate defaults override.

**Comment by wdo3650** [comment]
Thanks for pointing these concerns out. We're working to make the DatePicker markup more accessible by unwrapping it from the JQuery plugin. See issue #71. This should allow you to again bind data and localize.

**Comment by PFAR** [comment]
Glad it contributed to spark a great discussion ;-) Looking forward to the design changes!

**Comment by ericthompson** [comment]
#179 reverts DatePicker back to its original state. Closing for now, but let us know if you're still having trouble.
