### ISSUE TITLE
Fabric Tutorial Part 1 lacks correct CSS, may lack correct HTML, and lacks completed text

### ISSUE THREAD

**Issue by yoDon** [OfficeDev/Office-UI-Fabric#171]
The Tutorial at https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/TUTORIAL.md lacks any sort of "here's what your files should look like when you are done" and contains at a minimum bad CSS (and possibly also bad HTML). 

The CSS in the tutorial sets the background color for various elements to black #000000 but the "here's what you should see" images clearly show white background color for those elements. If there were a "here's what your files should look like when you are done" section it would have been easier for the authors and others to review/confirm that the tutorial actually works.

I'm also getting incorrect positioning of the text field relative to the title text and incorrect spacing between the list elements, but again without a "here's what your files should look like when you are done" it's hard to tell if that's because I made a mistake following the tutorial or because the tutorial contains additional errors.

Here's a snapshot of the rather unattractive-looking todo list I get when using the CSS contained in the tutorial:

<img width="399" alt="capture" src="https://cloud.githubusercontent.com/assets/1760705/10294565/0672b186-6b70-11e5-8be0-e70282b52198.PNG">

**Comment by ericthompson** [comment]
Great feedback and good tutorial bugs - we'll work on this and fix it up. Thanks for finding them!

**Comment by battletoilet** [comment]
We have fixed up our tutorial and addressed these issues. Here is a completed pull request with the changes. Let us know if you find anything else! Thank you!

[Pull Request #242](https://github.com/OfficeDev/Office-UI-Fabric/pull/242)
