### ISSUE TITLE
PersonaCard overflows

### ISSUE THREAD

**Issue by unindented** [OfficeDev/Office-UI-Fabric#172]
![screen shot 2015-10-06 at 17 44 44](https://cloud.githubusercontent.com/assets/69485/10315393/f6ef6f3c-6c51-11e5-825e-24deee130393.png)

**Comment by ericthompson** [comment]
Good catch - we're on it to add truncation to the name text.

**Comment by unindented** [comment]
@ericthompson I think all the fields (`primaryText`, `secondaryText`, `tertiaryText`, `optionalText`) overflow, so it may be worth adding truncation to all of them.

Thanks!

**Comment by ericthompson** [comment]
@unindented - gotcha and noted. Agreed!

**Comment by jonahkirangi** [comment]
PersonaCard overflow issue has been resolved in pull request https://github.com/OfficeDev/Office-UI-Fabric/pull/177

**Comment by unindented** [comment]
:+1:
