### ISSUE TITLE
TypeError: window.external.GetContext is not a function

### ISSUE THREAD

**Issue by Arthur-Z** [OfficeDev/Office-UI-Fabric#180]
TypeError: window.external.GetContext is not a function
https://appsforoffice.microsoft.com/lib/1.1/hosted/o15apptofilemappingtable.js(line 11,col 117878)
my browser is Firefox 39.0

**Comment by Arthur-Z** [comment]
![qq 20151013134921](https://cloud.githubusercontent.com/assets/14676728/10446823/58bdf54e-71b1-11e5-94e5-37c1ff3f09cc.jpg)

**Comment by Jahnp** [comment]
This looks like a bug with with either this add-in or the JS for the [Office Add-in Fabric Sample](https://github.com/OfficeDev/Office-Add-in-Fabric-UI-Sample), not with Fabric itself. The specific error you're seeing looks like it's coming from Office.js, which is a separate project from Office UI Fabric.

Please consider opening an issue on the [issues page](https://github.com/OfficeDev/Office-Add-in-Fabric-UI-Sample/issues) for the Office Add-in Fabric Sample with any relevant details or repro steps. Thank you!
