### ISSUE TITLE
Dropdown scroll issue on mobile/small devices.

### ISSUE THREAD

**Issue by ericivarsson** [OfficeDev/Office-UI-Fabric#181]
I'm not able to scroll up/down in a dropdown with many items.

adding css "overflow-y: scroll" solves the issue for me.
.ms-Dropdown-items {
    overflow-y: scroll;
}

Before:
![image](https://cloud.githubusercontent.com/assets/14924332/10450164/c19bc76c-7198-11e5-9386-148014623887.png)

After:
![image](https://cloud.githubusercontent.com/assets/14924332/10450204/0ea8c3ca-7199-11e5-822e-d6b7c524991a.png)

**Comment by ericthompson** [comment]
This is great - thanks for catching it and proposing a solution. Would you mind making a pull request with your fix so we can review it?

**Comment by dmitriyyepishin** [comment]
Thanks! I was trying to figure out solution for this and your fix works great.

**Comment by ericivarsson** [comment]
Glad to help! @ericthompson I've created a pull request with a small change in Dropdown.less for you to review.

**Comment by ericthompson** [comment]
Closed with @ericivarsson's pull request #182.
