### ISSUE TITLE
Disabled button looks exactly like a button

### ISSUE THREAD

**Issue by martellaj** [OfficeDev/Office-UI-Fabric#183]
There should be some visible clue that the button is disabled, other than the hover style not being applied when I hover over it.

**Comment by ericthompson** [comment]
Thanks for the feedback, @martellaj! Right now, the text inside the button being greyed out is the way that the Design Language currently indicates a disabled state, so what you're seeing is per the design. We'll be mindful of your feedback as the design evolves.

**Comment by martellaj** [comment]
Then I think it's a bug. The button in it's regular state and disabled state is actually the same color (#f4f4f4). 

**Button CSS without state**
![regular](https://cloud.githubusercontent.com/assets/1019478/10522460/1fbdd6f4-732a-11e5-9d69-fa2b1cfe5987.PNG)

**Button CSS with disabled state**
![disabled](https://cloud.githubusercontent.com/assets/1019478/10522463/2282f856-732a-11e5-93fa-e10eab4fb12b.PNG)

**Comment by ericthompson** [comment]
You're correct about the colors for the background/border colors staying the same across states, but, currently, the Design Language takes the *text color* as the signal for the enabled/disabled state. This is especially relevant for the default button that only has a change in the text color from dark grey to light grey. It's probably easiest if you compare them side-by-side.

Here are the 5 Fabric buttons in their enabled state:
<img width="210" alt="buttonenabled" src="https://cloud.githubusercontent.com/assets/1420854/10522953/be2b60e8-732c-11e5-8ee5-ace012eae621.PNG">

Here are the same 5 buttons in their disabled state:
<img width="204" alt="buttonsdisabled" src="https://cloud.githubusercontent.com/assets/1420854/10522964/c473ca80-732c-11e5-9e0d-46b235ba0169.PNG">

**Comment by martellaj** [comment]
Do you have code that confirms that with the latest version? You can see in the CSS screenshot I took above that the `color` attribute doesn't change. I can show you a side-by-side of my button, but spoiler, they look the same. :dancers:
