### ISSUE TITLE
Configurable DatePicker

### ISSUE THREAD

**Issue by aremes** [OfficeDev/Office-UI-Fabric#185]
Since you're using the incredibly capable pickadate.js, why not allow configuration of that via your JQuery plugin. It's a quick fix. I'll issue a pull-request shortly and reference it here. This would make formatting, localization and customization of the Datepicker very easy.

**Comment by ericthompson** [comment]
This is a great idea and we're happy to make the presentational JS in the toolkit more usable. The only caveat we have to make is that the design language currently doesn't support all of the functionality in pickadate.js's robust API, so we can't take on any bugs resulting from the API's many options or the visualizations of those options.

To that end, we'll definitely look into supporting more of the functionality provided by pickadate.js (e.g. disabled days, formatting options, etc.) and open an issue on ourselves to keep tabs on the fact that we're missing these. Thanks for contributing and improving the toolkit for everyone!
