### ISSUE TITLE
Add support for Pickadate.js options

### ISSUE THREAD

**Issue by ericthompson** [OfficeDev/Office-UI-Fabric#188]
Placeholder issue for looking into the many options provided by pickadate.js - the presentational js date picker used by Fabric. Feel free to comment about which options you leverage the most often.

We will need to understand the design implications for each option and address them as we expand the design language to support them.

**Comment by mikewheaton** [comment]
It looks like this was taken care of by pull request #186, which allows you to pass an object to DatePicker() with configuration options.
