### ISSUE TITLE
Provide a smaller list item component

### ISSUE THREAD

**Issue by ssandu** [OfficeDev/Office-UI-Fabric#189]
When a list hasn't a primaryText then a metaText is rendered under tertiaryText.
Would be nice not to be forced to use primaryText. For a client web part it's too big.
Just an idea.
Thank you !

**Comment by ericthompson** [comment]
Interesting request - could you show us what you'd like to see? It's especially helpful if we could see it in the context of a web part.

Thanks!

**Comment by ssandu** [comment]
This is my client web part now and some of your samples modified
![captura1](https://cloud.githubusercontent.com/assets/5037954/10738574/b643b20c-7c20-11e5-9145-cda7307898ef.PNG)
![captura2](https://cloud.githubusercontent.com/assets/5037954/10738581/bbcb179c-7c20-11e5-84d3-944e9a2253e3.PNG)

**Comment by ericthompson** [comment]
Thanks for showing us this - it was great to see what you're trying to do. We can pass the feedback for the need for a more "compact" list item along to our design team. We'll let you know when we've got updates!

**Comment by ssandu** [comment]
Hi Eric
I don't want to use primaryText because the app part will be inserted on the home page of an O365 site collection and there that primaryText will be the largest font on the page. It doesn't look nice. On the left/top I have navigation links which have the same font as secondaryText.

**Comment by ericthompson** [comment]
Ah, I see. The ListItem you're using is intended to be a hero component (e.g. the primary component on the page/app/add-in), so I can understand how the large size of the primaryText could throw off your visual hierarchy.

I still wonder if a compact variant of the ListItem where the text is smaller would help - especially if it's the same/closer in size to the secondaryText.

**Comment by ssandu** [comment]
A MiniList maybe ?

**Comment by ericthompson** [comment]
The request makes sense. We don't have an ETA, but we'll work with our partners and provide an update as soon as we can.

**Comment by jedunn** [comment]
I think additional list styles and layouts are a great idea. To make sure I understand this particular context fully I have one Q: Do we have a screenshot or sample of the o365 homepage where this web part will sit?

**Comment by ssandu** [comment]
The app part screenshot is above. It is called Sarcini nerezolate. The scroll bar there looks like from another world ☺

**Comment by ericthompson** [comment]
I think what @jedunn is getting at is a screenshot showing the list items in the greater context of the overall page. This would allow us to get a sense of how the list item sits in comparison to other elements on the page.

**Comment by ssandu** [comment]
@ericthompson you are right.Here's a sample site with secondaryText. As you can see it looks like the right part of the page. Imagine how it looks like with primaryText. It will be the largest font (larger than web part titlle) on the page even maybe it's not so important.
![site](https://cloud.githubusercontent.com/assets/5037954/10990618/c2978d40-845d-11e5-94d5-7fb736ab3d22.png)

**Comment by mikewheaton** [comment]
We'll run this by our designers to see what we can provide for a smaller ListItem component.

**Comment by mikewheaton** [comment]
While there is no schedule for this, I've added it to [our roadmap](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md) as we know that list items are important to many scenarios. We want to provide generic list items that are easier to customize.
