### ISSUE TITLE
Dropdown title wraps text

### ISSUE THREAD

**Issue by dmitriyyepishin** [OfficeDev/Office-UI-Fabric#190]
If selected option text is wider then the dropdown title span element, the text wraps and shows outside the dropdown label.

![image](https://cloud.githubusercontent.com/assets/13841696/10823123/626a5dc2-7e17-11e5-9cac-ca6aba01858e.png)

**Comment by ericthompson** [comment]
Good catch - we'll look into it!

**Comment by ericthompson** [comment]
Looks like this one was fixed by #229! Let us know if you notice anything else!
