### ISSUE TITLE
Increment/decrement component

### ISSUE THREAD

**Issue by kennywangjin** [OfficeDev/Office-UI-Fabric#196]
is it possible to have numeric textbox component for form?
the normal input[type='number'] looks pretty much same as input[type='text'].
if we could have the numeric textbox, just as the nice datepicker control, it would be much easier to use office-ui-fabric for productions.

**Comment by ericthompson** [comment]
We'll look into this one - seems like a good request.

Other than changing the type, what kinds of design details are you looking for / thinking about?

**Comment by kennywangjin** [comment]
thanks for your response.
the numeric box should have two icons 'increase' and 'decrease' to inform users that they could just click the buttons to change the number other than typing numbers. Also, these icons could inform the users that this input accepts only numbers, not strings.
and the standard 'step' attribute should be considered.
Anyway, the numeric textbox could tell the users that what is acceptable in the input (numbers only, not strings) and is easier to use (mouse click, not have to type numbers). 
Thanks.

**Comment by ericthompson** [comment]
Ah, interesting then this is more of an increment/decrement component. I think, on our end, a numeric input component would be more akin to a textbox with special alignment and an input mask.

For our bookkeeping, I'll rename this to reflect how we're thinking about it and what you've asked for. We'll loop back when we've got updates to share.

Thanks!

**Comment by mikewheaton** [comment]
This would be a useful component, but it's not something we have a need for in product at this time and therefore can't make it a priority. I've added it to [our roadmap](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md) as a potential future component. If you do build it, @kennywangjin, we'd be interested to see your implementation.
