### ISSUE TITLE
local office365 icons font:

### ISSUE THREAD

**Issue by kennywangjin** [OfficeDev/Office-UI-Fabric#197]
office365icons font-family references the source from Microsoft public sites.
but sometimes, we have to use it in intranet without internet access, then it will be some problems for the default styles.
please set the styles to use the local fonts 'src' and let the fonts downloadable.

**Comment by ericthompson** [comment]
Right now, the license only allows the fonts to be pulled from the CDN, and the font files cannot be distributed on their own (i.e. download locally and then distribute).

**Comment by reego-fr** [comment]
Hi,
was the license updated ? 
From http://aka.ms/fabric-font-license I don't read anything that would prevent one from downloading the assets from CDN and make them available from a locally accessible server for use in intranet-only Office Add-in. Or am I totally wrong ?
