### ISSUE TITLE
Bug for datepicker:

### ISSUE THREAD

**Issue by kennywangjin** [OfficeDev/Office-UI-Fabric#200]
"go to previous month" arrow button in calendar view (days view) will break the component.
please confirm.

**Comment by Jahnp** [comment]
Which version are you experiencing this on? Have you tried the latest on the `master` branch to see if this still repros? There's been a fair bit of work on DatePicker since the last release, especially https://github.com/OfficeDev/Office-UI-Fabric/pull/184, which sounds like it may fix the issue.

**Comment by ericthompson** [comment]
OK - we're not seeing this error anymore on our end. Please reping if you notice it again.
