### ISSUE TITLE
SearchBox Label Incorrect Positioning

### ISSUE THREAD

**Issue by ryankmcintyre** [OfficeDev/Office-UI-Fabric#203]
The label for SearchBox shows inside the search field if using Chrome, but in Edge and IE the label is shown to the right of the input field with the icon above the text label.

**Comment by ericthompson** [comment]
Interesting... we're actually not getting *that exact* bug, but we're seeing that the placeholder text blocks selection of the SearchBox.

What versions of IE and Edge are you currently using?

**Comment by ryankmcintyre** [comment]
Edge is 20.10240.16384.0
IE is 11.0.10240.16431 (also has "Update Versions: 11.0.22")

**Comment by ericthompson** [comment]
Thanks for the extra info - we'll look into this one.

**Comment by mikewheaton** [comment]
Looks like this has been fixed by @wdo3650.
