### ISSUE TITLE
Hero Button Incorrect Position in Office

### ISSUE THREAD

**Issue by ryankmcintyre** [OfficeDev/Office-UI-Fabric#204]
When using a hero button (ms-button--hero) within Office Add-In, the office.css adds a line-height attribute to all buttons with a value of 16px. This causes the button icon and label to not be positioned properly in the span tag and in IE and Edge the top of the icon is cut off. 

Setting line-height to normal fixes the positioning.

**Comment by ericthompson** [comment]
You're right to set the line-height back to normal, @ryankmcintyre. Since office.css is not a part of Fabric, please file an issue against that repo so they're aware. Thanks!

**Comment by ryankmcintyre** [comment]
I'm sure the office.css folks have a reason for setting line-height. It would be nice if the UI Fabric could include an override to set line-height to normal for folks using the fabric within Office.

**Comment by ericthompson** [comment]
After thinking about it some more, this seems easy enough to include and it **is** important for us to work well with office.css. We'll get something out as soon as possible. Thanks!

**Comment by ericthompson** [comment]
OK - let us know if you still have any trouble, but #230 should fix it for you!
