### ISSUE TITLE
Release schedule?

### ISSUE THREAD

**Issue by unindented** [OfficeDev/Office-UI-Fabric#211]
What's the release schedule for this project? Fixes have been piling for a month. It'd be nice to start benefitting from them...

**Comment by ericthompson** [comment]
Completely our bad - we've been lagging behind as our team has worked on a bunch of big projects (like the [site](http://dev.office.com/fabric)). We just made our [big 1.2.0 release](https://github.com/OfficeDev/Office-UI-Fabric/releases/tag/1.2.0), and we plan to move to a 2 week cadence with absolutely nothing waiting longer than a month. We apologize for the pretty extreme delay in this release!

**Comment by unindented** [comment]
:+1:
