### ISSUE TITLE
Possible license issue copyright vs. MIT License

### ISSUE THREAD

**Issue by StfBauer** [OfficeDev/Office-UI-Fabric#216]
When you take a look at the less files it says "Copyright by Microsoft". On the other hand when I check the git hub repository it use the MIT Licenses.

Which license is now the correct one?

Thanx.

**Comment by ericthompson** [comment]
It can be a bit confusing! Actually, the License and the copyright don't conflict since Microsoft *owns* the code but *licenses* it under an MIT license. Hope this helps!

**Comment by StfBauer** [comment]
Thanks for the update.
