### ISSUE TITLE
HTML view of Dropdown documentation missing <i> tag

### ISSUE THREAD

**Issue by digitalhurricane** [OfficeDev/Office-UI-Fabric#217]
In the HTML tab of the [examples for the Dropdown and Dropdown - Disabled](http://dev.office.com/fabric/components/dropdown) the `<i>` tag before the `<select>` is missing that is needed in order for the down caret icon to appear.

Everything shows up correctly in the Example tabs because the tag is in the source for those.

**Comment by ericthompson** [comment]
OK - we actually think we know what's happening here. It looks like the CMS might be ripping that line of code out. Ouch!

Good find - we'll put it on the backlog and scan the rest of the components as well to see if it did something similar. Thanks!

**Comment by ericthompson** [comment]
OK - we fixed up the documentation so that we don't get these tags dropped! Let us know if you notice more problems.
