### ISSUE TITLE
Panel not working (ie9 & ie10)

### ISSUE THREAD

**Issue by brannmar** [OfficeDev/Office-UI-Fabric#218]
When trying to use Panel with ie9, it is not working at all. 

http://dev.office.com/fabric/resources-and-faq#browser-compatibility
says that ui-fabric is compatible with ie9. 

To replicate the issue. Start ie9 (for this example goto: http://dev.office.com/fabric/components/panel) You can not open any panel at all.
When trying to use panel with ie10 the overlay is the only thing clickable on the site. So when you are trying to click on a link to open the panel. You are not acctually clicking the link but the overlay. Nothing else is clickable.

**Comment by ericthompson** [comment]
@brannmar - good catch. We've actually got a PR out that *should* fix this - we'll need to test to to confirm. I'll leave this open until we get a chance to test it, and get it merged in. If not, we'll address it in a different PR. Thanks!

**Comment by ericthompson** [comment]
Looks like #209 fixed this for ie10. We're looking at the problem for ie9 - I'm not even seeing the button to trigger the panel :-/

**Comment by mikewheaton** [comment]
We're dropping support for IE9, and the latest build from the master branch is now working in IE10.
