### ISSUE TITLE
Panel animation ie9

### ISSUE THREAD

**Issue by brannmar** [OfficeDev/Office-UI-Fabric#219]
IE9 cant handle the slide/fade CSS animation of a panel. The Panel gets "stuck" on one side. It doesn't seem to get triggered by any of these events. "animationend webkitAnimationEnd MSAnimationEnd"

Possible cause it is not supported in IE9: http://www.impressivewebs.com/css3-support-ie9/

**Comment by ericthompson** [comment]
Thanks for finding this one - looking into it!

**Comment by SharePointOscar** [comment]
I see that the office dev site actually has the carousel component, guess the version on Bower is just not the latest....

Thank you
________________________________

**Comment by mikewheaton** [comment]
Closing this issue as we're now dropping support for IE9.
