### ISSUE TITLE
Carousel Component

### ISSUE THREAD

**Issue by SharePointOscar** [OfficeDev/Office-UI-Fabric#220]
Wondering when a Carousel component will be included.

**Comment by ericthompson** [comment]
Soon... very soon... I'll leave this open until we've got it in so you'll be aware!

**Comment by SharePointOscar** [comment]
Awesome thanks Eric!  At one point I'll start contributing on the repo as well.

Cheers,
Oscar
________________________________

**Comment by mikewheaton** [comment]
Was it @philworthington who worked on a Carousel component? How much work is involved in getting into Fabric as a component?

**Comment by ericthompson** [comment]
@battletoilet worked on this one and we're still working towards design approval before pulling in.

**Comment by Jahnp** [comment]
After discussing with the team, we decided that this component doesn't make sense right now. We can revisit the Carousel if there's a future need.

**Comment by gunjandatta** [comment]
Can we re-open this issue? A carousel component would be useful.

**Comment by mikewheaton** [comment]
@gunjandatta: Are you using [Fabric React](https://github.com/OfficeDev/office-ui-fabric-react)? I can add a component request to our Trello board.

**Comment by gunjandatta** [comment]
Yes, I'm using the Fabric React Framework, and if you could add a request to the Trello board I would really appreciate it.

**Comment by mikewheaton** [comment]
Added here: https://trello.com/c/lfvOTWeE/16-carousel

**Comment by bendewey** [comment]
What's the status on the carousel?  There doesn't seem to be any activity on the trello board or fabric react side.  Does this need to be added to the fabric first before becoming a react component?

**Comment by mikewheaton** [comment]
It's probably best to open an issue in the [Fabric React](https://github.com/OfficeDev/office-ui-fabric-react) repo for this feature request.
