### ISSUE TITLE
Create a "multiple" select element

### ISSUE THREAD

**Issue by oising** [OfficeDev/Office-UI-Fabric#221]
I would suggest mapping this to List or ListItem and using jquery $.fn.ListBox or something to apply the effect.

**Comment by mikewheaton** [comment]
You mean a `select` element with the `multiple` attribute ([example](http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select_multiple)), right? I don't believe this is part of our design language. Could you provide more details on what you're trying to achieve?

**Comment by oising** [comment]
What I'm trying to achieve? Seriously? How about parity with vanilla HTML -- seems like a reasonable goal, no? ;)

**Comment by mikewheaton** [comment]
We like to ask about the scenario in case there's an alternate component that might come recommended by our designers. A checkbox list is usually preferable to a multiple select (touch friendly, no keyboard needed, etc.) but in your case that would make for a funky interface. The multiple select seems reasonable.

I'll dig around in our pattern library and see if anything like this has been designed before, and ask @ericthompson where we can place this in our backlog.

**Comment by oising** [comment]
Sounds great -- thanks.

**Comment by mikewheaton** [comment]
We discussed this with design today and there are no plans to create a `<select multiple='multiple'>` component. There are concerns around touch friendliness and accessibility, and it's not a pattern we have in product.

**Comment by shaipetel** [comment]
FYI if anyone still interested, we just implemented this in our own hosted version of Office UI Fabric JS.

It has a few more fixes, changes, and we are hosting it for free on our servers.

If you are interested, here it is:
https://kwizcom.blogspot.ca/2017/09/office-ui-fabric-js-multi-select-support.html

I'd love to hear comments on what we done, and hopefully soon we will upload all our source to GitHub.
