### ISSUE TITLE
Consider implementing JQuery fn functions for all Fabric components

### ISSUE THREAD

**Issue by oising** [OfficeDev/Office-UI-Fabric#222]
I would like to able to apply to, or create, dynamic fabric UI elements using jquery functions. Also, please implement the standardized "destroy" and "refresh" commands. See my comments on the folllowing issue: https://github.com/OfficeDev/Office-UI-Fabric/issues/159

**Comment by janpieterz** [comment]
For me, creating a dependency on jQuery would actually 'ruin' the potential of this for me.

**Comment by ericthompson** [comment]
I think this gets to the heart of the issue of our response in #159 - relying heavily on certain tools empowers some folks and slows down others. The right thing to do here is for us to leave this issue open with a **help wanted** tag, and recommend a community-driven fork of the project to help make the truly jQuery-focused flavor of the toolkit available for others.

We're currently evaluating paths forward that would allow us to reduce our dependencies, and we can provide an update as soon as we have a more concrete answer.

**Comment by oising** [comment]
The point is certainly not to create a "dependency" on jQuery. There must be some medium where we can have an entirely independent fabric.jquery.js file that uses the assets in an abstracted fashion.

**Comment by mikewheaton** [comment]
For the core Fabric project we're moving away from jQuery, as it's not necessary to demonstrate the basic functionality of the components. We'll be making the switch to TypeScript instead, and have noted this in [our roadmap](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md). Of course, developers are free to interact with Fabric components using whatever framework they prefer.

**Comment by andrewconnell** [comment]
:+1: Awesome to see you guys are moving away from the jQuery dependency! We did the same with [ngOfficeUiFabric](https://github.com/ngOfficeUIFabric/ng-officeuifabric) and using Angular + vanilla JavaScript and if necessary, Angular's jqLite to handle these cases.

**Comment by andrewconnell** [comment]
How does this impact the date picker & `pickadate.js`?

**Comment by mikewheaton** [comment]
That's a good question, @andrewconnell. Eventually we want to have everything in TypeScript with no external dependencies, but the date picker is clearly going to be a lot more complex than any other component. There's a good chance that it will rely on jQuery and Pickadate for a while.
