### ISSUE TITLE
Consider implementing actual html5 components for Fabric elements

### ISSUE THREAD

**Issue by oising** [OfficeDev/Office-UI-Fabric#223]
You guys use the term "component" a lot, which is unfortunately pretty topical right now and has nothing to do with your use of the term. HTML5 components are a real thing, and it would be nice to see Fabric offer support for them; even non-evergreen browsers can support them by way of frameworks and polyfills like https://www.polymer-project.org/1.0/

**Comment by mikewheaton** [comment]
This is an option we could consider if there's enough demand. Right now most requests are for React and Angular components, and there are some open source projects started: [ng-OfficeUIFabric](https://github.com/ngOfficeUIFabric/ng-officeuifabric) and [react-fabric](https://github.com/ngOfficeUIFabric/ng-officeuifabric). If you've been implementing Fabric components in Polymer we'd love to take a look.

**Comment by mikewheaton** [comment]
I've added this to [our roadmap](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md) as a potential feature.

**Comment by gautamsi** [comment]
I am working on Aurelia component [gautamsi/aurelia-OfficeUIFabric](https://github.com/gautamsi/aurelia-OfficeUIFabric/)

Most work is in dev branch for now. Need to write documentation and API information. 

Following is working

- Button
- List
- List Item
  - List Item Action - so that you can add click events
- Persona
- SearchBox - with optional Search button  which fires search event on mousedown
- Spinner
- Overlay (needs improvement)

**Comment by mikewheaton** [comment]
Wow, nice work @gautamsi! We'll call out your project on our [documentation site](http://dev.office.com/fabric) in an update soon.

**Comment by gautamsi** [comment]
thank for the appreciation. I have just merged dev to master, adding [NavBar and ContextualMenu](https://github.com/gautamsi/aurelia-OfficeUIFabric/pull/1) https://github.com/gautamsi/aurelia-OfficeUIFabric/pull/1. also has sample page (very ugly for now - now that I have NavBar I can crate multiple views for sample soon:)).

**Comment by oising** [comment]
Very nice, @gautamsi ! Aurelia is where it's at right now - Rob E. and crew are doing a stellar job.
