### ISSUE TITLE
Consider to add postcss autoprefixing to build process for cleaner CSS and better legacy browser support

### ISSUE THREAD

**Issue by StfBauer** [OfficeDev/Office-UI-Fabric#232]
Hi,

I would highly recommend to add [postcss autoprefixer](https://github.com/postcss/autoprefixer) plugin to build process of Office UI Fabric. Personally I use it now for more then six month and have a much cleaner code because I don't have to add vendor prefixes manually.

For Office UI Fabric it will provide from my point of view the following three benefits:
- Reduce file size of Office UI Fabric
No legacy vendor prefixes that current browser don't need anymore
- Easy configuration to build Office UI Fabric to target different legacy browsers
- Automated prefixed according to the informations provided by [caniuse](http://caniuse.com) and therefor less bugs

**Comment by battletoilet** [comment]
Hey @StfBauer  we currently run [Gulp Autoprefixer](https://www.npmjs.com/package/gulp-autoprefixer)  to auto-prefix our less files. We were wondering if you are referring to replacing our current autoprefixer? Or suggesting we add this to our build in addition to our Gulp autoprefixer?

**Comment by StfBauer** [comment]
Somehow I look into an old version. Now i've seen that this is currently implemented. The other thing I've are legacy fallbacks in the LESS files. Will you remove this in a future release?

**Comment by mikewheaton** [comment]
@StfBauer: Where are you seeing legacy fallbacks in the LESS files? Those should all be handled by autoprefixer.

**Comment by StfBauer** [comment]
There were some when I last checked the less files. Might recheck the style sheet again but close it for now.
