### ISSUE TITLE
Office-UI-Fabric code snippets for Visual Studio

### ISSUE THREAD

**Issue by kennywangjin** [OfficeDev/Office-UI-Fabric#233]
Could you please consider post to nuget code snippets for office-ui-fabric?
It is terrible to type so many markups just by hand! :)

**Comment by ericthompson** [comment]
Completely understood! Have you tried perusing the [Fabric site](http://dev.office.com/fabric)? There are samples for each of the components and if you click on the HTML tab (included for each component), you can copy/paste the markup from there. This is a super common use case here in the Studio.

Are these the types of snippets you're looking for?

**Comment by kennywangjin** [comment]
Thanks for your reply.
I know the fabric site. But if there are some snippets for visual studio as plugin (not copy and paste), it will be great, just like the bootstrap snippets. :)

**Comment by mikewheaton** [comment]
Thanks for the suggestion, I've added this to the [Fabric roadmap](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md) as a feature we could consider in the future if time permits.

**Comment by manndave** [comment]
See #418

**Comment by manndave** [comment]
There are code snippets available here: https://github.com/Sector43/FabricSnippets.  The snippets are for VSCode, but there is also a small console application there that will convert them to the format required by Visual Studio.
