### ISSUE TITLE
Differences between CDN and bower package

### ISSUE THREAD

**Issue by gabbsmo** [OfficeDev/Office-UI-Fabric#235]
I've diffed CommandBar.css from [CDN](https://appsforoffice.microsoft.com/fabric/1.0/fabric.components.css) with the one in the bower package. Both say version 1.1.3 in the header but they are vastly different.

I've attached a report from WinMerge. Rename it to .html and view it in a browser.

[CommandBarDiff.txt](https://github.com/OfficeDev/Office-UI-Fabric/files/63971/CommandBarDiff.txt)

**Comment by ericthompson** [comment]
Sorry about the delay here! We recently updated our bower package registry, and just double checked - it looks OK on our end. We're seeing the same CSS on both the CDN and the Bower package. Please let me know if they're still different for you.
