### ISSUE TITLE
Tabs in PersonaCard not switching

### ISSUE THREAD

**Issue by TBag** [OfficeDev/Office-UI-Fabric#236]
When you have a page with two persona cards on it the tabs in the persona cards only switch for the first persona card on the page.

This is the file that is the culprit.

https://github.com/OfficeDev/Office-UI-Fabric/blob/master/src/components/PersonaCard/Jquery.PersonaCard.js

How to repro using the attached demo project:

a.	In the Index.cshtml file, un-comment the Microsoft out-of-the-box Jquery.PersonaCard.js reference, and comment out the Jquery.PersonaCard.FIX.js reference.
b.	RUN the sample,
c.	Click first person, then click the tabs in the persona card.  It works.
d.	Click first person to hide persona card.
e.	Click second person, try to switch tabs in the persona card, it does not work.

[DemoIssue.zip](https://github.com/OfficeDev/Office-UI-Fabric/files/65901/DemoIssue.zip)

Here's the differences in the out-of-the-box file and the fixed file.

![personacardfix](https://cloud.githubusercontent.com/assets/1407310/11881529/5e355dd0-a4d5-11e5-8afd-aef8529a3962.jpg)

**Comment by ericthompson** [comment]
This is a great catch - your fix finds the correct card. This is a pretty gnarly scoping issue, and your fix is exactly what we would do. Would you mind submitting a pull request with this fix in it?

**Comment by ericthompson** [comment]
Thanks for the help, @TBag!
