### ISSUE TITLE
TreeView Component(s) planned?

### ISSUE THREAD

**Issue by AlexHiesch** [OfficeDev/Office-UI-Fabric#238]
Hi Guys,

I love the Office UI Fabric Components but to really use it for an app in one of our projects it lacks a TreeView (http://demos.telerik.com/kendo-ui/treeview/index ) or TreeList (http://demos.telerik.com/kendo-ui/treelist/index).

Is by any chance something similar already in your backlog for the near future?

**Comment by ericthompson** [comment]
Hi Alex! We didn't have this on our backlog, but we'll add it and start looking for other patterns within Office / Office 365.

There is a pattern for folder hierarchies within OneDrive that seems inline with TreeView that we could look into getting built out, but the closest thing we have to TreeList is Fabric's [OrgChart component](http://dev.office.com/fabric/components/orgchart). Unfortunately, OrgChart doesn't have the nice nesting indentation that the TreeList does.

Here's the folder hierarchy within OneDrive:
![image](https://cloud.githubusercontent.com/assets/1420854/12043307/dccf1fd4-ae38-11e5-927d-3dc1b91bb537.png)

I'll mark this one and we'll update you when we've got something!

**Comment by mikewheaton** [comment]
While we have no immediate plans to add this to Fabric, I've added it to [our roadmap](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md) so that we don't lose track of your request. If you build a tree view using Fabric classes we'd love to see your code.

**Comment by AlexHiesch** [comment]
Wonderful, thanks for listening. I love this direct interaction possibilities. I'll try to support you guys how ever I can.

**Comment by stewartadam** [comment]
What happened to this? That roadmap link points to the new Trello board, and I can't find this request on it.

**Comment by mikewheaton** [comment]
Sorry about that, I linked to the Fabric Core board rather than the one for Fabric JS. Here is a link directly to the card: https://trello.com/c/hpLEICo1
