### ISSUE TITLE
Ms-Searchbox not activated if you click on the label

### ISSUE THREAD

**Issue by mandiros3** [OfficeDev/Office-UI-Fabric#239]
The ms-Searchbox consists of a  textfield with a label inside of it. If you click on the label the field won't be activated.
![s](https://cloud.githubusercontent.com/assets/1945406/12025515/b48868e8-ad7d-11e5-9f6a-7aebe6f8ec06.PNG)

Suggested fix: Make it so that ms-searchbox-label.click() focuses the field. Quick and easy

```javascript
 $(".ms-SearchBox-label").click(() => {
                $("#searchField").focus();
            });
```

**Comment by wdo3650** [comment]
Thanks for mentioning this @mandiros3. There is currently a bug out on this, #203, and PR #228 for the fix. Stay tuned for updates.

**Comment by wdo3650** [comment]
Just merged in the fix for this. Let us know if this doesn't fix your bug and we'll reopen the issue.

**Comment by mandiros3** [comment]
That was quick! Alright, I will give it a try.
