### ISSUE TITLE
Missing script and css references in bower.json

### ISSUE THREAD

**Issue by StfBauer** [OfficeDev/Office-UI-Fabric#245]
I recognized that some important information in the [bower.json](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/bower.json) file are missing. With the main section wiredep and other dependency checker fail and the [bower packages](https://github.com/bower/spec/blob/master/json.md) is not properly configured.

I manually added the required files to the bower.json. It should look like this.
```
{
  "name": "office-ui-fabric",
  "author": "Office UI Fabric Team",
  "version": "1.1.3",
  "description": "The front-end framework for building experiences for Office 365.",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/OfficeDev/Office-UI-Fabric"
  },
  "main": [
    "dist/css/fabric.css",
    "dist/css/fabric.components.css",
    "dist/js/jquery.fabric.js"
  ],
  "private": false,
  "ignore": [
    "node_modules",
    "bower_components"
  ]
}
```

Can you please include this to make the bower package work properly.

**Comment by andrewconnell** [comment]
:+1:

**Comment by StfBauer** [comment]
Created a [pull request](https://github.com/OfficeDev/Office-UI-Fabric/pull/252) for this issue and added the main section in the bower.json myself.

**Comment by Jahnp** [comment]
This makes sense. Thanks @StfBauer --we've gone ahead and merged your fix in. Closing for now.
