### ISSUE TITLE
Enable Office-UI-Fabric through Bower

### ISSUE THREAD

**Issue by thephoenics** [OfficeDev/Office-UI-Fabric#246]
Since Office UI fabric is already made available through GIT, I think it would be great if you can spend a little more time and make it available through bower. That would make it super easy to integrate and also version-control/dependency-control this library from our code.

**Comment by thephoenics** [comment]
Looks like it is already added to bower, all you need to do is expose it through the readme.

`bower install office-ui-fabric` would do the trick :).

**Comment by StfBauer** [comment]
Well yes you can use it but there is currently a missing option that make the bower package a real useful extension. Documented in [issue #245](https://github.com/OfficeDev/Office-UI-Fabric/issues/245)

**Comment by Jahnp** [comment]
This has been addressed with @StfBauer 's fix in #252--closing for now. Thanks for bringing this to our attention, @thephoenics!
