### ISSUE TITLE
Dropdown component doesn't work...

### ISSUE THREAD

**Issue by elegault** [OfficeDev/Office-UI-Fabric#251]
...or I'm doing something stupid.  A regular select control shows up, but only the dropdown icon is visible for the ms-Dropdown select.  See my shared Napa project and /App/Read/DropdownTest.html: http://aka.ms/V127h2.

Something looks weird in /Content/Dropdown/Jquery.Dropdown.js.  While the main function initializes, none of the helper methods ever get executed (see my comments).  It certainly looks and works differently compared to the code in the Jquery.*.js files for the other Fabric components.

Also note the typos ("`<option>Choose a sound&hellip;</option>`") and missing value attributes in Dropdown.html and Dropdown.Disabled .html.  The sample at dev.office.com is okay.

**Comment by elegault** [comment]
Any ideas @battletoilet  or @ericthompson?

**Comment by elegault** [comment]
I've got this working in a different project, so the problem is clearly on my end.  Sorry!  Carry on...

**Comment by ericthompson** [comment]
Haha - no worries! Let us know if it comes back up.

**Comment by elegault** [comment]
I'm going to reopen this because I need to get to the bottom of what the problem is - whether it is on my end or not.
Problem 1: See http://aka.ms/Dtxwlh. Note how the dropdown arrow is not correctly rendered. I can't see anything obviously wrong with my markup.
Problem 2: See http://aka.ms/V127h2. The dropdown isn't rendered at all. I'm not sure if the problem is in DropdownTest.html or ../../Content/Dropdown/Jquery.Dropdown.js or in the fabric.css files via CDN.  Feel free to alter the head to reference the local fabric.css files in ../../Content/css instead.

Any guidance would be appreciated!

**Comment by elegault** [comment]
OY! The problem is simple - in fabric.components.css .ms-Dropdown-select has display:none. No wonder it's not visible, but why is this hidden by default??

**Comment by mikewheaton** [comment]
`.ms-Dropdown-select` targets the actual `<select>` element, which is hidden and replaced with a JavaScript-generated dropdown. This allows us to style it correctly. The JavaScript should be hiding the original element and generating an HTML dropdown.

**Comment by elegault** [comment]
My bad, I remember reading about that behaviour before. But it still doesn't work, no dropdown is ever seen - see my sample Napa project: http://aka.ms/V127h2. I can't figure out what's wrong and it's driving me nuts!

**Comment by mikewheaton** [comment]
Well this is embarrassing. It turns out that the code sample on our documentation site is showing the HTML _after_ it has been modified by JavaScript. So the code we provided doesn't work. Please see **[this CodePen](http://codepen.io/mikewheaton/pen/WrKwyE)** for a working sample. Let me know if you have any trouble and I'll get right back to you.

**Comment by mikewheaton** [comment]
Changing this issue from a bug to a documentation issue.

**Comment by elegault** [comment]
Thanks Mike - your sample works, but the markup is effectively identical to the sample at dev.office.com. Am I missing something?

**Comment by elegault** [comment]
The return function in Jquery.Dropdown.js never fires but it's definitely being initialized and I am calling $(".ms-DropDown").Dropdown().

**Comment by mikewheaton** [comment]
You're right, it looks like you do have the correct markup there. Looking more closely at DropdownTest.js, I think the issue may be that you're calling `.DropDown()` with a capital D rather than `.Dropdown()`. Could you give that a try?

**Comment by elegault** [comment]
I'm already using .Dropdown, not .DropDown! Like I said, the main function gets hit with a breakpoint, but the return function never gets hit. It seems like there's a wrong name _somewhere_ but I'm stumped! I may be doing something stupid but I'd sure like to know what it is!

**Comment by mikewheaton** [comment]
In DropdownTest.js I'm still seeing `DropDown`:

![image](https://cloud.githubusercontent.com/assets/1382445/12731787/691f4d92-c8e7-11e5-9510-14ddf21bca3e.png)

**Comment by elegault** [comment]
Oh for the element name oh geez I'll try it when I get back

Sent from my Windows Phone
________________________________

**Comment by elegault** [comment]
(I mean the 'class' name) Yup, that works. I'm an idiot. I hate typos. Sorry! Carry on folks and thanks for your patience!

**Comment by mikewheaton** [comment]
Happy to help – wish I'd spotted it sooner for you. You're not the first to make a typo and you certainly won't be the last. :smile:

**Comment by elegault** [comment]
Haha true! But BOO to all these IDE tools I have loaded in Visual Studio and none of them caught it :-|

**Comment by AnushKatari** [comment]
@mikewheaton , I face a similar issue. When i tried to call $('.ms-Dropdown').Dropdown(), it just gives a blank panel instead of showing options 
![image](https://user-images.githubusercontent.com/33859845/42860716-744c8cc8-8a75-11e8-9f5b-f5fb7fb16bef.png)

this is how the drop-down items look(blank panel)
![image](https://user-images.githubusercontent.com/33859845/42860740-90460e18-8a75-11e8-938e-d215473438cf.png)

Please bare me if its wrong from my side. I'm a newbie to Fabric.
