### ISSUE TITLE
Version number in header of distribution CSS incorrect for 1.2.0 (says 1.1.3)

### ISSUE THREAD

**Issue by andrewconnell** [OfficeDev/Office-UI-Fabric#262]
In the distribution of 1.2 either downloaded from the repo's release or installed via NPM / Bower, the source in the CSS files says the file is version 1.1.3, when it appears it is really 1.2.

**Comment by ericthompson** [comment]
Woah - thanks for bringing this to our attention, @andrewconnell!

We're working to fix this and get everything on the CDN right now.

**Comment by andrewconnell** [comment]
:+1:

**Comment by mikewheaton** [comment]
This is fixed in 1.2.1. Unfortunately the CDN is still out of date, so you'll have to [download a copy](http://dev.office.com/fabric/getting-started#download) for the latest version.
