### ISSUE TITLE
Deprecated gulp plugins

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/Office-UI-Fabric#264]
When first installing NPM to build Fabric, there are deprecation warnings for four of the plugins we're using:
- gulp-minify-css
- gulp-uglifyjs
- lodash
- npmconf

Everything works fine so I'll mark this as an enhancement.

![image](https://cloud.githubusercontent.com/assets/1382445/12280734/18b84216-b945-11e5-92de-224c7daa217a.png)

**Comment by ericthompson** [comment]
Thanks, Mike :+1:

**Comment by battletoilet** [comment]
Fixed in PR  #368
