### ISSUE TITLE
Navbar menu not closing

### ISSUE THREAD

**Issue by khassan82** [OfficeDev/Office-UI-Fabric#265]
menu not closing if clicking on other navbar item having sub menu
![image](https://cloud.githubusercontent.com/assets/12068212/12284726/1fd8ae88-b980-11e5-8cf7-026ce621ffbc.png)

**Comment by mikewheaton** [comment]
I've [create a repro of the issue](http://codepen.io/mikewheaton/pen/OMjjqG). Investigating now.

**Comment by mikewheaton** [comment]
Before opening any menu, I've added a command to close any neighboring menus. Please see the **[demonstration of the fix](http://codepen.io/mikewheaton/pen/mVMpWx)**. The logic of opening/closing menus within the NavBar could use some refactoring, but this fixes the immediate issue.

I'll create a branch and pull request to get this fix into the next version of Fabric.
