### ISSUE TITLE
Set up a new CDN

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/Office-UI-Fabric#268]
In [our documentation](http://dev.office.com/fabric/getting-started) we provide the CDN reference for Fabric 1.0. Are the later and current releases of Fabric on the CDN as well? I tried updating the url (e.g. http://appsforoffice.microsoft.com/fabric/1.2.1/fabric.min.css) with no luck.

Assigning to @notandrew as I think he's in charge of the CDN.

**Comment by mikewheaton** [comment]
Turns out the process for checking in new code to the CDN takes weeks, so the CDN will always be behind if we release regularly. Can we speed up that process, or set up our own on [Azure CDN](https://azure.microsoft.com/en-us/services/cdn/) or [MaxCDN](https://www.maxcdn.com/)?

**Comment by mikewheaton** [comment]
Also, we should make it clear in the documentation that the CDN version is out of date. Otherwise our example code may not work as expected.

**Comment by andrewconnell** [comment]
OR... you could get added to CDNJS. This repo passes their criteria (100+ stars). Once you get submitted, you can include a bit in your config that will have their system include your library in a hourly crawl they do. If it sees you did a new drop (using tags in github repos), it will create a new version, suck in the files you specify and make them available in the directory. So worst case, you are in a public CDN within an hour or so of tagging & pushing a new release => master.

This is what we did for **[ngOfficeUiFabric](https://github.com/ngOfficeUIFabric)**: https://cdnjs.com/libraries/ngOfficeUiFabric

Happy to assist with this... just ping me. We have a separate repo we use for distro of our libraries => NPM / bower / NuGet and CDNJS pulls from that (https://github.com/ngOfficeUIFabric/package-ngofficeuifabric) not where all dev is going on (https://github.com/ngOfficeUIFabric/ng-officeuifabric).

**Comment by mikewheaton** [comment]
CDNJS looks like a very interesting option, and thanks for the offer to assist in getting it set up. We'll discuss our CDN options and leave this issue open until we have a decision.

**Comment by andrewconnell** [comment]
:+1: happy to jump in a chat to discuss (v-aconn)... we are going to see how the auto-update part goes in the next few days as I'm merging 4+ PR's and cutting a new patch release

**Comment by andrewconnell** [comment]
Just piling on... we cut a new release of ngOfficeUiFabric... we updated the version number in our `bower.json` and `package.json` in the repo that we use for distros... sure enough, within the hour the CDNJS saw the change and sucked in our packaged library into their CDN, preserving the old versions.

https://cdnjs.com/libraries/ngOfficeUiFabric

**Comment by notandrew** [comment]
We're still discussing it.  No ETA on when we'd be able to come to a decision on this as there's a lot of moving parts on our side.

**Comment by notandrew** [comment]
We have made changes to our deployment process, decreasing the time between release and when the files appear on the CDN.  At this time, we don't have plans to switch CDN providers.
