### ISSUE TITLE
Use CodePen to demonstrate components

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/Office-UI-Fabric#269]
Our documentation site provides sample HTML and JS for each component (e.g. [dropdowns](http://dev.office.com/fabric/components/dropdown)) but requires developers to set up Fabric locally to test these components. If we were to create an example of each on CodePen, we could use [Embedded Pens](http://blog.codepen.io/documentation/features/embedded-pens/) to present the code and allow developers to easily fork it and test modifications to the component, CSS overrides, etc.

**Comment by mikewheaton** [comment]
I created a **[base pen that can be forked](http://codepen.io/mikewheaton/pen/gPGzgX)** to demonstrate Fabric features or attempt to reproduce bugs. We can give this a try and see if it's helpful.

**Comment by chriscoyier** [comment]
You can send people to the CodePen Editor with your code filled in to a brand new Pen using a URL like:

http://codepen.io/pen?template=gPGzgX

**Comment by mikewheaton** [comment]
Perfect, thanks @chriscoyier!

**Comment by andrewconnell** [comment]
That's what I did for the http://officeuifabric.com site, here's the list: http://officeuifabric.com/components/list/

I find it MUCH easier to demo the components than the way they are currently demo'd on the http://dev.office.com/fabric site (the markup is very hard to read & consume).

**Comment by mikewheaton** [comment]
Closing this for now. We may investigate it more in the future, but want to focus on other updates like better component documentation for now.
