### ISSUE TITLE
Duplicate class in ListItem sample code

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/Office-UI-Fabric#272]
See the middle of the screenshot below: `is-selected is-selected`

![image](https://cloud.githubusercontent.com/assets/1382445/12337254/ca954d0c-babd-11e5-8ffb-9135c4b09513.png)

**Comment by ericthompson** [comment]
I'm only seeing `is-selected is-selectable` which brings up the checkbox for a selectable item. I'm seeing the same in my local builds as well.

![image](https://cloud.githubusercontent.com/assets/1420854/12534463/1958e414-c20f-11e5-9500-3b9bc911593d.png)


Closing, but please reopen if I've missed something.
