### ISSUE TITLE
Inappropriate table implementation

### ISSUE THREAD

**Issue by StfBauer** [OfficeDev/Office-UI-Fabric#276]
I know there is another issue concerning the table implementation because colspan or rowspan cannot be applied to the div based table.
I played a little bit around by replacing the div and span element with regular table, tr, and td elements. The currently implemented style sheets work correctly. At least the table component should provide the original semantic correct implementation (a version without div). Plus in addition if needed the div based table.

The following image shows the semantically correct implementation of the table. The component works the same way.

<img width="505" alt="screen shot 2016-01-16 at 12 39 22" src="https://cloud.githubusercontent.com/assets/5503835/12372178/73903714-bc4e-11e5-81ce-1608761c2b38.png">

For responsiveness the should be some sort of tutorial how to deal with tables in responsive scenarios. Because this can lead to problems in both implementations div based or table based.

**Comment by mikewheaton** [comment]
This is related to #192, where the suggested fix is to replace the `div` based table with an actual `table` element. We'll need to review our design language and current products to determine the best behavior(s) for adapting to smaller screens.

In the meantime, it's great to know that our existing classes can be applied to a standard table!

**Comment by StfBauer** [comment]
:+1: Great and understandable. 

I was not really surprised by this behavior because all the css does is to build a table but with the wrong elements and only applies display values for table, table-row, table-cell.

I found out that in most cases for larger table a surrounding div that allows horizontal scroll works great on mobile device.

**Comment by mikewheaton** [comment]
Closing this issue. We'll use #192 to discuss a change from `div` to standard `table` elements in our recommended HTML.
