### ISSUE TITLE
Progress Indicator's CSS not in main CSS distro?

### ISSUE THREAD

**Issue by andrewconnell** [OfficeDev/Office-UI-Fabric#281]
Is it an oversight / bug or is it intentional to not have the [ProgressIndicator's styles](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/src/components/ProgressIndicator/ProgressIndicator.less) in the main CSS distro for components?

For instance, the class `ms-ProgressIndicator-itemName` is not in the generated CSS files within the `dist` folder in the NPM / Bower distros in v1.2.1.

**Comment by ericthompson** [comment]
Whoops! Looking into this now - thanks for bringing it to our attention!
