### ISSUE TITLE
ContextualMenu header text out of alignment

### ISSUE THREAD

**Issue by s-KaiNet** [OfficeDev/Office-UI-Fabric#283]
When using list item `ms-ContextualMenu-item--header` with regular (not multi selection) menu, then header is not aligned with other menu items.  
Here the [plunk](http://plnkr.co/edit/4sTsxYedCgn5IDR5wFUU?p=preview) demonstrating the issue.

**Comment by mikewheaton** [comment]
Interesting. In our [reference ContextualMenu](http://dev.office.com/fabric/components/contextualmenu) we only use the headers on multi-select (`ms-ContextualMenu--multiselect') menus. We have no examples in our design documentation of a standard contextual menu using the headers, so it looks like we neglected to test this.

I'll get this fix into Fabric for the next release. In the meantime you can apply a CSS override to pull the header back into alignment:

```
/* Temporary override to pull header into alignment. Remove after updating Fabric. */
.ms-ContextualMenu-item--header {
  padding-left: 18px;
}
```

**Comment by mikewheaton** [comment]
Also made the change in @battletoilet's 'less-sass-components' branch to be sure we don't lose this fix when that branch is merged in.

**Comment by mikewheaton** [comment]
I've created pull request #285 for this. Once it's been approved and merged in we can close this bug.
