### ISSUE TITLE
Plans for overall layout controls?

### ISSUE THREAD

**Issue by andrewconnell** [OfficeDev/Office-UI-Fabric#284]
Today fabric is components you use *within* an application.

What I'm curious about are your plans (if any) for full layout controls. Specifically, things that could be use to mimic the SharePoint UX, OneDrive UX, OWA UX... I'm not saying i want to do that, but consider the scenario where I wanted to. There is clearly a design language here for this stuff.

This is something that's come up a few times when people considering using Fabric / Material for a new app. This is one area where it's hard not to make the case for Material for your app if you are building a complete web app in need of a full UX. It's something we're starting to discuss with ngOfficeUiFabric but if we did it, it would only apply to Angular apps & miss out on anyone using React / Knockout / Aurelia / multi-page web apps. So we want to see what you are doing before we go forward.

We're seeing a lack of things like general layout / header / footer / quick launch (left-nav) / tree view to name a few things.

Ref - Material has something like this: https://material.angularjs.org/latest/layout/introduction

**Comment by mikewheaton** [comment]
This is something our team will have to discuss (I've added a label here so we don't forget it) and see if/when it fits into our road map. I'll leave this issue open and comment back when we have an update. Thanks for the suggestion!

**Comment by mikewheaton** [comment]
We discussed this and while it's something we'd like to provide in the future, at this point we're not seeing enough common patterns to provide layouts. I've created a [Fabric roadmap document](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md) where we will track potential features and improvements like this.

**Comment by andrewconnell** [comment]
Disappointing, but thanks for the transparency & roadmap

**Comment by raix** [comment]
@mikewheaton Can't add this FR on the trelloboard - I was looking for some basics like in react-toolbox. *(maybe have a separate package for `office-ui-simple-layout` providing the basics `Layout`/`NavDrawer`/`Panel `/`Sidebar` etc. (ref. the components you already have in the demo)*
