### ISSUE TITLE
JavaScript Samples Not Working

### ISSUE THREAD

**Issue by wdo3650** [OfficeDev/Office-UI-Fabric#286]
The Vanilla Javascript variants for the component samples aren't rendering in the component sample.  Specifically this is happening for the Spinner.

**Comment by andrewconnell** [comment]
Same seems to be true with the command bar: http://dev.office.com/fabric/components/commandbar. Clicking doesn't do anything with the search or any demo of the dropdown.

**Comment by mikewheaton** [comment]
It looks like the version of our JS files (and Fabric in its entirety) is currently out of date on the Fabric docs site. We'll get this fixed right away.

In the meantime, you can view working demos by [downloading a copy of Fabric](https://github.com/OfficeDev/Office-UI-Fabric/releases/latest) and viewing `samples/Components/[component-name]/index.html`.

**Comment by mikewheaton** [comment]
Closing this as the original issue is fixed. We have another issue opened to fix the CommandBar.
