### ISSUE TITLE
Prevent text moving in pivot when font weight changes

### ISSUE THREAD

**Issue by StfBauer** [OfficeDev/office-ui-fabric#288]
This is more a user experience issue than a bug. 

In the pivot component the selected element is bold and color highlighted. In the large pivot the element is defined only be the color.
The problem that I like to address is that the regular pivot elements start to jump around right after the selected element have been deselected. (Simply be clicking the bubbles for example). This issue is caused by changing the font-weight.
This flickering of the font-weight is very irritating because you change something on the UI without actually changing something.

**Comment by mikewheaton** [comment]
The shifting text caused by those font-weight changes isn't ideal. The best solution I'm aware of is to create a hidden pseudo element that makes room for the heavier text (see [this example JSfiddle](http://jsfiddle.net/85LbG/)) but that requires a change to the HTML markup.

Let's leave this open to see if anyone has alternative ideas for improving this.

**Comment by StfBauer** [comment]
I checked the control in SharePoint because the same thing is already implemented there. Looks like the same issue is there too. The font-weight bold shifting exists there as well.
I spotted another bug in the current Office UI Fabric implementation of the pivot.

When you click on the bubbles the selection will be removed. In SharePoint the selection won't be removed because just by clicking the bubbles you just show the extended options and don't make a new selection.

**Comment by mikewheaton** [comment]
There are some design updates coming, so we're going to ask the designers if we'll still be changing the font-weight. If so, we can discuss the best technical solution to fix this.

**Comment by mikewheaton** [comment]
Verified with design that the font weights should be changing to indicate the active state for accessibility. We need to update the large pivot to change its font weight the same as the small one does. Our designs also call for these to have underlines, which we need to add.
