### ISSUE TITLE
Design responsive behavior for tables

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric#292]
Over in #192 we had some interest in making Fabric's Table component responsive. @StfBauer wrote a [blog post](http://www.n8d.at/blog/how-to-handle-table-component-of-office-ui-fabric/) on this and there are other [examples](http://codepen.io/geoffyuen/pen/FCBEg) out there we could consider. We'd like to run this by our internal design team to see if there are any products using responsive tables, or general patterns we might be able to adopt.

**Comment by jbarr33** [comment]
Is there some thought around complementing bootstrap's (responsive) design instead of trying to redo what they have done?  There are probably licensing/copyright issues I'm not aware of but I see no problem putting a bootstrap responsive-table intermingled with Office UI Fabric (I'm doing it now).  The Fabric tables are very verbose and for any sizable table will generate too much HTML.

**Comment by mikewheaton** [comment]
For reference, here is [Bootstrap's responsive table](http://getbootstrap.com/css/#tables-responsive). On small screens they set a max-width and then scroll horizontally.

![image](https://cloud.githubusercontent.com/assets/1382445/12758878/3ae0a35c-c993-11e5-886a-f515b14e0708.png)

Another way to adapt tables to small screens is to turn each row into a section, like the [TableSaw Stack Table](https://filamentgroup.github.io/tablesaw/demo/stack.html) that @ericthompson pointed out.

The discussion on our markup being too heavy is being discussed over in #192. We're going to be suggesting the use of standard `table` elements (including `th`, `tr`, `td`, etc.) rather than `div`s as we do now, which will mean that classes like `ms-Table-row` are no longer necessary. This will give us the same amount of markup as Bootstrap: just a standard `table` structure with a single `ms-Table` class.

**Comment by mikewheaton** [comment]
We have some designers looking at how to handle tables on small screens, and will update Fabric based on their recommendations.

**Comment by mikewheaton** [comment]
While we don't have plans to make the Table component responsive, this will be a requirement for a new details list component that will be added in a future release. It's now included on [our roadmap](https://github.com/OfficeDev/office-ui-fabric/blob/master/ghdocs/ROADMAP.md).
