### ISSUE TITLE
Consider to create grid using SUSY after migration to SASS

### ISSUE THREAD

**Issue by StfBauer** [OfficeDev/Office-UI-Fabric#296]
Just a small suggestion. I might be useful to automatically create the grid system using [SUSY](http://susydocs.oddbird.net/en/latest/) once the migration to SASS have been finished.

You can easily create default classes for Office UI Fabric and custom grid systems can be implemented easily if the content required to have a special kind of grid.

The overall configuration can be stored in a separate file.

**Comment by ericthompson** [comment]
This is really neat - thanks for bringing this to our attention! I'm curious about the team's overall thoughts.

**Comment by mikewheaton** [comment]
We discussed this today and while we like the idea of using SUSY to generate the grid, we don't see enough demand to justify making the change at this time. I'll close the issue for now, but if @StfBauer or anyone else wants to submit a pull request we'd be happy to review it. We just have to be sure that the output CSS doesn't change for our default 12-column grid.
