### ISSUE TITLE
Label consisting of multiple words wrapped on each word

### ISSUE THREAD

**Issue by waldekmastykarz** [OfficeDev/Office-UI-Fabric#302]
When using a spinner with a label as showed in https://github.com/OfficeDev/Office-UI-Fabric/blob/70ad36cb77e1bbf3946cc7555381fd7e9359274c/src/components/Spinner/Spinner.Message.html in ngOfficeUIFabric (https://github.com/ngOfficeUIFabric/ng-officeuifabric/issues/151) we discovered that if the label consists of a few separate words each word is displayed on a new line rather than the label be displayed in a single line. Ideally the length of the wrapper should determine how the label wraps.

**Comment by mikewheaton** [comment]
Thanks for reporting this, we'll look into a fix. For now, here is **[repro of the issue](http://codepen.io/mikewheaton/pen/XXBmZW)**.

**Comment by waldekmastykarz** [comment]
:+1:

**Comment by wdo3650** [comment]
This should be fixed in master.
