### ISSUE TITLE
NavBar rendering not right see image

### ISSUE THREAD

**Issue by gautamsi** [OfficeDev/Office-UI-Fabric#310]
see the menu items, it seems off when search box is active when body width is 481-647px

![navbar bug](https://cloud.githubusercontent.com/assets/5769869/12780052/b3113e32-ca91-11e5-9ded-2fa1797d47f5.png)

repro step:
1. run sample dev server
2. open browser and go to navbar sample page
3. resize window so that body width is between 481-647px
4. click in the search box.

you can also click in the search box and then resize window to see as it happens. Not sure if this issue is only with sample or any NavBar placement

**Comment by mikewheaton** [comment]
Fixed by PR #615. The design has been updated so that search takes over the entire CommandBar or NavBar on screens under 1024px, covering all of the items.
