### ISSUE TITLE
NavBar vs CommandBar

### ISSUE THREAD

**Issue by dmitriyyepishin** [OfficeDev/Office-UI-Fabric#313]
Are there guidelines for when to use NavBar vs CommandBar?

**Comment by mikewheaton** [comment]
I've flagged this as "needs-design" so that we can ask the designers for guidance. The two components are very similar, so we should be more clear in our documentation when to use each, and maybe change the example content to make this more clear.

**Comment by dmitriyyepishin** [comment]
Thanks for looking into this. I think I understand the current difference between them - in Navigation Bar the item that is clicked on is selected (by being underlined) - thus it is useful for navigation, but in Command Bar, the selection does not happen.

The samples are misleading: Navigation Bar sample has an "Upload" button, which get's selected when clicked upon, which does not seem to make sense, and Command Bar has a Categories drop-down, which looks like a navigational button.

It seems to me that these two components should be combined into one and there should be an option to create a navigation element, which would be selected or un-selected when clicked on, or a command element, which would not be selected. 

In additions, the design guidelines (https://msdn.microsoft.com/EN-US/library/office/mt484319.aspx) only mention a Nav Bar.

**Comment by pschaeflein** [comment]
They way I interpret the controls -- the command bar is used to invoke actions on the "current" or "selected" item. As such, I assume I need to provide an href or client script to be invoked when the command is clicked.

I used an href in a project. Doing so added an underline on the link text, so I added text-decoration:none to the ms-CommandBarItem--link class.

**Comment by mikewheaton** [comment]
Confirmed with design: these are two distinct components but we need to improve our documentation so that the reasons for each are clear. We'll update the samples so that CommandBar clearly just has commands in it, and NavBar is for navigation.

**Comment by mikewheaton** [comment]
Apologies for the lack of updates here. In Fabric 3.0 we've decided to remove the NavBar entirely, and have the CommandBar support both typical command buttons and navigation-styled buttons. See these examples:

![image](https://cloud.githubusercontent.com/assets/1382445/15797765/f7424448-29d7-11e6-9cc0-c3e891c309bc.png)

**Comment by dmitriyyepishin** [comment]
That's a great idea. Thanks!
