### ISSUE TITLE
Required and disabled states for the Toggle

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric#315]
There are no required or disabled states for the Toggle component.

**Comment by jshowatt** [comment]
Disabled works in 2.0.1 except that the label color is #333333 instead of #a6a6a6 like choice field labels.

**Comment by mikewheaton** [comment]
Flagging this for design review, as I don't think we have styles for a required toggle. Is it just a change in the label style?

**Comment by mikewheaton** [comment]
There is no required state for a Toggle, which makes sense since it is always on or off with no unspecified or empty state. Where a 'yes' choice is mandatory we recommend using a check box.
