### ISSUE TITLE
Panel header text line height too large

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/Office-UI-Fabric#320]
![image](https://cloud.githubusercontent.com/assets/1382445/12858869/7d4c93d8-cc07-11e5-90eb-f3b38b7bf370.png)

**Comment by notandrew** [comment]
This issue repros with your changes.  We should probably remove the height property and add padding.

**Comment by mikewheaton** [comment]
The problem with removing height is that the content area below it is absolutely positioned, so that when scrolling a panel with a lot of content the command bar and header text stay in place. So we'd have to use JS to set a top position for that content, or have the header scroll out of view.

**Comment by philworthington** [comment]
The header text is within the absolutely positioned contentInner causing it to scroll out of view. This is what we've had by default and how we see panels built in other experiences. It's also safer to remove the height and add padding which I've done in my latest commit to PR #322 . Closing issue.

**Comment by mikewheaton** [comment]
Fixed by PR #615. 

![image](https://cloud.githubusercontent.com/assets/1382445/15729624/ca176912-281a-11e6-980f-361e5db82fe2.png)
