### ISSUE TITLE
dist folder missing in NPM package for 2.0.0

### ISSUE THREAD

**Issue by jjczopek** [OfficeDev/Office-UI-Fabric#323]
Hi,

After updating my `package.json` to require version 2.0.0 of Office UI Fabric, it downloaded the module but the references to CSS files on the pages were not working.

It turned out the there is not `dist` folder in the module folder:
![image](https://cloud.githubusercontent.com/assets/865473/12859694/47697c80-cc58-11e5-8547-6708d2ba5601.png)

As a reference, picture with folder structure for 1.2.1 version of the module:
![image](https://cloud.githubusercontent.com/assets/865473/12859751/9cbe3676-cc58-11e5-9c48-70bf0215dca5.png)

Is there a new way to get access to distribution version of CSS or it's a bug?

**Comment by mikewheaton** [comment]
That's odd, our [release](https://github.com/OfficeDev/Office-UI-Fabric/releases/tag/2.0.0) includes the `dist` folder and this should be what is published to NPM. Any ideas here, @Jahnp?

**Comment by mikewheaton** [comment]
Thanks for bringing this to our attention, @jjczopek. I made a mistake when publishing the NPM package so we're going to have to publish a new version. Stay tuned.

**Comment by mikewheaton** [comment]
Okay, we've published version 2.0.1 as an NPM package. Please re-open this issue if you have any trouble.
