### ISSUE TITLE
Progress Indicator's CSS not in main CSS distro (regression from #281)

### ISSUE THREAD

**Issue by andrewconnell** [OfficeDev/Office-UI-Fabric#325]
Unfortunately looks like a regression from #281 ... the latest release seems to have lost it again...

**Comment by mikewheaton** [comment]
Thanks for catching this, @andrewconnell. Looks like we fixed the issue in our LESS file, but that fix wasn't copied over to the Sass while we still had both.

**Comment by andrewconnell** [comment]
:+1:
