### ISSUE TITLE
Large spinner misplaced

### ISSUE THREAD

**Issue by jjczopek** [OfficeDev/Office-UI-Fabric#328]
There a small issue with spinner positioning. After recent fix regarding label size, there was new variable introduced - `parentSize` used to calculate dot size and offsets.

It looks like that in method `_createCircleAndArrange`, `x` and `y` coordinates have hardcoded 20 at the beggining of the calculation:
https://github.com/OfficeDev/Office-UI-Fabric/blob/master/src/components/Spinner/Spinner.js#L122
https://github.com/OfficeDev/Office-UI-Fabric/blob/master/src/components/Spinner/Spinner.js#L123

It should be:
`var x = Math.round(parentSize * 0.5 + radius * Math.cos(angle) - circle.clientWidth * 0.5) - offset * 0.5;`
rather than:
`var x = Math.round(20 * 0.5 + radius * Math.cos(angle) - circle.clientWidth * 0.5) - offset * 0.5;`

**Comment by mikewheaton** [comment]
Thanks for pointing this out, @jjczopek, we'll get it fixed for the next release.

**Comment by mikewheaton** [comment]
Fixed by #352
