### ISSUE TITLE
ms-Panel-headerText looks terrible when line the wraps

### ISSUE THREAD

**Issue by gavinbarron** [OfficeDev/Office-UI-Fabric#333]
The line height is pretty bad if the header text happens to wrap ![Bad line wrap](http://content.screencast.com/users/gavinbarron/folders/Snagit/media/facba89c-b948-43a8-bde6-8de8f8b4abec/02.04.2016-15.45.png)

**Comment by mikewheaton** [comment]
Thanks for reporting this, @gavinbarron. It's actually a duplicate of #320 so I'll close it, but please keep submitting bugs as you see them.
