### ISSUE TITLE
Remove the 'hero' link variant

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/Office-UI-Fabric#338]
Fabric currently has a regular link and a hero link (second example below). This changes the font weight and padding, but it's unclear when and where it should be used.

![image](https://cloud.githubusercontent.com/assets/1382445/12937506/3767081c-cf5e-11e5-9bfd-071d952b923d.png)

**Comment by tyrasm** [comment]
Seems like we only need the one...

Sent from Outlook Mobile<https://aka.ms/qtex0l>




On Tue, Feb 9, 2016 at 6:53 PM -0800, "Mike Wheaton" <notifications@github.com<mailto:notifications@github.com>> wrote:


Fabric currently has a regular link and a hero link (second example below). This changes the font weight and padding, but it's unclear when and where it should be used.

[image]<https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fcloud.githubusercontent.com%2fassets%2f1382445%2f12937506%2f3767081c-cf5e-11e5-9bfd-071d952b923d.png&data=01%7c01%7ctyrasm%40exchange.microsoft.com%7c2e519edc166140d9424c08d331c549be%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=RICfFblcanoCdOnFplFy7QBLkTWwozACmKE52Rzxoy0%3d>

-

**Comment by mikewheaton** [comment]
Okay, let's remove the hero variant.
