### ISSUE TITLE
Breadcrumb example seems broken.

### ISSUE THREAD

**Issue by dzearing** [OfficeDev/Office-UI-Fabric#340]
I copy/pasted the html and included the css from the breadcrumb component.

The example references ms-Breadcrumb-currentLarge but there is no such style in breadcrumb.scss.

**Comment by wdo3650** [comment]
It also doesn't seem to be behaving correctly. For example the overflow menu isn't showing up.

**Comment by wdo3650** [comment]
@dzearing I think the BreadCrumb component you're looking at is an old version. The new one is in the Github repo. There's no ms-Breadcrumb-currentLarge style in the more recent one. FYI, the Javascript doesn't seem to be included in that sample. I'll file a separate bug for that.

**Comment by dzearing** [comment]
@wdo3650 I'm looking at http://dev.office.com/fabric/components/breadcrumb

Click "html" example. It's busted.

**Comment by mikewheaton** [comment]
Many of the examples on the docs site are outdated and/or broken. We have issues open on this and are working on getting it updated.
