### ISSUE TITLE
Hero button relies on space in HTML

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric#345]
Here is what the primary button looks like when rendered with React:
![image](https://cloud.githubusercontent.com/assets/1382445/12963950/49699ada-d002-11e5-8beb-e07020dea4cf.png)

The lack of space between the plus icon and text is caused by React stripping out spaces between HTML elements. We rely on that single space to push these apart, as both the icon and text are `display: inline-block`. Need to position these in a way that will work with or without a space in the HTML.

**Comment by andrewconnell** [comment]
We have a slightly similar problem in Angular 1.4.9 as well... 

![image](https://cloud.githubusercontent.com/assets/2068657/12964085/2907bbfe-d01c-11e5-9fc7-00995e9aeccb.png)

For a live demo, you can scroll to the bottom of the page to see how it's rendered both as a `<button>` and `<a>`: http://ngofficeuifabric.com/demos/uifButton/

**Comment by mikewheaton** [comment]
After some digging it looks like that's a related but different issue, @andrewconnell. Thanks for reporting it. I'll open a new issue here and submit a PR.
