### ISSUE TITLE
BreadCrumb Behavior Broken

### ISSUE THREAD

**Issue by wdo3650** [OfficeDev/Office-UI-Fabric#348]
The Javascript doesn't seem to be connected to this component in the samples, so none of the behaviors are showing up. For example the context menu is absent.

**Comment by mikewheaton** [comment]
Are you looking at it on our docs site, or http://localhost:2020 with a local build of Fabric running? The docs site is out of date and many of the samples are broken.

**Comment by wdo3650** [comment]
Looking at http://localhost:2020.

**Comment by mikewheaton** [comment]
I'm not familiar enough with this component to know what it's supposed to do, but the overflow menu is opening fine for me. Here's a [GIF showing what I see](http://f.cl.ly/items/1a1L2d47271M1x3Z0N42/Screen%20Recording%202016-02-10%20at%2009.58%20PM.gif).

**Comment by wdo3650** [comment]
Thanks for the illustrating what you're seeing with the gif. That is expected behavior. I nuked and rebuilt Fabric and it seems to be working now for me.
