### ISSUE TITLE
SearchBox redundant X

### ISSUE THREAD

**Issue by smiles2424** [OfficeDev/Office-UI-Fabric#351]
I noticed a potential bug in my recent work with UI Fabric SearchBox. If you go to the [example page](http://dev.office.com/fabric/components/searchbox) in IE 10 or 11 you can see it. 

When you type into the search box, you will see an extra x floating to the left of the expected box. I couldn't inspect on it or find a way to fix this in my solution.
![image](https://cloud.githubusercontent.com/assets/1531591/12983276/396a334a-d0ae-11e5-8a82-b471916c7d8a.png)

Please let me know if this issue already exists, but i couldn't find on a quick scroll through the Searchbox related issues.

This does not happen in Chrome or Firefox. Just IE.

**Comment by mikewheaton** [comment]
Thanks for reporting this, we'll look into it.

**Comment by wdo3650** [comment]
This looks like it's coming from an older version of SearchBox in the docs site which we're working on updating. This issue should be fixed in the latest release in the Fabric repository.

**Comment by smiles2424** [comment]
Do you know the version number that it was fixed in? My requirements need a
local copy of Fabric and I just want to have confirmation that my version
has the bug in it

**Comment by wdo3650** [comment]
Version 1.2.0 should have this fix.
