### ISSUE TITLE
Standard focus colors?

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric#355]
What should the standard outline be for focus states? @dzearing pointed out that we have some inconsistencies here:

![image](https://cloud.githubusercontent.com/assets/1382445/13030401/1d6c2840-d25e-11e5-9a81-6f573458cc82.png)

**Comment by tyrasm** [comment]
+Ben

Sent from Outlook Mobile<https://aka.ms/qtex0l>




On Sat, Feb 13, 2016 at 2:30 PM -0800, "Mike Wheaton" <notifications@github.com<mailto:notifications@github.com>> wrote:


What should the standard outline be for focus states? @dzearing<https://github.com/dzearing> pointed out that we have some inconsistencies here:

[image]<https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fcloud.githubusercontent.com%2fassets%2f1382445%2f13030401%2f1d6c2840-d25e-11e5-9a81-6f573458cc82.png&data=01%7c01%7ctyrasm%40exchange.microsoft.com%7cd8f192cdec824566a76908d334c53643%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=zqmkdXc%2bBIs8qmc6V4z4PYgoefwV9%2btcX50xDjr7RKw%3d>

-

**Comment by tyrasm** [comment]
Yeah, I'm working on this right now. David, Mike and I are on a separate thread.

**Comment by mikewheaton** [comment]
This has been assigned to one of our designers. There won't be a single color for focus borders, as we have to ensure there is contrast with the element that's been focused, but we'll likely get this down to a small set of colors with clear guidance on when to use each.

**Comment by mikewheaton** [comment]
Closing this issue, as #339 covers focus styling throughout Fabric.
