### ISSUE TITLE
Forms sample broken on Safari

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/Office-UI-Fabric#358]
It was [reported in another issue](https://github.com/OfficeDev/Office-UI-Fabric/issues/301#issuecomment-184346264) that the forms sample is not working correctly in Safari.

**Comment by waldekmastykarz** [comment]
Attached is how the sample is displayed in Safari on OS X. Additionally clicking on any of the controls (like date picker or drop-down) doesn't seem to do anything.

![screen shot 2016-02-15 at 20 58 18](https://cloud.githubusercontent.com/assets/11164679/13058956/35ee2632-d427-11e5-9fb1-8b8716c7ae09.png)

**Comment by mikewheaton** [comment]
Well that doesn't look so great. Thanks for reporting this, we'll get it fixed.

**Comment by waldekmastykarz** [comment]
No problem. Please let me know if I can help with anything.

**Comment by ericthompson** [comment]
Thanks, @waldekmastykarz!  I think I know what's happening here - our components aren't updated in the samples :disappointed:

#143 fixed the DatePicker bug... if I remember correctly. We can take a look and see if that's actually issue

`/armchairBugFixing`

**Comment by waldekmastykarz** [comment]
:+1:

**Comment by mikewheaton** [comment]
I'm unable to repro this on the latest pull from 'master', in Safari 9.0.3. Do you recall what steps you took to get it into this error state?

![image](https://cloud.githubusercontent.com/assets/1382445/13384719/3164ce74-de4d-11e5-88a6-b6eac5df8e48.png)

**Comment by waldekmastykarz** [comment]
I haven't done anything special other than trying to run the sample.

**Comment by mikewheaton** [comment]
Is anyone else able to repro this?

**Comment by ericthompson** [comment]
@waldekmastykarz - what version of Fabric are you using?

**Comment by waldekmastykarz** [comment]
@ericthompson it was the version from 23 days ago. I basically cloned the latest version available in the repo.

**Comment by ericthompson** [comment]
Oh no! OK, just checking - I'll try to repro it on some other machines asap.

**Comment by ericthompson** [comment]
Well, I'm on 9.0.3 like @mikewheaton and not able to repro:
![screen shot 2016-03-13 at 10 48 04 pm](https://cloud.githubusercontent.com/assets/1420854/13736041/e9396872-e96d-11e5-9ad9-103578dcf370.png)

Not quite sure what could be happening... might want to try a fresh clone?

**Comment by mikewheaton** [comment]
Let's close this for now, as no one seems to be able to repro it.

**Comment by waldekmastykarz** [comment]
Sorry for late reply. Just tried it and it seems to be working just fine.
