### ISSUE TITLE
Add a slider component

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/Office-UI-Fabric#360]
We don't have a slider component right now. Maybe the design could be based on the toggle?

![image](https://cloud.githubusercontent.com/assets/1382445/13122549/4f082582-d56c-11e5-936e-82617d3213b2.png)

**Comment by Jahnp** [comment]
We definitely need to double-check with design around specific directions, but there are styles we can draw from:

An actual slider In Settings:
![image](https://cloud.githubusercontent.com/assets/307118/13223862/e6efa81c-d93a-11e5-8624-6ecd9ce6b6ff.png)

The scrubber in Movies & TV (though this would be better-suited for a audio/video component):
![image](https://cloud.githubusercontent.com/assets/307118/13224054/a35835d2-d93b-11e5-851f-65a5d777c085.png)

In either case, I think that moving forward, there are reference we can pull from.

**Comment by mikewheaton** [comment]
There are no plans to design or build a slider at this time. I've added it to [the roadmap](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md) as something we hope to provide in the future.
