### ISSUE TITLE
CommandBarItem underlines links

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/Office-UI-Fabric#366]
As pointed out by Paul Schaeflein in [Office UI Fabric - first impressions](http://www.schaeflein.net/office-ui-fabric-first-impressions/), using an `a` element in a CommandBarItem results in the link being underlined:

![image](https://cloud.githubusercontent.com/assets/1382445/13162454/f17ff4dc-d659-11e5-82d8-d37c7bd0900e.png)

We need `text-decoration: none;` here.

**Comment by Fensterbank** [comment]
Could be also added on ListItem component. If you use the list items as links you have the whole text underlined.
