### ISSUE TITLE
PersonaCard actions tightly coupled to class names & order in the HTML

### ISSUE THREAD

**Issue by manndave** [OfficeDev/Office-UI-Fabric#371]
In the current implementation of PersonaCard, the action id ("chat")  must  have a corresponding class in the CSS (".ms-PersonaCard-detailChat") and none of this is obvious to new users.  There's also a bug in the HTML that makes the presentation of the action details dependent upon the order of the HTML.

To reproduce part of the problem, open the index.html sample for the PersonaCard, scroll down to the class with the class "ms-PersonaCard-actionDetailBox" and then below that find the `<li>` with an id of "chat" (it should be the first `<li>`).  Cut that entire `<li>` and then paste it below the "phone" `<li>` so that chat is now second.  Save and reload the page in a browser.  The details shown will no longer match up with the icon selected for the first two items as shown here: 
![personacardactiondetailorder](https://cloud.githubusercontent.com/assets/6853483/13194045/74d9b784-d752-11e5-80f2-cc2d76e768d9.png)

The other part (having to match ids/names) can be reproduced simply by adding a new action and not adding the appropriate IDs and CSS classes.  Perhaps not a bug, per se, but an unnecessary complication.

I'm wrapping up some changes which make the HTML a little easier to follow, breaks the dependency upon names/ids and makes the order of the HTML elements irrelevant to the successful presentation of the action details for the current action.

Let me know if you're interested in a PR.

**Comment by mikewheaton** [comment]
Absolutely, we'd love a PR with your suggestions for making this work better. Please submit it when you have a chance and we'll review. Thanks!

**Comment by manndave** [comment]
OK, will do.  Probably in a few days.

**Comment by mikewheaton** [comment]
The tabs and content are now linked with data attributes, so this component is much more flexible than before.
