### ISSUE TITLE
Update component section of the documentation

### ISSUE THREAD

**Issue by kasajian** [OfficeDev/Office-UI-Fabric#374]
If you look at the components section of the documentation:  http://dev.office.com/fabric/components
you will see that it's missing documentation that still exists on the old site: http://officeuifabric.com/components/

For instance, click on command-bar on both sites:
http://officeuifabric.com/components/command-bar/
and
http://dev.office.com/fabric/components/commandbar

On the old site, you have a Usage section that's quite useful.  Never mind the fact that the old site also allows you to try the code in codepen.

After scouring for more details on this library for the last week I was not able to find any links from the main sites to the old http://officeuifabric.com/components/ .  A google search helped me out.   Furthermore, if you go to http://officeuifabric.com directly, it will redirect you.  So you have to go to http://officeuifabric.com/components/ instead.  Makes me wonder how much longer the old site will be around.

The redirection notice says "In November 2015, Microsoft released their own site with samples and demos for the Office UI Fabric, located at dev.office.com/fabric. When the Microsoft site is up, this site will redirect to the Microsoft site as it doesn't make sense to have two demo sites when one is the real source of truth."

I disagree with the statement that it doesn't make sense.  The new site doesn't have as much information.  Generally the documentation for Office-UI-Fabric and samples are sorely lacking docs so I think the team should try to do what they can to leverage documentation that's already been written.

**Comment by mikewheaton** [comment]
Thanks for bringing this up, our component documentation definitely needs some love. We're working on an update to [our official website](http://dev.office.com/fabric) that will include much more detail on where and how to use each of the components.

I've added this to [our roadmap](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md) for visibility.

**Comment by andrewconnell** [comment]
@kasajian The "old site" is something I built separate from Microsoft... I did it as a community thing. I've since handed the domain over to Microsoft who can change where it points. The site lives in a GitHub repo (https://github.com/ngOfficeUIFabric/officeuifabric.github.io) for another project the community is working on (http://ngofficeuifabric.com).

FWIW, we have no plans to remove the "old site"... you can always get to it even after Microsoft decides to redirect the domain to their site by using the repo link.
