### ISSUE TITLE
No documentation on how to use the components without jquery plugins

### ISSUE THREAD

**Issue by kasajian** [OfficeDev/Office-UI-Fabric#375]
The components delivered by this library are not reliant on any third-party technology, however the main published examples of how to use the components is via the use of the jquery plugins.   This means one must look at the jquery plugin source code to see how to use the actual API, which also means one must understand jquery and how to author plugins.   The same thing with the few Angular directives that are published for this library.

I hope that I'm missing something that my assessment is wrong.   But if it is, I think it would be a really good idea to have very basic reference documentation on how the JavaScript APIs work.

**Comment by mikewheaton** [comment]
One of the top priorities on [our roadmap](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md) is to rewrite all of the components' scripts in TypeScript (compiled down to regular JavaScript for distribution) that will remove dependencies and provide standard patterns for interacting with components.

**Comment by DuNuNuBatman** [comment]
This would be ideal. We are trying to remove the jQuery dependency in all of our applications.

**Comment by kasajian** [comment]
I use TypeScript and I think it's great, and it would be good to do this.  But I think what's really needed is to have very simple javascript (vanilla.js) in the reference documentation so people know how to use it regardless of platform.   Whatever UI framework people use, they all can understand the one common language, which is ES 5 vanilla.js (which isn't that bad).   As the world of front-end frameworks is moving to componentization, each has they're own take on it whether it's jquery, react, angular1, angular2, aurelia, winjs or vue.js, you can have someone from the community provide the wrappers for each of those, while the core framework stays neutral.

Unless I'm misunderstanding something, but I can see using typescript gives you richness in the language, but wiring it up to a particular ui framework is i think an orthogonal concern, IMHO

**Comment by mikewheaton** [comment]
That's a good point. We'll want to be sure that we don't introduce confusion by using TypeScript. We need our output JavaScript to be production quality, but the TypeScript also serves as a form of documentation for those who are writing components for jQuery, React, Angular, or whatever framework comes out tomorrow. If TypeScript confuses those developers, or prevents them from reusing our functions, we're missing an opportunity.

**Comment by andrewconnell** [comment]
IMHO, it’s JS first, then TS.

If you write TS, you can understand JS, but the opposite might not be true. What WOULD be nice is if you do create JS libraries for your components, is if you provide type definitions for them one for each or one for all, just like you added bundles recently.

**Comment by kasajian** [comment]
Yeah, Andrew.  You're right.  That makes sense.
