### ISSUE TITLE
Documentation at Component page is incorrect

### ISSUE THREAD

**Issue by kasajian** [OfficeDev/Office-UI-Fabric#381]
1.
If you go to http://dev.office.com/fabric/components you will see that text there implying that it's just three simple steps to add a component.   First you download the component.  For instance, for SearchBox the link given is https://github.com/OfficeDev/Office-UI-Fabric/tree/master/src/components/SearchBox
Add a reference and that's it.   But if you go to that folder, you will see that it contains a sass file, which you cannot just simply use right off the bat.  The folder is probably pointing to a src folder that needs to be "built" before it can be used.

2.
The documentation seems to imply that you can mix and match components by downloading the source for just what you want; but that's clearly not the case.   However, the full download does have a jquery.fabric.min.js and fabric.components.min.css gives you all the components.  Almost.

3.
If you go to the "Table" component at http://dev.office.com/fabric/components/table you will an example and HTML.  The table is not clickable.   There's no reference to a javascript file.  If you go to the old site, you will see not only that sample, but also one that's clickable: http://officeuifabric.com/components/table/
There's also a JavaScript file there.  Unlike other components, the JavaScript file for the table is *not* included in jquery.fabric.min.js.   You have to include it manually.   It seems like the the dynamic behavior of the Table component never made it to the new site.

My request is to update the site to indicate:
1.  How to include a single component into an existing project (if that's something you intend to support)
2.  Indicate that there's a bundled version that has all the components.

That would be very useful for someone to understand just what bits are needed.

**Comment by mikewheaton** [comment]
Thanks for bringing this to our attention, @kasajian, our documentation site needs updated to better explain how to use a component. Right now it depends on the specific component: some have no JS, others require jQuery, others just a JS file from us.

It's important to note that [http://officeuifabric.com](OfficeUIFabric.com] is *not* the official documentation site for this project, and is not built or maintained by us. What you're seeing there is a jQuery plugin that they've written, separate from this project.

We'll be updating our documentation site to make it clear how to use components generally, and then adding specific notes on the component pages where special instructions are needed.

**Comment by kasajian** [comment]
Thank you Mike.   Do you know how I can go about determining how the table component is supposed to be used from plain javascript?  I want to be able to use the checkbox feature as demonstrated in this pen: http://codepen.io/andrewconnell/pen/RWGgmY

But without jquery.   If there's no documentation at all, what would be the best way to determine the API by looking at the actual source.   Perhaps a few short words from someone on the team on how to do that will get us over the hump and use the library when the documentation is lacking.

**Comment by mikewheaton** [comment]
If you go to the [Table component](http://dev.office.com/fabric/components/table), you can click the HTML tab to see the code for the sample component. In there you'll see `<div class="ms-Table-row is-selected">` – it's that `.is-selected` state class that provides the highlighted background color and puts a checkmark in the box. You just need your JavaScript to toggle this class.

Here's what [Andrew Connell's example](http://codepen.io/andrewconnell/pen/RWGgmY) does:
```
$tableRow.on('click', '.ms-Table-rowCheck', function(event) {
  $(this).parents('.ms-Table-row').toggleClass('is-selected');
});
```

When clicking on a `.ms-Table-rowCheck` element (the checkbox itself) it will add or remove the `.is-selected` state class from the parent, which is an `.ms-Table-row`. Does that help?

**Comment by andrewconnell** [comment]
I don't want to get into pointing fingers here, but I do want to mention that **all** jQuery plugins referenced in the http://OfficeUiFabric.com site & those codepens referenced in were all created from JS I got form the Office UI Fabric downloads in the initial release. I didn't write any of those.

**Comment by andrewconnell** [comment]
@kasajian any chance you are using Angular? The our `<uif-table>` directive implementation of the Office UI Fabric table includes not only selectable rows by also sortable columns:

http://ngofficeuifabric.com/demos/uifTable/

**Comment by kasajian** [comment]
andrew, thank you.   Yes, there's another project we're using angular on and we can use it there.

mike that helps and thank you for telling me how to do that, but i am curious if that's something that I should have been able to figure out on my own somehow..   Am I missing something, or is really the only way to use these components is to look at the source.   I'm honestly scratching my head trying to understand how these components are meant to be used without docs.   I think if the answer really is, "yes, look at the source", then that's fine.   We'll get used to that workflow.

thanks

**Comment by mikewheaton** [comment]
Unfortunately yes, the answer for now is "look at the source". We provide an example for each component that demonstrates the various features, but you do need to examine the source to see which classes are being applied to get the effect.

We're working now on updating the documentation with clear descriptions of the classes available, suggestions for use, etc. Thanks for hanging in there!

**Comment by kasajian** [comment]
Mike, I think that's a reasonable answer, so we'll figure out and get used to that.   It's all part of working in the open.   Thanks for the prompt responses.
