### ISSUE TITLE
How to make list items not take so much space

### ISSUE THREAD

**Issue by kasajian** [OfficeDev/Office-UI-Fabric#383]
I want the user to select multiple items from a list.   I was going to use the table component with check-boxes, but I'm not even sure that's supported anymore, seeing as how the check-box behavior and the jQuery plug-in didn't make its way over to the new documentation.

So I decided to use the the list component itself, which has checkbox features.

If I use the standard list component, by default I get something like this:
http://codepen.io/andrewconnell/pen/yYaMpb

```html
<div style="width:400px">
  <div class="ms-ListItem is-selectable">
    <div class="ms-ListItem-selectionTarget js-toggleSelection"></div>
    <span class="ms-ListItem-primaryText">Satya Nadella</span>
    <span class="ms-ListItem-secondaryText">Office UI Fabric Rocks!</span>
    <span class="ms-ListItem-tertiaryText">Congrats on a fantastic release helping developers build apps that look like Office!</span>
    <span class="ms-ListItem-metaText">10:15a</span>
    <div class="ms-ListItem-actions">
      <div class="ms-ListItem-action"><i class="ms-Icon ms-Icon--attachment"></i></div>
      <div class="ms-ListItem-action"><i class="ms-Icon ms-Icon--x"></i></div>
      <div class="ms-ListItem-action"><i class="ms-Icon ms-Icon--flag"></i></div>
    </div>
  </div>
</div>
<br />
<div style="width:400px">
  <div class="ms-ListItem is-selectable is-selected">
    <div class="ms-ListItem-selectionTarget js-toggleSelection"></div>
    <span class="ms-ListItem-primaryText">Satya Nadella</span>
    <span class="ms-ListItem-secondaryText">Office UI Fabric Rocks!</span>
    <span class="ms-ListItem-tertiaryText">Congrats on a fantastic release helping developers build apps that look like Office!</span>
    <span class="ms-ListItem-metaText">10:15a</span>
    <div class="ms-ListItem-actions">
      <div class="ms-ListItem-action"><i class="ms-Icon ms-Icon--attachment"></i></div>
      <div class="ms-ListItem-action"><i class="ms-Icon ms-Icon--x"></i></div>
      <div class="ms-ListItem-action"><i class="ms-Icon ms-Icon--flag"></i></div>
    </div>
  </div>
</div>
```

![image](https://cloud.githubusercontent.com/assets/2384797/13291690/8d0e661e-dacd-11e5-950b-2690ef642d26.png)

Now, clearly, each line is too big.  I just want one line per row.   So I remove all but the primary text, including the &lt;br /&gt;, and get this:

```html
<div style="width:400px">
  <div class="ms-ListItem is-selectable">
    <div class="ms-ListItem-selectionTarget js-toggleSelection"></div>
    <span class="ms-ListItem-primaryText">Satya Nadella</span>
  </div>
</div>
<br />
<div style="width:400px">
  <div class="ms-ListItem is-selectable">
    <div class="ms-ListItem-selectionTarget js-toggleSelection"></div>
    <span class="ms-ListItem-primaryText">Satya Nadella</span>
  </div>
</div>
```
![image](https://cloud.githubusercontent.com/assets/2384797/13291896/747e2e26-dace-11e5-9385-66b1eacb6b47.png)

There's just too much space between those.  After a few hours of staring at CSS, I came up with one way to solve it:

```html
<style>
.ms-ListItem.is-selectable:before,
.ms-ListItem.is-selectable:hover:before {
  top: 4px;
}
</style>

<div style="width:400px">
  <div class="ms-ListItem is-selectable"  style="padding-top:0px">
    <div class="ms-ListItem-selectionTarget js-toggleSelection"   style="top: 4px"></div>
    <span class="ms-ListItem-primaryText">Satya Nadella</span>
  </div>
</div>
<div style="width:400px">
  <div class="ms-ListItem is-selectable"  style="padding-top:0px">
    <div class="ms-ListItem-selectionTarget js-toggleSelection"   style="top: 4px"></div>
    <span class="ms-ListItem-primaryText">Satya Nadella</span>
  </div>
</div>
```
![image](https://cloud.githubusercontent.com/assets/2384797/13291969/bcb90fb2-dace-11e5-8387-5bb3bb1d564a.png)

The biggest issue is aligning the checkbox location, where you click on the checkbox with the text element.
That seems like an amazing amount of effort for me to have to have to figure out and rather hackish to do something so basic as decreasing the row height of a list-view.   I'm thinking I'm may be making things more complicated.  **Is there a more proper way to do this?**

I was playing around with Angular Material, and they're stuff isn't much easier to figure out.   To get them to make the line-height smaller I had to do something like this:

```html
<style>
md-list-item, md-list-item .md-list-item-inner, md-checkbox {
    min-height: 100%;
}
</style>

<md-list ng-controller="ListCtrl" ng-cloak="" class="listdemoListControls" ng-app="MyApp">
  <md-list-item ng-repeat="message in messages">
      <md-checkbox class="green" ng-model="message.selected">
    </md-checkbox> 
       <p style="" >{{message.title}}</p> 
  </md-list-item>
</md-list>
```

http://codepen.io/kasajian/pen/JXPPVw

**Comment by mikewheaton** [comment]
ListItems are tricky because there are so many potential use cases. Our current ListItem is modeled after the Outlook mail list, so it has a whole bunch of elements that you may not be using. It's hard to know what to suggest without seeing the specific app you're working on, but some options could be:

1. Override the existing `.ms-ListItem` like you're doing here. It's a pain but there's nothing wrong with what you're doing to make the component work for you.
2. Use the `.ms-Table` component. We don't provide JavaScript for it, but to select a row you just need to add the `.is-selected` class, as I described in the [other issue](https://github.com/OfficeDev/Office-UI-Fabric/issues/381#issuecomment-188447621) you opened.
3. Use a [ChoiceField component](http://dev.office.com/fabric/components/choicefield) to create the checkbox.
