### ISSUE TITLE
NavBar: more than one right aligned items

### ISSUE THREAD

**Issue by cut2run** [OfficeDev/Office-UI-Fabric#385]
Documentation on NavBar component doesn't indicate that you cannot have more than one NavBar item aligned to right. When using class "ms-NavBar-item--right" on more than one item  ...
1. they will not have spacing between them as the class has the style "margin:0"
2. the items will have opposite order than in HTML list or narrow version as the same class uses style "float:right"
The documentation on the control has to indicate this fact that you support only one right aligned NavBar item or better this should be fixed as I am not probably along who wants to align two items to the right. For now I just use one right aligned item with contextual menu of two context menu item, which is work around, but overkill for me indeed, despite inconvenience for user.
Thanks

**Comment by mikewheaton** [comment]
Thanks for bringing this up, I'm quite sure the NavBar should support having multiple commands on the right hand side.

Here is a quick example of how to write your own CSS override to support having a second item: [NavBar with Multiple Items on Right](http://codepen.io/mikewheaton/pen/QNLbKj)

You could also consider using a CommandBar, which is much the same component (we're likely going to remove one in the future) and supports this: [CommandBar with Multiple Items on Right](http://codepen.io/mikewheaton/pen/zqOGGz)

**Comment by cut2run** [comment]
Thank you, I'll have a look.
