### ISSUE TITLE
CommandBar first item of CommandBar-mainArea become hidden

### ISSUE THREAD

**Issue by cut2run** [OfficeDev/Office-UI-Fabric#388]
NavBar was replaced with CommandBar as per your suggestion: [https://github.com/OfficeDev/Office-UI-Fabric/issues/385](https://github.com/OfficeDev/Office-UI-Fabric/issues/385)
It does looks more robust than NavBar, but still has an issues I would like to bring up.

1. I know my commands are not going to overflow. So I have removed   section completely. This will lead to incorrect processing of Commands inside 'Jquery.CommandBar.js'. The function "processCommands" uses "overflowwidth" parameter directly without any check. When HTML node removed the value will be "undefined" and you add this directly to "rightOffset". You probably should have something like this before use of the parameter ...
`if (typeof overflowwidth === "undefined") {
	overflowwidth = 0;
}`
I work around this issue by keeping the HTML tag.

2. I don't need  entire "ms-CommandBarSearch" item and I have removed it. The content of "ms-CommandBar-mainArea" has "padding-left:58px" and command bar icons starts from this position. When I override "padding-left:8px" (8px is the padding-right for "ms-CommandBar-sideCommands") first item in the "ms-CommandBar-mainArea" disappear. How is it happen ...
`    // my parameters as follow: (commands, 8, 0)
    // rightOffset will be calculated to 10
       
    var processCommands = function(commands, width, overflowwidth) {
        var overFlowCommands = [];

        for(var i=0; i < commands.length; i++) {
          var $Item = commands[i].jquery;
          var rightOffset = commands[i].rightOffset;
          
          // If the command is outside the right boundaries add to overflow items
          if(!$Item.hasClass('ms-CommandBarItem-overflow')) {

// my condition will not evaluate properly: (10 + 0) > 8 !!! Item become hidden

            if((rightOffset + overflowwidth) > width) {
              overFlowCommands.push($Item);
            } else {
              // Make sure item is displayed
              $Item.removeClass('is-hidden');
            }
          }
        }
        return overFlowCommands;
    }
`
I am working with narrow interface, only icons are displayed.The item gets "is-hidden" class at the first load. After refresh calculation work correctly and icon appear.
I worked around this issue by setting "padding-left:11px" for "ms-CommandBar-mainArea"

**Comment by mikewheaton** [comment]
The issue with removing the search box and having too much padding is being tracked in #363. I've also added a note there describing your issue with the first command disappearing after you change the padding.

Right now the CommandBar assumes that you'll have the overflow area for commands that don't fit. Even if you aren't expecting to need this, does it cause problems to leave it in? We could make that behavior optional but just need to understand the use case for doing so.

**Comment by cut2run** [comment]
There is no problem to keep it in. In fact as my work around I left the top level node in place as follow ...
`                    
                    <div class="ms-CommandBarItem ms-CommandBarItem--iconOnly ms-CommandBarItem-overflow">
                    </div>
                    
`
This gives me input parameter overflowwidth set to 0.
As far as I see the points of making change as follow ...
1. If I don't want to have overflow I should be able to delete the section completely. why would I leave the part of the HTML section in place? Just to make variable equal to zero? You may have this assumption in the control itself and set overflow to 0 when entire section doesn't exist.
2. If I leave it in place I would probably want to leave it completely, as the part of the control, not just top node as I did. In this case I have to implement "ms-ContextualMenu", set "ms-CommandBarItem-commandText" (I have localization and have to set every single line via code). Why would I want to do all this work to make the section complete?
3. The last point  ... as the general rule for development if I have something in my HTML I have to take care of it, not relay this part will never shows up. Otherwise I should remove it completely.

I hope this is confirm there is certain use case for this simple control change. Otherwise there is work around anyway.
Thank you for your attention, Mike.

**Comment by mikewheaton** [comment]
The main remaining issue here seems to be the overflow menu, and wanting to remove it if there are few items in the CommandBar. With the new CommandBar updates the overflow menu *only appears when the items do not fit*. So you will no longer have to manually add/remove the overflow menu. 😄
