### ISSUE TITLE
Remove content-specific classes from PersonaCard

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/Office-UI-Fabric#389]
The PersonaCard includes a bunch of classes that are specific to the sample, such as `.ms-Persona-detailPhone`. We'll verify this with the designers, but I don't think the PersonaCard requires those tabs in that specific order – it should be able to accept custom tabs.

![image](https://cloud.githubusercontent.com/assets/1382445/13332379/84bff20e-dbb6-11e5-87f2-b578a42484aa.png)

![image](https://cloud.githubusercontent.com/assets/1382445/13332417/bd49be02-dbb6-11e5-8fab-5b4a23dc44d1.png)

**Comment by mikewheaton** [comment]
It turns out that the design intent is for a PersonaCard to have only those 4 actions. You can have fewer (e.g. if phone numbers aren't available) but nothing different. So we won't be updating the component at this time to make it easier to customize. Instead, we'll document this more clearly.

**Comment by andrewconnell** [comment]
Posted this elsewhere, but putting it here for transparency… this is disappointing.

IMHO that seems very self serving for Office… what about if I was building a CRM system and wanted to use an icon to log a note on their account, or a currency symbol to see the status of their account balance & invoices or `ms-icon—bookmark` or `ms-icon—star` to follow them.

Even if those 4 specific actions are what it’s intended for, you ​know people will simply use other icons to solve their business problem.

**Comment by manndave** [comment]
Hmmm.. I handle this exact scenario (other tabs and icons) in the PR I submitted a few days ago, but also some other enhancements and bug fixes (like the markup and CSS only working if the tabs and action icons are in the correct order.)

Based on the above, I guess my PR won't be accepted.  What changes do you need me to make to make it acceptable?

**Comment by mikewheaton** [comment]
We need to discuss this some more, as there are multiple goals conflicting here and we need to figure out where to draw the line between advising and enforcing. Please leave your pull request as it is for now. Thanks for your patience.

**Comment by manndave** [comment]
Roger.  ([huh?](https://www.youtube.com/watch?v=2OBZf0QdKdE))

**Comment by mikewheaton** [comment]
Thanks as always for your candid feedback. We discussed this again today and realized that while we want to encourage you to follow our guidelines, it's going too far to put up roadblocks that keep you from customizing Fabric.

We're going to review @manndave's pull request (https://github.com/OfficeDev/Office-UI-Fabric/pull/377) and get this into the next version of Fabric. If you see any other places where our components are difficult to modify please let us know.

**Comment by andrewconnell** [comment]
:+1:

**Comment by mikewheaton** [comment]
Closing this. It's a duplicate of #371, for which we now have a pull request in review.
