### ISSUE TITLE
CommandBar links only work when already focused

### ISSUE THREAD

**Issue by Fensterbank** [OfficeDev/Office-UI-Fabric#396]
When you use CommandBar items as links with href, I saw the behavior that the link is selected on the first click, the second click triggers the navigation.

I don't know, if it's really an issue because the CommandBar is not designed to contain classic navigation links, but if you do, this behavior seems really strange.

This behavior was fixed after removing the .ms-CommandBarItem-link:focus styles.

**Comment by mikewheaton** [comment]
The CommandBar should generally contain commands that act on the currently-selected item, whereas the NavBar is best for links that navigate away from the current page. Still, it seems reasonable that some commands might require changing the page and that the CommandBar should support this. We'll investigate it.

**Comment by mikewheaton** [comment]
Fixed by PR #615. CommandButton can be a link and it will navigate immediately when clicked.
