### ISSUE TITLE
Strange NavBar behaviour with the is-selected class

### ISSUE THREAD

**Issue by Fensterbank** [OfficeDev/Office-UI-Fabric#397]
When clicking on a NavBar link, the item gets the `is-selected` class.
Also it seems like the class is designed to be added always to the current page items.
But the class is always removed when clicking somewhere else on the page.

So in fact the link becomes bold when you click on it, (then maybe a navigation event happens and a new site is displayed where the current item is underlined) and then class is removed when clicking somewhere. This seems wrong and "flashy".

**My Suggestions:**
- Remove the `.removeClass('is-selected')` in following line https://github.com/OfficeDev/Office-UI-Fabric/blob/master/src/components/NavBar/Jquery.NavBar.js#L86 to just let the class be there

**OR** (I would prefer)
- Don't do anything with the `is-selected` class. Normally it's not the job of a navbar to take care to add or remove "current page indicators" to the links contained in the navbar.  
Also in most use cases a current page indicator in a menu is added **after** the navigation happens not during click.  
Setting a current page indicator in JavaScript makes only sense if you have a single page application without url change, but the NavBar component is designed to contain links with "real navigation" events.

**Comment by mikewheaton** [comment]
We're setting the `is-selected` class here to demonstrate how the component works. You're right that we should clearly separate this out, making it clear what JS is required by the component and what is for demonstration.

**Comment by mikewheaton** [comment]
Fixed by PR #615. We've separated out demonstrational JavaScript from the JavaScript intended for production use.
