### ISSUE TITLE
Multiple NavBar items on right have incorrect spacing

### ISSUE THREAD

**Issue by emiliogg84** [OfficeDev/Office-UI-Fabric#398]
When there is more than one right-aligned element, and these elements contain text, the space between the elements is not respected.

I solve the problem changing the css and adding padding-right:18px; to .ms-NavBar-item--right

**Comment by mikewheaton** [comment]
Fixed by PR #615.

![image](https://cloud.githubusercontent.com/assets/1382445/15729655/14609e30-281b-11e6-81ed-3c7350a75217.png)
