### ISSUE TITLE
Link element in NavBar link is smaller than hovered list item area

### ISSUE THREAD

**Issue by Fensterbank** [OfficeDev/Office-UI-Fabric#403]
The link element in a navbar link list item is smaller than the outer `<li>` item, which has an hover effect.

![navbar](https://cloud.githubusercontent.com/assets/1684826/13439128/686e442c-dfec-11e5-966f-838efb1f3e83.png)

This results in the bug the menu item itself is hovered, but nothing happens on click if you don't hit the inner link element.

I think this could be fixed by removing the line-height of `.ms-NavBar-item` and make the .ms-NavBar-link a inline-block element with a height of 29px and a top padding of 10.5px.
10.5px seems to result in exact the same look, but because float values in pixel units are evil we could use 0.7em or any better idea. :smirk:

```
.ms-NavBar-link {
    padding-top: 10.5px;
    display: inline-block;
    height: 29px;
}

.ms-NavBar-item {
    line-height: initial;
}
```

**Comment by mikewheaton** [comment]
Fixed by PR #615. The CommandButton we're using now is full height.
