### ISSUE TITLE
SplitView (MainMenu)

### ISSUE THREAD

**Issue by sondreb** [OfficeDev/Office-UI-Fabric#405]
Are there plans to develop a SplitView (main menu/hamburger menu) that is similar to WinJS and the new one used on the Office 365 portal?

**Comment by mikewheaton** [comment]
We'll bring this up with the design team to see if it's a standard pattern we'd like to provide in Fabric.

**Comment by mikewheaton** [comment]
While we have similar navigation in our Windows UWP and Android apps, this isn't a pattern we're currently using on the web. So unfortunately at this time there are no plans to develop this for Fabric.

**Comment by sondreb** [comment]
Not sure if you understood, the right-side main menu is called SplitView on WinJS. It's the black bar menu that is visible in the screenshot from Office 365 portal below:

![image](https://cloud.githubusercontent.com/assets/309938/13489036/e1288f88-e124-11e5-9d62-a80751635192.png)

A similar menu is available in WinJS, but it does not have features such as pin to keep open and the flyout on hover and expander for more options.

If it's not in the plans, it's not in the plans, but I just want to confirm that there was no misunderstanding. If it won't be implemented, we'll just make our own :-)

**Comment by mikewheaton** [comment]
Well then, it turns out Office 365 is using this on the web. I'll leave this issue open for now so that I can mention it to the designers, as this pattern might be useful in Fabric. But I wouldn't count on it being added any time soon. Let us know if you do build your own.

**Comment by mikewheaton** [comment]
I've added this request to [our roadmap](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md) as a potential component to include in a future release.
