### ISSUE TITLE
AppPicker

### ISSUE THREAD

**Issue by sondreb** [OfficeDev/Office-UI-Fabric#406]
Are there any plans to implement an AppPicker similar to Office 365 portal? The latest release have great features for pinning, resizing, etc.

![AppPicker](https://i-msdn.sec.s-msft.com/office/office365/HowTo/images/Office365_AppLauncher_Launcher.png)

**Comment by mikewheaton** [comment]
This was requested previously (see #81) and is on [our roadmap](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md) as a component we'd like to provide in the future.
