### ISSUE TITLE
AppChrome

### ISSUE THREAD

**Issue by sondreb** [OfficeDev/Office-UI-Fabric#407]
Are there plans to implement something similar to AppChrome in this framework? This should probably also have the new pinned shortcuts support which is available on Office 365 portal.

https://msdn.microsoft.com/en-us/office/office365/howto/javascript-controls

Image from URL above:
![Screenshot](https://i-msdn.sec.s-msft.com/office/office365/HowTo/images/Office365_JavaScriptControl_AppChrome_2.png)

**Comment by mikewheaton** [comment]
We'll check with the design team to see if this is a standard component we'll provide.

**Comment by mikewheaton** [comment]
This is on [our roadmap](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md) as a potential component to include in a future release.
