### ISSUE TITLE
Facepile CSS not included in fabric.css 2.1.0

### ISSUE THREAD

**Issue by manndave** [OfficeDev/Office-UI-Fabric#411]
The classes for the Facepile **component** (i.e not the facepile variant of PeoplePicker) are not included in the bundled fabric.css file in the 2.1.0 release on the CDN or in the output of a forked build.  Looks to be a Build problem?

**Comment by manndave** [comment]
Looks like they weren't included in 2.0.1 either.  Specifically, this is any selector beginning with ".ms-Facepile"

**Comment by Jahnp** [comment]
Great catch--thanks for calling this out! Looks like it didn't get added to Fabric.Components.scss. We have a fix for this in #412 right now, and it'll definitely be included in the next release.

**Comment by mikewheaton** [comment]
Fixed by #412.
