### ISSUE TITLE
Question: Is CommandBar supposed to have an associated Contextual Menu?

### ISSUE THREAD

**Issue by manndave** [OfficeDev/Office-UI-Fabric#420]
Maybe I'm just missing something...but CommandBar doesn't seem to _do anything_ - it just looks nice.  With NavBar, you can add a Context Menu simply by adding the `<ul class="ms-ContextualMenu">` and some `li` but this doesn't work for CommandBar.  To get the ContextMenu you need to add some HTML and some CSS.  Not a big deal, just wondering if there is guidance or plans to add some functionality.  If the latter, I can work on a PR if someone clarifies how things should work.

Thanks.

**Comment by mikewheaton** [comment]
I would think the CommandBar should open a ContextualMenu in the same way that the NavBar does. I'll flag this as 'needs-design' so that we can verify.

**Comment by fabianhussl** [comment]
I agree with @manndave - the is no such trigger-class like `ms-NavBar-item--hasMenu` for the CommandBar. This is a pity. I would like to build something like the sort-menu in OneDrive. Please verify if there is a workaround or a solution for this issue.

Thanks

**Comment by mikewheaton** [comment]
Fixed by PR #615. The CommandBar now opens a ContextualMenu as expected, making it much more functional:

![image](https://cloud.githubusercontent.com/assets/1382445/15767397/6d627d96-28fc-11e6-9ffc-541ebd443100.png)

**Comment by asith-w** [comment]
Horizontal scroll bar is appeared when command item is positioned in right corner of page.
![cmd](https://cloud.githubusercontent.com/assets/5784846/17166005/ee871966-53f1-11e6-91e7-6d2e58cf9bf8.png)
