### ISSUE TITLE
CommandBar Searchbox windows width

### ISSUE THREAD

**Issue by 12seconds** [OfficeDev/Office-UI-Fabric#422]
If page is loaded say at 850px width, searchbar on click event does not fire until you resize your window < 640 which fires the event window.resize function and then the click event listener is registered to the searchbar button. 
Is there any reason to have this width initial check?

```
      // Set Search Behavior
      if($(window).width() < 640) { 

        $('.ms-CommandBarSearch-iconSearchWrapper').click(function() {
          $(this).closest('.ms-CommandBarSearch').addClass('is-active');
        });

      }
```

**Comment by mikewheaton** [comment]
Fixed by PR #615. The CommandBar's search bar now functions correctly across screen sizes.
