### ISSUE TITLE
Actions on PersonaCard in FacePile do not work

### ISSUE THREAD

**Issue by manndave** [OfficeDev/office-ui-fabric#426]
When the embedded template PersonaCard is shown for a person in the FacePile, clicking the action icons (phone, chat, mail, etc) does not do anything.  A quick test indicates that you just need to include the `PersonaCard` function and a call to `$('.ms-PersonaCard').PersonaCard();` but this should probably be included in the sample or at least mentioned somewhere.

**Comment by mikewheaton** [comment]
Good point, if a component contains another we should make sure everything is working in the demo/sample.

**Comment by Jahnp** [comment]
This has been fixed for 3.0.
