### ISSUE TITLE
please consider pagination element:

### ISSUE THREAD

**Issue by kennywangjin** [OfficeDev/Office-UI-Fabric#437]
Please consider implementation of pagination control. It's really useful for many table-base web applications. Or add an optional pager component to table component.

**Comment by mikewheaton** [comment]
We've had many requests for this and have placed it in the planned work section of [our roadmap](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md). Designs are complete and we just need to get it built, thanks for your patience here.
