### ISSUE TITLE
Update docs to use HTTPS for CDN

### ISSUE THREAD

**Issue by iambmelt** [OfficeDev/Office-UI-Fabric#444]
Per screenshot below
<img width="1004" alt="screen shot 2016-03-18 at 2 08 12 pm" src="https://cloud.githubusercontent.com/assets/990063/13892188/e4f74fec-ed12-11e5-868d-c966cc729a94.png">

We should encourage developers to use the HTTPS hosted files by default. If developers plan to use Office Fabric in their Add-Ins they'll have to so as to avoid mixed content blocking.

**Comment by mikewheaton** [comment]
Excellent point. There are no issues (that I'm aware of anyway) with requesting HTTPS resources on HTTP-served pages, so it would be best practice to link to the HTTPS version. I've confirmed that appsforoffice.com supports HTTPS, so we just need to update the docs.

**Comment by iambmelt** [comment]
Thanks for the update @mikewheaton :+1:

**Comment by mikewheaton** [comment]
I've made this change and am working on getting it merged into the documentation site. Will leave this issue open until we've deployed the site with the updated URLs.

**Comment by zkoehne** [comment]
Usually, the protocol is not included for CDN references. It would look something like `//cdn.example.com/resource/fabric.css`. That way, the link can inherit the protocol from the server whether it's server HTTP or HTTPS. HTTPS on an HTTP site might show a "mixed content" warning to the user when the page loads. That said, you would run into issues when [running locally](http://stackoverflow.com/questions/15795080/jquery-cdn-is-not-loading-on-localhost?lq=1).

**Comment by notandrew** [comment]
:+1:

**Comment by mikewheaton** [comment]
I actually did look at using protocol-relative URLs (e.g. `//cdn.com/fabric.css`) but after some research it seems that this is no longer the recommended approach. See the note at the top of this [article from Paul Irish](http://www.paulirish.com/2010/the-protocol-relative-url/).

**Comment by zkoehne** [comment]
Interesting. Everyone should be using HTTPS now anyways. :)

**Comment by mikewheaton** [comment]
We've made this change to the documentation site and it will included in the next deployment.
