### ISSUE TITLE
search button in NavBar does not work as desired

### ISSUE THREAD

**Issue by Brian-Ding** [OfficeDev/Office-UI-Fabric#445]
there is no forum for the fabric, so i am gonna put the question here, sorry if i ask at a wrong place

i followed the example of navbar from here: http://dev.office.com/fabric/components/navbar

but when i click the search button, no input area shows up, and i cant open the navbar in mobile mode

any ideas? all help are appreaciated

![image](https://cloud.githubusercontent.com/assets/11363173/13897031/d7604d6e-eddc-11e5-9ccd-32d7a09359bb.png)

![image](https://cloud.githubusercontent.com/assets/11363173/13897033/ede56934-eddc-11e5-9d56-f59511278ae4.png)

**Comment by av-virlan** [comment]
Based on the snippet above it seems you're missing the initialization of the NavBar. Just add this piece of code to your page

```javascript
$(document).ready(function(){
	$(".ms-NavBar").NavBar();
});
```

This should fix both the hamburger menu in mobile not showing the menu & the search not switching to input mode

**Comment by Brian-Ding** [comment]
that works, thank you for the help!!

**Comment by andrewconnell** [comment]
Actually there is a forum… OfficeDev has a Slack team with a dedicated channel on fabric. See https://github.com/OfficeDev/Office-UI-Fabric/pull/342

**Comment by Brian-Ding** [comment]
thx for that info
