### ISSUE TITLE
Pivot: Missing functionality from component

### ISSUE THREAD

**Issue by av-virlan** [OfficeDev/Office-UI-Fabric#446]
Currently pivots are able to switch styles between the pivot-links but do not hide/show any content. The way I see it Pivots should act like Bootstrap tabs and allow to to link them to some elements on the page that should be visible/hidden depending on what pivot you select.

I have an implementation in place - see [commit](https://github.com/av-virlan/Office-UI-Fabric/commit/cf2f38d6cbe4972834861af7f1db6da5582829c2) - and will prepare a pull-request if you think this is something that should be included.

**Comment by mikewheaton** [comment]
The Pivot component now includes content areas that are shown/hidden based on the selected item:

![image](https://cloud.githubusercontent.com/assets/1382445/15797928/606d9bbc-29dc-11e6-8b80-b61533a5047d.png)
