### ISSUE TITLE
Dropdown component does not update with ajax data

### ISSUE THREAD

**Issue by twaddell** [OfficeDev/Office-UI-Fabric#451]
I am trying to add items to the dropdown component using ajax. However when I update the contents of the `select` the dropdown does not update.
I have also tried executing `$('.ms-Dropdown').Dropdown();` after the update but this does not work either.

I have set up a jsfiddle example here: https://jsfiddle.net/9e6z91bz
Javascript lines 1-158 = jquery.Dropdown.js
lines 159 - 187 = ajax data loading

**Comment by mikewheaton** [comment]
This is a known issue (#159). A [potential solution](https://github.com/OfficeDev/Office-UI-Fabric/issues/159#issuecomment-179283391) was posted in the original issue, could you please give it a try?

**Comment by twaddell** [comment]
Sorry for not spotting the original issue.  The suggested solution worked well, thank you.

**Comment by mikewheaton** [comment]
No worries, we've got a long list of issues to sort through. Let us know if there's anything else we can help with.
