### ISSUE TITLE
NavBar disabled items should not respond to click

### ISSUE THREAD

**Issue by Elfayer** [OfficeDev/Office-UI-Fabric#452]
When we click on a disabled item on the NavBar, it is showing a blue color on the text. I think this behavior is confusing and should not show visible response to user click.

![image](https://cloud.githubusercontent.com/assets/15869149/13959237/b80ccaa4-f053-11e5-94aa-5c6fe8670a63.png)

**Comment by s-KaiNet** [comment]
just my 50 cents:   
color for disabled item seems to be not correct: 

![2016-03-22_2223](https://cloud.githubusercontent.com/assets/10658276/13964880/fb8dfea0-f07c-11e5-9739-0859b49eb7e4.png)

should be `#a6a6a6` but overrided by `.ms-NavBar-link` style

**Comment by mikewheaton** [comment]
Fixed by PR #615. The NavBar is being combined with the CommandBar, which has a proper state for disabled items.
