### ISSUE TITLE
Can this be used for SharePoint 2013 on premises ?

### ISSUE THREAD

**Issue by NandaCodeBox** [OfficeDev/Office-UI-Fabric#455]
Can this be used for SharePoint 2013 On-premises ?

**Comment by mikewheaton** [comment]
Please see the [license](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/LICENSE) and [Eric's comment](https://github.com/OfficeDev/Office-UI-Fabric/issues/341#issuecomment-194082728) that goes into more detail. I'm not a lawyer so please read the license for yourself, but my understanding is that Fabric is licensed to 'extend the Office experience' and that this would include on-premises SharePoint.

**Comment by NandaCodeBox** [comment]
Thank you
