### ISSUE TITLE
All CallOut's are the height of the browser window

### ISSUE THREAD

**Issue by EdMarsden** [OfficeDev/Office-UI-Fabric#459]
Tried for a while to get the CallOut to behave like the sample, and can't.
It appears that the way the CSS is declared each CallOut will expand to 100% the height of their host window.
Appears to come from the height attribute in: .ms-Callout-inner{height:100%;...}
![callout_cssnotoverridden](https://cloud.githubusercontent.com/assets/17994264/14037843/f89b8232-f21e-11e5-9064-21161faa31f8.png)

If I override this with .ms-Callout-inner{height:auto;} the CallOut appears to behave as expected.
![callout_cssisoverridden](https://cloud.githubusercontent.com/assets/17994264/14037852/0312ce46-f21f-11e5-9682-a55bd530ac02.png)

Am I missing something? Is there supposed to be a parent element that restricts the height of the CallOut? Or is this a bug?

**Comment by manndave** [comment]
Make sure your doctype is correct:  <!doctype html>

**Comment by mikewheaton** [comment]
Make sure that `.ms-Callout-inner` is wrapped within the main `.ms-Callout` container. Here is a [demo on Plunker](http://plnkr.co/edit/R3IyRd?p=preview) showing a Callout in use.

**Comment by EdMarsden** [comment]
Thanks all.
The example code I was using came straight from the Office Dev Center, so the structure was good.
Ensuring the <!doctype html> tag was present fixed the issue. ;)

**Comment by mikewheaton** [comment]
I never would've guessed it was the doctype causing this. Thanks, @manndave!
