### ISSUE TITLE
Documentation: remove periods from classes for easier copy-paste

### ISSUE THREAD

**Issue by Caseyyu2** [OfficeDev/Office-UI-Fabric#463]
It's troublesome to copy paste into my project, but need to remove the doc every single time. :) Can you please remove it?

**Comment by mikewheaton** [comment]
We're including the dot (e.g. `.ms-font-su`) throughout our documentation. I guess the idea was to communicate that these are classes, but we refer to them as classes constantly and they all start with `ms-` so that should be clear. Removing the dot would make copy-pasting easier and reduce noise.

**Comment by mikewheaton** [comment]
This has been fixed in our documentation repo and will be included in the next deployment. 😄
