### ISSUE TITLE
Using NavBar inside Office add-in task pane

### ISSUE THREAD

**Issue by dougperkes** [OfficeDev/Office-UI-Fabric#465]
I there any markup I can apply to a NavBar to prevent it from switching into the mobile view? I am trying to use a NavBar inside of a Word add-in, why by default gives me 320px width to work with. Even with a single item in the nav bar with only an icon, the NavBar always collapses into the mobile view with just the ms-Icon--menu showing. Ideally, I'd like to have a set of icons sitting in the NavBar that the user can click on to quickly move to different sections of the add-in. I've looked through the docs and samples and can't find anything that would indicate how to control the min width before the NavBar collapses.

**Comment by mikewheaton** [comment]
Unfortunately no, right now the NavBar has a hard-coded responsive style that shows the hamburger menu on small screens and opens the menu in a Panel.

Have you considered using a CommandBar? The style is slightly different, but it does support showing icons on small screens (no hamburger menu).
