### ISSUE TITLE
Panel: CommandBar hides at very narrow widths

### ISSUE THREAD

**Issue by elegault** [OfficeDev/Office-UI-Fabric#466]
The default of 400px for the media variable seems way too small.  I have to bump it to over 1000 so it doesn't get hidden. It disappears quickly with vertical task panes if you resize it just a little larger than the default.  I need to review this further but I just wanted to get this issue logged for now.

@media (min-width: 400px) {
  .ms-Panel-main .ms-CommandBar {
    display: none;
  }

**Comment by mikewheaton** [comment]
We'll have a designer take a look at this. It does seem odd to hide the CommandBar entirely – there's no reason to think those commands suddenly become unnecessary on small screens.

**Comment by mikewheaton** [comment]
Fixed by PR #615. The CommandBar inside a Panel is no longer hidden on small screens.
