### ISSUE TITLE
NavBar: selected items not closing

### ISSUE THREAD

**Issue by brannmar** [OfficeDev/Office-UI-Fabric#479]
Version 2.2.0

When having multiple dropdowns in the navbar only the first one is deselected when selecting an other menu item. 

The problem seems to be at row 49 in the javascript file. Jquery.NavBar.js
`$(this).siblings('.ms-NavBar-item--hasMenu').children('.ms-ContextualMenu:first').removeClass('is-open');`

It works great up until the `.children('.ms-ContextualMenu:first')`

We tried removing the `:first` selector and it worked. The code on row 49 only works for the first element and not the others. Therefore the other selected menu items does not get selected.

**Comment by mikewheaton** [comment]
Thanks for the bug report and suggested fix, @brannmar. I'm not sure what that `:first` selector is there for – we'll take a closer look and get a fix in soon. Until we release a new version, are you able to modify your copy locally so that you're not blocked?

**Comment by mikewheaton** [comment]
Would you mind submitting a pull request with your fix?

**Comment by brannmar** [comment]
I will try. Have to setup an development evironment for this.

**Comment by mikewheaton** [comment]
Fixed by PR #615.
