### ISSUE TITLE
nuget :not find package

### ISSUE THREAD

**Issue by haijiandong** [OfficeDev/Office-UI-Fabric#481]
PM> Install-Package office-ui-fabric
Install-Package : 找不到程序包“office-ui-fabric”
所在位置 行:1 字符: 1
+ Install-Package office-ui-fabric
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by mikewheaton** [comment]
Any ideas here, @Jahnp?

**Comment by haijiandong** [comment]
@mikewheaton 
sorry，This problem may be I am wrong package source。
I am in China,so...blocked ？
source：https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/

**Comment by haijiandong** [comment]
I have tried it,Modify source ：https://api.nuget.org/v3/index.json
"Manage NuGet Packages for Solution" ,Here i can install :)
but, "package manager console" still not find package

**Comment by mikewheaton** [comment]
Sorry, I'm not familiar with NuGet myself so am not sure what to suggest here. Was this working for a previous version of Fabric?

**Comment by haijiandong** [comment]
@mikewheaton Thanks,Is the latest version 2.3.0,I like it :)

**Comment by mikewheaton** [comment]
So everything is working okay now?

**Comment by haijiandong** [comment]
yes, @mikewheaton 
Thank you for your reply :-)

**Comment by mikewheaton** [comment]
Glad to hear it's working, and that you're liking Fabric! Open an issue here any time you have trouble or a question for us. :smile:

**Comment by haijiandong** [comment]
Okey @mikewheaton ,Thank you for your work,This is a great project.😄
