### ISSUE TITLE
NAME THE RELEASES AFTER HOT SAUCES THANK YOU 🔌🚀🎈

### ISSUE THREAD

**Issue by battletoilet** [OfficeDev/Office-UI-Fabric#484]

**Comment by mikewheaton** [comment]
Any suggested names?

**Comment by Jahnp** [comment]
Fabric 3.0: WackyTabascy

**Comment by mikewheaton** [comment]
Here's a [list of 130 hot peppers](https://www.cayennediane.com/big-list-of-hot-peppers/), with no trademark concerns. :smile:

**Comment by manndave** [comment]
Well, that limits you to only 130 releases.  What do you do for 131?  ;-)

**Comment by dammittom** [comment]
Go backwards up that list, so we tell everyone how our fabric releases just keep getting hotter.

**Comment by notandrew** [comment]
piri piri :fire:

**Comment by mikewheaton** [comment]
We're going to go ahead and use the names of spicy peppers, working our way from most spicy to least spicy. The idea is that Fabric should get more tolerable over time. 😉 

**Fabric 3.0 is codenamed "Ghost".**

![image](https://cloud.githubusercontent.com/assets/1382445/15729740/c4e8a338-281b-11e6-9b74-2b1f4011d74e.png)
