### ISSUE TITLE
Plans to include suiteBarTop element?

### ISSUE THREAD

**Issue by philbritton** [OfficeDev/Office-UI-Fabric#488]
The overall navigation of Office 365 is great for large applications with many components.  The glue that seems to stick it all together is the top bar with the nine box in the left to link to other apps and the user profile on the top right.  Is this something that might be implemented here?

**Comment by mikewheaton** [comment]
This has been [requested before](https://github.com/OfficeDev/Office-UI-Fabric/issues/81) but is not something we have planned right now. The [Office 365 AppChrome Control repo](https://github.com/OfficeDev/Office-365-AppChrome-Control) might be what you're looking for.
