### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by manndave** [OfficeDev/Office-UI-Fabric#494]
Need a question mark inside an empty circle.  Thanks.

**Comment by mikewheaton** [comment]
We've added this icon request to [our roadmap](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md) and hopefully it can be included in a future release.

For the time being, you can use the existing question mark icon and place it inside an element with `border-radius: 50%` and a border to simulate the effect. You may need to tweak the vertical and horizontal position to get it visually centered.
