### ISSUE TITLE
Add JavaScript to the CDN

### ISSUE THREAD

**Issue by davidchesnut** [OfficeDev/Office-UI-Fabric#496]
The document states that CSS files are hosted on CDN but there is no information about the JS components. They should also be available via CDN. If they are available then this should be documented.

**Comment by mikewheaton** [comment]
We don't have JavaScript on the CDN right now (long story...) but will look into this again to see if we can include it.

**Comment by ericthompson** [comment]
Totally true that we host the CSS, but our focus is mostly in this area. We'll add it to our [roadmap](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md) as something that has been requested so we can track it, but I'm afraid it's not on the immediate horizon (for now).
