### ISSUE TITLE
Textfield: use disabled attribute, not is-disabled class

### ISSUE THREAD

**Issue by andikrueger** [OfficeDev/office-ui-fabric#500]
The textfield is not disabled in IE 10 when class .is-disabled is used.

This markup:
`<div class="ms-TextField is-disabled">
  <label class="ms-Label">Name</label>
  <input class="ms-TextField-field">
  <span class="ms-TextField-description">This should be your first and last name.</span>
</div>`

should render a textfield like that one (ie. latest Chrome)
![image](https://cloud.githubusercontent.com/assets/15608729/14579045/3c89828a-039c-11e6-8b0c-730497953d7e.png)

in IE 10 it is still possible to click into the inputfield and insert stuff:
![image](https://cloud.githubusercontent.com/assets/15608729/14579053/68699b60-039c-11e6-9d12-4998e27c159f.png)

I think the source of the problem is, that the class .is-disabled is using " pointer-events: none;". It seems that this is not working in IE 10. In IE 10 it is required to set the input to disabled as well.

**Comment by StfBauer** [comment]
You cannot disable a text field by assigning a css class only you need to place the property:
`disabled='true'` directly on the input field.
The css lass 'is-disabled' only provides the design of a disable input field.

**Comment by andikrueger** [comment]
the class .is-disabled contains the "pointer-events" attribute, that prevents all events for the DIV and for underlying elements in newer browsers. It's not possible to click into the input and edit it. During the form submit it still gets posted to the server, which is ok in most cases. 
I think I'll stick with adding disabled to the input element, as you recommended. This provides cross browser compatibility. 

Seen that way, .is-disabled does not prevent the pointer-event on the div and its child elements in IE10.

**Comment by mikewheaton** [comment]
We should probably require use of the `disabled` attribute rather than having the `is-disabled` state class. Having both is confusing and likely to cause issues with browsers and accessibility.
