### ISSUE TITLE
Could not find undo redo icons

### ISSUE THREAD

**Issue by padewitte** [OfficeDev/Office-UI-Fabric#502]
Is there any chance to see soon an undo and a redo icons in the list of provided icons ? If not do you have any pointer to a svg source ?

**Comment by ericthompson** [comment]
Hi @padewitte!

We provide the "reply" icon which is actually used across Microsoft Office properties:
![image](https://cloud.githubusercontent.com/assets/1420854/14686813/4f3b435e-06ef-11e6-8098-f67b143a4cc0.png)


You can see it in the Outlook Web App for the undo metaphor:
![image](https://cloud.githubusercontent.com/assets/1420854/14686944/da842110-06ef-11e6-9698-c33722676912.png)

...and the Word app for both undo and redo:
![image](https://cloud.githubusercontent.com/assets/1420854/14686755/17bc4c98-06ef-11e6-8f5d-908891c9d28e.png)

For redo, you can simply flip the icon along the vertical axis to where it points in the opposite direction. Let us know if you have any questions!
