### ISSUE TITLE
Typeahead / autocomplete component

### ISSUE THREAD

**Issue by lagivan** [OfficeDev/Office-UI-Fabric#504]
I could not find a typeahead component in UI Fabric. There is one in UI Bootstrap: https://angular-ui.github.io/bootstrap/#/typeahead

Is it worth adding it to the roadmap? I think it's very useful in search applications.

**Comment by ericthompson** [comment]
Thanks for the suggestion, @lagivan - we're actually in the process of looking at this right now but don't have a timeframe. I just added it to [the roadmap](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md)!

**Comment by oozoo-solutions** [comment]
Is this still on the radar?
There's nothing actually in the Trello board that's linked from the roadmap

Cheers

**Comment by ericthompson** [comment]
Hi @oozoo-solutions - the components have been moved out of the core repository (this one) and into a new repository called [Office UI Fabric JS](https://github.com/OfficeDev/office-ui-fabric-js) which has its own [Trello board](https://trello.com/b/wq7oIK87/office-ui-fabric-js-requests). I assure you, your request is alive and well :smile: 

For now, we're focusing our efforts on the [Fabric React](https://github.com/OfficeDev/office-ui-fabric-react) project, but we're watching the Trello boards/Issue trackers closely. Please vote up to help us see what folks are looking for.
