### ISSUE TITLE
Panel: Animations not working since 2.2.0

### ISSUE THREAD

**Issue by tobiaswest83** [OfficeDev/Office-UI-Fabric#505]
Animations for `.ms-Panel-animateIn` and `.ms-Panel-animateOut` no longer appear to work, they were OK in 2.1.0. Can't see any changes in how animations should be applied in [JQuery.Panel.js](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/src/components/Panel/Jquery.Panel.js) so I don't think it's a case that the demo is wrong. 

## 2.2.0 upwards

Panel opens quickly, and doesn't close correctly. CommandBar hidden

https://embed.plnkr.co/44Tx7k4YGuNr1Otv2SnT/

## 2.1.0 

Panel animates in and out correctly. CommandBar animates in

https://run.plnkr.co/plunks/uPCbFZqBknCDoU7W7mji/

**Comment by ericthompson** [comment]
Uh oh - that's not good. I'm not seeing it in my local build of 2.4.1, but I'll put a bug on us to see if we can investigate and understand what's happening.

**Comment by mikewheaton** [comment]
Fixed by PR #615. The Panel animates in and out correctly now.
