### ISSUE TITLE
Toggle: Not keyboard accessible

### ISSUE THREAD

**Issue by vibhava** [OfficeDev/Office-UI-Fabric#506]
Hi, We use the fabric toggle 
<input tabindex="0" class="ms-Toggle-input" id="PlanPrivacyToggle" type="checkbox" data-bind="checked: isPublic">
tabindex has been set to 0, so it is tab-able, but I am not able to toggle it with keyboard. I tried space and enter. Would there be something else I am missing?
![fabric toggle](https://cloud.githubusercontent.com/assets/17240119/14754573/10f3043a-0891-11e6-82f9-4bfb43c2f2fa.PNG)

Thank you for taking a look.

**Comment by mikewheaton** [comment]
Thanks for reporting this issue, @vibhava. We'll take a look and get this fixed – accessibility and keyboard navigation are very important to us.

**Comment by vibhava** [comment]
Thank you for taking a look. Please let me know if there is a key
combination you expect me to use that I am not aware of. I only tried space
and enter.

Vibha

**Comment by lixonic** [comment]
@vibhava adding tabindex works for me `  <input type="checkbox" id="demo-toggle-3" class="ms-Toggle-input" tabindex="0" />
`
