### ISSUE TITLE
Documentation: Wrong package name in the Getting Started page

### ISSUE THREAD

**Issue by PaoloPia** [OfficeDev/Office-UI-Fabric#509]
The statement:

PM> Install-Package office-ui-fabric

in page http://dev.office.com/fabric/get-started is wrong, or at least doesn't work.
The right one is:

PM> Install-Package OfficeUIFabric

Thanks,
Paolo

**Comment by mikewheaton** [comment]
We've confirmed this issue and will get the documentation updated. Thank you!

**Comment by mikewheaton** [comment]
This has been fixed in our documentation repo and will be included in the next deployment.
