### ISSUE TITLE
TextField: Multiline textfield should be using semilight (not regular) Segoe

### ISSUE THREAD

**Issue by ericthompson** [OfficeDev/Office-UI-Fabric#510]
Per our design language, the text entered into a textfield should be semilight, but the multiline textfield currently uses regular:
![single](https://cloud.githubusercontent.com/assets/1420854/14869694/ee1719fe-0c89-11e6-811e-5657b4cc3818.png)
![multi](https://cloud.githubusercontent.com/assets/1420854/14869693/ee147cc6-0c89-11e6-9b81-f9b60bd715c3.png)

**Comment by lixonic** [comment]
Fixed. https://github.com/OfficeDev/Office-UI-Fabric/pull/607
