### ISSUE TITLE
Panel: left panel does not display content

### ISSUE THREAD

**Issue by ascot31** [OfficeDev/office-ui-fabric#511]
I use the panel with alignment to the left and this does not show the content think it is problem of a style that says:

```
.ms-Panel.ms-Panel--left .ms-Panel-commands,
.ms-Panel.ms-Panel--left .ms-Panel-contentInner {
  display: none;
}
```

Thanks

**Comment by lixonic** [comment]
Yep, same issue with `ms-Panel--lightDismiss`  . Created a PR
