### ISSUE TITLE
Components with dependencies contain duplicate styles

### ISSUE THREAD

**Issue by purtuga** [OfficeDev/Office-UI-Fabric#512]
I'm using v.2.4.1 installed via Bower.
I noticed that `dist/components/CommandBar/CommandBar.css` includes the styles associated with `ContextualMenu`. Is that by design?
They seem to be the same styles as `ContextualMenu` component, so I assume this is not the intended behavior?. 

/Paul.

**Comment by mikewheaton** [comment]
As the CommandBar can contain a ContextualMenu, we've included the styles for both components in `CommandBar.css` to ensure that the dependency is met and everything works well. However, this simple method of handling dependencies is now deprecated in favor of [custom bundling](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/BUNDLING.md) which results in much less duplicate code. We should remove these duplicate styles for dependencies and recommend bundling going forward.

**Comment by purtuga** [comment]
Glad to hear that it should be corrected and thanks for the pointer to the custom builds. I'll certainly will looking into it. 

Paul
-- sent from mobile

**Comment by mikewheaton** [comment]
We discussed this today and agreed that it's not necessary to include the dependency CSS within each component's CSS. Instead, our documentation will make those dependencies clear and you'd just be expected to include all of the required CSS files.

This allows for a simple method to use a small subset of components (without duplicate styles) while [custom bundling](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/BUNDLING.md) will remain the recommended method. We will do the same thing for components that require JavaScript.

**Comment by purtuga** [comment]
That's excellent @mikewheaton. That will make it much easier to use only what we need in custom solution without having to clone the project and run a custom build.  

(FYI: I was including Office UI Fabric components into an existing project using LESS, thus the built individual .css files are very helpful)

**Comment by mikewheaton** [comment]
Fixed by PR #615. The component folders within `dist` no longer contain CSS files, only Sass, and those files don't have references to dependencies. This makes for smaller file sizes with no repeated styles.
