### ISSUE TITLE
Animation Docs Errors

### ISSUE THREAD

**Issue by zkoehne** [OfficeDev/Office-UI-Fabric#516]
On [http://dev.office.com/fabric/styles](http://dev.office.com/fabric/styles), there are a few small errors in the animation docs. `ms-u-slideUpIn10` uses the `ms-u-slideDownIn10` animation, and `ms-u-slideUpOut20` is duplicated.

**Comment by mikewheaton** [comment]
Thanks, @zkoehne, we'll get this fixed up. 😄

**Comment by mikewheaton** [comment]
This change has been made to the documentation site and will be included in the next deployment.
