### ISSUE TITLE
Autocomplete Field Where is it?

### ISSUE THREAD

**Issue by phemto5** [OfficeDev/Office-UI-Fabric#519]
Can you please make a new component for autocomplete. Sometimes You want a user to select a value, but there are more than a reasonable amount of choices for a dropdown.

**Comment by mikewheaton** [comment]
We do have this on [our roadmap](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md) as a commonly-requested feature that we'd like to include. Unfortunately at this time there's no one assigned to work on it, but we do hear your request.
