### ISSUE TITLE
Datepicker - Firefox crashes on selecting date

### ISSUE THREAD

**Issue by nilobarp** [OfficeDev/Office-UI-Fabric#520]
On desktop mode, Firefox crashes as soon as I select a date.
In mobile mode, crash happens even before the datepicker is displayed.

![2016-05-04 17_48_05-office dev center - datepicker](https://cloud.githubusercontent.com/assets/1141369/15010817/ce186670-1220-11e6-99d5-1191c9d27ad7.png)
![2016-05-04 17_48_25-office dev center - datepicker](https://cloud.githubusercontent.com/assets/1141369/15010829/e11063d6-1220-11e6-8372-ed426109d5af.png)
![2016-05-04 17_48_47-mozilla crash reporter](https://cloud.githubusercontent.com/assets/1141369/15010840/f5560d96-1220-11e6-96f2-20bc6ed018c5.png)

**Comment by av-virlan** [comment]
I believe this is related to the jquery plugin pickadate - there's a similar issues here though not yet resolved - https://github.com/amsul/pickadate.js/issues/835

**Comment by mikewheaton** [comment]
Thanks for digging up that issue with Pickadate, @av-virlan. I'll close this issue as it does appear to be the same one with Pickadate.
