### ISSUE TITLE
Documentation: Build docs assume Gulp is already installed globally

### ISSUE THREAD

**Issue by atneik** [OfficeDev/Office-UI-Fabric#521]
The [build documentation](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/BUILDING.md#building-fabric) assumes that gulp is already installed globally, which results into 'command not recognized' if the user runs it on a new system. Either we need to specify that gulp is needed globally before running the command, or have a npm script in package.json which runs the local gulp:

Something like: `"scripts": {
    "build": "gulp"
  } ` (we already have this, but by the name of test) in package.json can allow a command `npm run build` and run the latest version of local gulp:

1. Clone the repo.
2. Navigate to the folder that contains the gulpfile.js file (Fabric's root).
3. `npm install`
4. `npm run build`

**Comment by ericthompson** [comment]
Closed via [this commit](https://github.com/OfficeDev/Office-UI-Fabric/commit/fd5071637286cfc02fce6fcd17602816f1384e1b).
