### ISSUE TITLE
Question: Datepicker: setting maxDate and minDate

### ISSUE THREAD

**Issue by prmutha** [OfficeDev/Office-UI-Fabric#533]
My scenario is to set the maxDate and minDate on the DatePicker control to disable the ability of the user to choose any future dates from now.

Any pointers on this.

I appreciate your time.

-Priya

**Comment by mikewheaton** [comment]
The DatePicker is powered by the [pickadate.js](http://amsul.ca/pickadate.js/) jQuery plugin. It has methods for setting a [minimum date](http://amsul.ca/pickadate.js/api/#method-set-min) and [maximum date](http://amsul.ca/pickadate.js/api/#method-set-max). I haven't tested these, but suspect that it would block navigation to other dates and it likely applies some sort of disabled CSS class to the unavailable days within the calendar.

**Comment by prmutha** [comment]
Thank you for the prompt reply. I shall test this out.
