### ISSUE TITLE
Angular Directives for UI Fabric Components

### ISSUE THREAD

**Issue by andrewconnell** [OfficeDev/Office-UI-Fabric#55]
Other design languages like [Bootstrap](http://getbootstrap.com/) & Google's [Material Design](http://www.google.com/design/spec/material-design/introduction.html), there are projects that have created Angular directives for these design languages: [UI Bootstrap](http://angular-ui.github.io/bootstrap/) & [Angular Material](https://material.angularjs.org/latest/#/).

- Any thoughts to something like **ng-office-ui-fabric**? Maybe either as part of this project or, to follow what those other projects do, have a separate project & repo for it? 
- Is this something (a) you're working on or (b) the community should run with?

**Comment by IvanJosipovic** [comment]
+1

**Comment by martindr** [comment]
+1

**Comment by pascalberger** [comment]
+1

**Comment by rstormsf** [comment]
React Mixins!

**Comment by ahmad-hamade** [comment]
+1

**Comment by davidlitmark** [comment]
+1

**Comment by bstenberg64** [comment]
+1

**Comment by sergeluca** [comment]
+1

**Comment by colinrippey** [comment]
+1

**Comment by LezaMax** [comment]
We would love for the community to chime in the short term. While we are certainly evaluating additions on this space we would love to see community specific projects that add this capability.

**Comment by andrewconnell** [comment]
OK... I'll be happy to take this on... I've created a repo and will start flushing it out with community contribution guidelines: https://github.com/andrewconnell/ng-office-ui-fabric

**Comment by andrewconnell** [comment]
... and just to beat the horse a bit more, here's a followup and details on future plans: http://www.andrewconnell.com/blog/introducing-ng-officeuifabric-angular-directives-for-office-ui-fabric
