### ISSUE TITLE
Dropdown: Not working in mobile view

### ISSUE THREAD

**Issue by techvenky** [OfficeDev/Office-UI-Fabric#552]
Fabric UI dropdown component is not working in mobile view or smaller width. Please find the attached image.

![image](https://cloud.githubusercontent.com/assets/1742973/15338183/bd73e5fc-1c4c-11e6-9ca4-fdf0c41f248c.png)

**Comment by mikewheaton** [comment]
Thanks for reporting this, we'll have a look.

**Comment by lixonic** [comment]
this is happening below 480px . Opened a PR . please review
 
![issue1](https://cloud.githubusercontent.com/assets/934220/15550070/56318318-22cd-11e6-92f7-81f9659f0f42.gif)

**Comment by mikewheaton** [comment]
Fixed by PR #615

**Comment by andrewconnell** [comment]
While fixed in current versions of fabric, any thoughts to going back and applying the CSS fix to the 2.6.2 release? Many folks didn't update to the latest MDL2 implementation of the library yet.

**Comment by mikewheaton** [comment]
@andrewconnell: We should be able to do that. Would you mind opening an issue in [Fabric JS](https://github.com/OfficeDev/office-ui-fabric-js) for this?
