### ISSUE TITLE
TimePicker Component

### ISSUE THREAD

**Issue by JasonWeise** [OfficeDev/office-ui-fabric#558]
Hey

I am looking at taking up Fabric UI in our next project instead of Bootflat and am looking for one missing component - TimePicker. It is the only sticking point at the moment and wonder if one is likely to be implemented any time soon. I know there are a few loose ones floating around the web, but really want one that is nicely integrated with Fabric UI and has a consistent theme to it.

Any thoughts? 
PS. Keep up the great work, impressed with the direction Microsoft is taking lately and we are a large user of O365 and Azure and this UI Kit meets the look and feel of our custom apps perfectly!

**Comment by mikewheaton** [comment]
We don't have plans to create a TimePicker component right now. Could you send screenshots of other time pickers so we have an idea of what you're looking for?

**Comment by ericthompson** [comment]
@JasonWeise - any specific examples you're looking at?

**Comment by ArnonEilat** [comment]
@ericthompson although it's not my question, i'm looking for the same component.
Here are some examples:
- https://jdewit.github.io/bootstrap-timepicker
- http://ericjgagnon.github.io/wickedpicker/
- http://www.material-ui.com/#/components/time-picker

**Comment by ericthompson** [comment]
Thanks, @ArnonEilat. We've added this to the [roadmap](https://github.com/OfficeDev/office-ui-fabric/blob/master/ghdocs/ROADMAP.md), so we'll close the issue for now. 

@JasonWeise - feel free to pile on if you have specific examples you're looking at. The ones provided by @ArnonEilat are pretty varied, so it would be good to see what you were thinking as well.

Thanks all!

**Comment by davegrice** [comment]
FWIW, the style of timepicker used by the Material UI example previously mentioned at: 

http://www.material-ui.com/#/components/time-picker

...or as implemented in Bullhorn's Novo Elements here: 

http://bullhorn.github.io/novo-elements/#/calendar (scroll down past the Calendar)

presents the best modern desktop UX, in my opinion.  Mobile usability would have to be carefully crafted though, to avoid being overly fiddly.

**Comment by codeaid** [comment]
That's actually one of my few issues with this library. I need a time picker in my application and without a component I'll have to stick with React Toolbox (or something else that has a picker too).

Any update on your plans regarding this component, guys?

**Comment by mikewheaton** [comment]
@codeaid No updates here, unfortunately. I'm not aware of any plans to build a TimePicker for either Fabric JS or Fabric React.
