### ISSUE TITLE
Docs could be improved to be a bit clearer on necessary JS for some components

### ISSUE THREAD

**Issue by andrewconnell** [OfficeDev/Office-UI-Fabric#57]
Within the repo & on the [supporting MSDN article](https://msdn.microsoft.com/EN-US/library/office/6f46dd69-2ba3-4b0f-9735-7d7394ca2731.aspx) there is mention that there are some...

>  JS files are currently sample code that you will likely need to modify for your particular needs

To me that implies that the sample code is how you might want to use it, but some controls have JS that IMHO is absolutely required... for instance the search box & dropdown components require it.

For instance… the dropdown shows this sample code… but with just that and the CSS, it won’t work.
https://github.com/OfficeDev/Office-UI-Fabric/blob/master/src/components/Dropdown/Dropdown.html

You MUST reference this file as well:
https://github.com/OfficeDev/Office-UI-Fabric/blob/master/src/components/Dropdown/Jquery.Dropdown.js

And then in the file where you added the dropdown, you must attach it like you see in this sample:
https://github.com/OfficeDev/Office-UI-Fabric/blob/master/dist/samples/Components/Dropdown/index.html#L26

IMHO, this type of information on what's required for each components should really be in the doc for the component. Is this the type of info you're looking for community contribution for?

**Comment by LezaMax** [comment]
Is this better? https://msdn.microsoft.com/EN-US/library/office/mt450443.aspx if so we can update other docs to follow the pattern.

**Comment by andrewconnell** [comment]
The change does help.
