### ISSUE TITLE
Issue Tracker list missing labels mentioned in contributing doc

### ISSUE THREAD

**Issue by andrewconnell** [OfficeDev/Office-UI-Fabric#58]
The [contributing](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/CONTRIBUTING.md) mentions labels used in the issues list for questions... but seems they are missing from the list... only thing present are the OOTB ones

**Comment by Jahnp** [comment]
Oops! Great catch. Those have been added now.
