### ISSUE TITLE
Mention that license is MIT in FAQ

### ISSUE THREAD

**Issue by stuaxo** [OfficeDev/Office-UI-Fabric#60]
I'm lazy and had to go click on the license, it would be nice if there was one line on this in the FAQ.

**Comment by Jahnp** [comment]
Great call! We'll add a note soon. Thanks for calling this out!

**Comment by Jahnp** [comment]
[This has now been added!](https://github.com/OfficeDev/Office-UI-Fabric#how-is-fabric-licensed) Thanks again for the suggestion.
