### ISSUE TITLE
How to resize the Dialog?

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/Office-UI-Fabric#608]
Starting a new issue to continue to discussion with @johnnyongesa from #129.

Please see the demonstration of resizing a dialog here: http://plnkr.co/edit/tPZ8GJ?p=preview

![image](https://cloud.githubusercontent.com/assets/1382445/15582657/f3930d9e-2326-11e6-9048-dddec88629a6.png)

All you should need to add to your CSS is the following override:

```
.ms-Dialog-main {
  max-width: 600px; /* Your maximum width here */
}
```

**Comment by johnnyongesa** [comment]
Thank you. its working
