### ISSUE TITLE
How do i force the "ms-ListItem-tertiaryText" in "ms-ListItem" to display fully. the ms-ListItem-tertiaryText is cut when the text is too log, i want it to resize to accommodate the whole text

### ISSUE THREAD

**Issue by johnnyongesa** [OfficeDev/Office-UI-Fabric#609]

**Comment by mikewheaton** [comment]
By default, the third line of text in ListItem gets an ellipsis (...) when the text is too long to fit in a single line:

![image](https://cloud.githubusercontent.com/assets/1382445/15583461/b98482b4-232a-11e6-9919-dcf85218aaee.png)

You can override this like so:

```
.ms-ListItem-tertiaryText {
  white-space: normal;
}
```

![image](https://cloud.githubusercontent.com/assets/1382445/15583487/d71557ea-232a-11e6-8b13-b360f1439847.png)

**Comment by johnnyongesa** [comment]
Thanks mike. works like charm
