### ISSUE TITLE
Is there any good documentation on using ui fabric ms-Grid class

### ISSUE THREAD

**Issue by johnnyongesa** [OfficeDev/Office-UI-Fabric#611]
I am using ui fabric ms-Grid class with a menu in contextual menu and a table in the main content area. The table does not occupy the whole content area in large screens and when resizing the screen the table goes behind the menu. Their properties are as shown below

```
<div class="ms-Grid"> 
 <div class="ms-Grid-row">
    <div class="ms-Grid-col ms-u-sm6 ms-u-md5 ms-u-lg2">
         <div class="ms-Grid-row">
    <div class="ms-Grid-col ms-u-sm6 ms-u-md5 ms-u-lg2">
 <ul class="ms-ContextualMenu is-open">
//menu here
 
</ul>
        </div></div>

      </div>
     </div>
     </div>
```

   ```
    <div class="ms-Grid"> 
    <div class="ms-Grid-row">
    <div class="ms-Grid-col ms-u-sm6 ms-u-md6 ms-u-lg9">

  <div class="ms-Grid-row" >
    <div class="ms-Grid-col ms-u-sm6 ms-u-md6 ms-u-lg9">
        <%-- COMMAND and table --%>
        <div id="GETTableViewRow">
    <div class="ms-CommandBar">
   <%-- COMMAND BAR --%>
```

**Comment by mikewheaton** [comment]
Have you reviewed the [grid documentation on the website](http://dev.office.com/fabric/styles#responsive-grid)? It should be helpful in understanding how responsive layouts can be built.

Looking at the code you've included, it seems that many of the `div` elements aren't closed. You'll also want to have the columns within each row add up to 12. For example, combine two columns with `ms-u-lg6` to total 12, or one `ms-u-lg4` and one `ms-u-lg8`.

While our class names are different, our grid shares the same concepts as many other CSS toolkits. The [W3C guide to the Bootstrap grid](http://www.w3schools.com/bootstrap/bootstrap_grid_system.asp) is an excellent resource.

**Comment by johnnyongesa** [comment]
Thanks, sorry i did not copy the whole content. the divs are actually closed. and total number gids in a column add up to 12. My scenario is my page uses the default sharepoint 2013 master page. my page contains 2 asp content place holders: <asp:Content `ContentPlaceHolderID="PlaceHolderLeftNavBar" runat="server">  <div class="ms-Grid"> 
 <div class="ms-Grid-row">
    <div class="ms-Grid-col ms-u-sm6 ms-u-md5 ms-u-lg2">
        </div>
</div></div></asp:Content>` and `<asp:Content  ContentPlaceHolderID="PlaceHolderMain" runat="server"><div class="ms-Grid"> 
    <div class="ms-Grid-row">
    <div class="ms-Grid-col ms-u-sm6 ms-u-md7 ms-u-lg10"></div></div></div></asp:Content>`. each place holders i have an ms-grid. with one row. The problem is that the ms grid is the PlaceHolderMain leave out some white space in the right in large screens and when i re size the page it falls behind the menu.` I have used different ms-grids because the divs are in different asp content place holders`

**Comment by johnnyongesa** [comment]
Guys after looking at my code very well i think i need to make one column fixed(it should not resize at all) then allow the other column to resize. The problem is i don't know how to make an ms-grid column fixed

**Comment by mikewheaton** [comment]
The grid is intended for flexible layouts, so the columns will always resize based on a percentage of the row's width. If your layout calls for a fixed column you'll want to use standard layout techniques (e.g. [this W3C example](http://www.w3schools.com/html/html_layout.asp)) to position things on your page. You could then use the `ms-Grid` classes within the content area if you do have content that should scale proportionally to fit.

**Comment by johnnyongesa** [comment]
I found the way out, The `xl,xxl,xxx` sizes for ui fabric fixed my issue. i think microsoft overllok this in the office ui fabric documentation.

**Comment by mikewheaton** [comment]
Good point, we don't actually document all of the breakpoints and grid classes. I've opened a [issue #656](https://github.com/OfficeDev/office-ui-fabric/issues/656) to track this.

**Comment by shurick81** [comment]
Seems like the documentation has moved to https://dev.office.com/fabric#/styles/layout

**Comment by bnkamalesh** [comment]
docs have moved to https://developer.microsoft.com/en-us/fluentui
