### ISSUE TITLE
Panel: Left variant not working

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/Office-UI-Fabric#619]
Looking at the code it seems that a left Panel should be possible by adding on the `ms-PanelHost--left` and `ms-Panel--left` modifiers. When I do so, the content disappears from the Panel entirely. 

![image](https://cloud.githubusercontent.com/assets/1382445/15733111/9a254c2a-2837-11e6-89ee-611326a89d27.png)

![image](https://cloud.githubusercontent.com/assets/1382445/15733107/8f7e9556-2837-11e6-8c74-10e50b9c9861.png)

**Comment by mikewheaton** [comment]
See comments from @lixonic in PR #605 for a possible fix.

**Comment by lixonic** [comment]
@mikewheaton its #604

**Comment by lixonic** [comment]
@mikewheaton actually this [screenshot](https://monosnap.com/file/kWnS0NuCNvAkLbw6UnNaBl7pclZ9vF) is from old `dist/` . Instead I should have checked `localhost:2020`.  How would i  add a `--left` variant ? i didn't find any documentation.

**Comment by lixonic** [comment]
and obviously the bug is here > https://github.com/OfficeDev/Office-UI-Fabric/blob/master/src/components/Panel/Panel.scss#L88-L91

**Comment by mikewheaton** [comment]
Turns out this is a duplicate of #511. Closing this one.
