### ISSUE TITLE
Facepile: Not working

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric#634]
This doesn't look quite right:

![image](https://cloud.githubusercontent.com/assets/1382445/15807789/3d16e016-2b1b-11e6-9030-f96db212cd6c.png)

**Comment by lixonic** [comment]
missing `<div class="ms-Persona-initials">` ?

https://monosnap.com/file/tOl2xLJFmuRJprAicbR5N4XiHMpZT5

@mikewheaton  @philworthington

**Comment by lixonic** [comment]
@mikewheaton pushed a fix #660 

![f1](https://cloud.githubusercontent.com/assets/934220/15985044/53f46b68-2ffe-11e6-9022-de302666750b.png)
![f2](https://cloud.githubusercontent.com/assets/934220/15985045/53fa9196-2ffe-11e6-99dd-4d4cb73c378d.png)

**Comment by Jahnp** [comment]
This has been fixed for 3.0.
