### ISSUE TITLE
PeoplePicker: Use the circle persona in results list

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric#635]
We should use the circular persona in the results list, as it's the new default.

![image](https://cloud.githubusercontent.com/assets/1382445/15807803/85fbe948-2b1b-11e6-9932-55d4c22d5532.png)

**Comment by lixonic** [comment]
@mikewheaton  is this broken? i'm on latest master

![peoplepicker 2016-06-11 23-12-36](https://cloud.githubusercontent.com/assets/934220/15986650/61f0b948-302a-11e6-9844-205f3031a69f.png)

**Comment by mikewheaton** [comment]
Yes, the PeoplePicker is currently broken in master and @philworthington is working on it. 😄

**Comment by Jahnp** [comment]
This has been fixed for 3.0.
