### ISSUE TITLE
Persona: Remove the square persona

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric#636]
I think the round personas are used everywhere now. Can we go ahead and remove the square ones?

![image](https://cloud.githubusercontent.com/assets/1382445/15808361/0d1b9b4e-2b2b-11e6-920c-2f5b92fade89.png)

**Comment by ericthompson** [comment]
Agreed - I think this makes sense.

**Comment by tyrasm** [comment]
+1

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
