### ISSUE TITLE
Font License Link is broken

### ISSUE THREAD

**Issue by braintapper** [OfficeDev/Office-UI-Fabric#64]
I was trying to see what the rules/licensing for using Segoe UI were, and the link in line 28 of `_Fabric.Typography.Fonts.less` is broken:

https://appsforoffice.microsoft.com/fabric/Segoe UI and Fabric CDN License.txt

**Comment by Jahnp** [comment]
Thanks for calling this out! We're working on getting things deployed right now.

**Comment by LezaMax** [comment]
In the meantime, here is the correct link: http://aka.ms/fabric-font-license

**Comment by Jahnp** [comment]
A fix has been deployed--though we won't be updated link in 1.0 itself, we now have a redirect set up to handle the incorrect link. I'll close this issue, since the license should now be accessible. Thanks!
