### ISSUE TITLE
new field search icon

### ISSUE THREAD

**Issue by MartinSSeifert** [OfficeDev/Office-UI-Fabric#648]
I would like to see the field icons complimented with a ms-Icon--fieldSearch as drafted in the image below
![fieldsearch](https://cloud.githubusercontent.com/assets/19793161/15849123/3a6fda94-2c91-11e6-9578-d0ee6c31167f.jpg)

**Comment by ericthompson** [comment]
Thank you for filing this, Martin! Now that we've got in in our issues list, [I've gone ahead and added it to our roadmap's icon request section](https://github.com/OfficeDev/Office-UI-Fabric/commit/d78fd799c748ae60c1aa62f66ccc4d613b31a541).
