### ISSUE TITLE
Editable ms-drop down

### ISSUE THREAD

**Issue by johnnyongesa** [OfficeDev/office-ui-fabric#662]
Hi Guys,
Is there a way i can make my `ms-drop down editable`. I need to allow users to select options from the drop down or just type in new entries if the entry is not listed.

**Comment by mikewheaton** [comment]
We don't have this capability right now. Could you point to an example somewhere so that we're clear on what you're trying to achieve, and can add this as a request to our road map? For now you will probably need a separate text field for entering a value that is not available in the dropdown.

**Comment by johnnyongesa** [comment]
See sample  from` http://jqueryui.com/autocomplete/#combobox`
When i try to apply the same to ms-drop down the control breaks

**Comment by mikewheaton** [comment]
We do plan to add a searchable/autocomplete dropdown component (see [our roadmap](https://github.com/OfficeDev/office-ui-fabric/blob/master/ghdocs/ROADMAP.md)) but don't have the work scheduled yet.
