### ISSUE TITLE
how to disable command bar item

### ISSUE THREAD

**Issue by nandhu** [OfficeDev/office-ui-fabric#664]
Hi,
I have command bar and I want to enable / disable one CommandBarItem based on the condition. But the disable is not support in CommandBarItem . Also I tried with ng-disabled. but no luck.

`<div class="ms-CommandBar">
        <div class="ms-CommandBarItem cmd-add-section" ng-click="addNewSection()">
            <div class="ms-CommandBarItem-linkWrapper">
                <a class="ms-CommandBarItem-link" data-target=".ms-Dialog--close" tabindex="1"> <span class="ms-CommandBarItem-icon ms-Icon ms-Icon--plus"></span> <span class="ms-CommandBarItem-commandText ms-font-m ms-font-weight-regular">Section</span> </a>
            </div>
        </div>
        <div class="ms-CommandBarItem cmd-edit-section"  ng-click="editCurrentSection()">
            <div class="ms-CommandBarItem-linkWrapper">
                <a class="ms-CommandBarItem-link" tabindex="1"> <span class="ms-CommandBarItem-icon ms-Icon ms-Icon--editBox"></span> <span class="ms-CommandBarItem-commandText ms-font-m ms-font-weight-regular">Edit</span> </a>
            </div>
        </div>
        <div class="ms-CommandBarItem cmd-delete-section" ng-click="showDeleteSectionPopup(item)">
            <div class="ms-CommandBarItem-linkWrapper">
                <a class="ms-CommandBarItem-link" tabindex="1"> <span class="ms-CommandBarItem-icon ms-Icon ms-Icon--trash"></span> <span class="ms-CommandBarItem-commandText ms-font-m ms-font-weight-regular">Delete</span> </a>
            </div>
        </div>
    </div>`

**Comment by mikewheaton** [comment]
In Fabric 3.0 we're adding the ability to disable an item in the CommandBar. For now, you'll need to add a custom class to target the disabled CommandBarItem like so:

```
.ms-CommandBarItem.is-disabled .ms-CommandBarItem-icon,
.ms-CommandBarItem.is-disabled .ms-CommandBarItem-commandText {
  color: #A6A6A6;
}

.ms-CommandBarItem.is-disabled .ms-CommandBarItem-link {
  cursor: default;
}

.ms-CommandBarItem.is-disabled:hover {
  background-color: #EFF6FC;
}
```

Then add the `is-disabled` class to your CommandBarItem you want to disable. See [this example](http://plnkr.co/edit/QquUsp?p=preview) where I've disabled the delete button.
