### ISSUE TITLE
ui fabric documentation on a horizontal navigation bar

### ISSUE THREAD

**Issue by johnnyongesa** [OfficeDev/office-ui-fabric#667]
Hi guys, i have been looking for ui fabric documentation on a horizontal navigation bar without success. anyone with a sample

**Comment by mikewheaton** [comment]
Have you seen the [NavBar](http://dev.office.com/fabric/components/navbar) and [CommandBar](http://dev.office.com/fabric/components/commandbar) components? These are about to be merged together in Fabric 3.0, but should be what you are looking for if you need a horizontal bar that provides navigation options.

**Comment by johnnyongesa** [comment]
Thanks mike, was looking for the nav bar.
