### ISSUE TITLE
Missing component javascripts.

### ISSUE THREAD

**Issue by dereknutile** [OfficeDev/Office-UI-Fabric#67]
It seems like each of your Samples (in dist/samples/components/) are all missing their associated .js files.  For example, the ChoiceField component index.html (see here: https://github.com/OfficeDev/Office-UI-Fabric/blob/master/dist/samples/Components/ChoiceField/index.html#L15) calls a file named ChoiceField.js which doesn't exist.  Same thing for all the other components I've looked at.

**Comment by Jahnp** [comment]
Great catch, thanks. I think this is actually an issue with the template used for component samples, which expects a JS file for a component even if one doesn't exist, hence the 404s. We clean that up.

**Comment by dereknutile** [comment]
Awesome, go get 'em Peter.

**Comment by Jahnp** [comment]
Thanks again for flagging this. I'll reactivate this issue for now until we've resolved it--we don't have an ETA yet but I want to be sure it's clear we're aware of it :)

**Comment by digglek** [comment]
I am trying to make use of the dialog but the samples don't show how to open/close a dialog is there some missing js files as the sample references 

<script type="text/javascript" src="Jquery.Dialog.js"></script>
<script type="text/javascript" src="Dialog.js"></script>

However, these do not exist?

**Comment by weshackett** [comment]
In the fabric site the Spinner page doesn't show the js tab alongside the demo html. It should have as it is in the markup of the page, just not showing up.

**Comment by ericthompson** [comment]
@digglek - #274 should help with the JS for the Dialog. We've also included an example of a blocking dialog for extra completeness.

@weshackett - we'll get the examples up on the site asap for both the Spinner and the Dialog.

**Comment by mikewheaton** [comment]
Issue #110 covers needing JS to demonstrate opening and closing a Dialog.
