### ISSUE TITLE
Errors while building Fabric

### ISSUE THREAD

**Issue by pkbullock** [OfficeDev/office-ui-fabric#673]
Hi

I have cloned the master repository and followed the instructions on building the project, however I am getting an error when running "gulp" command: "no writecb in Transform class", is this an error with the fabric or local issue do you know?

I have attached a screenshot.

Thanks
Paul
![2016-06-20](https://cloud.githubusercontent.com/assets/8781041/16190451/3e4e4f24-36d7-11e6-89f7-e030b4c84511.png)

**Comment by mikewheaton** [comment]
Thank you for reporting this, @pkbullock. I'm also encountering a bunch of errors and warnings while running `gulp` on a fresh clone of the Fabric repo. Working on it now.

**Comment by mikewheaton** [comment]
I was hoping this was somehow related to the Sass linting errors, but it doesn't appear to be. 

@battletoilet, could you take a look? I'm getting the same errors you see in the screenshot above, and it seems to be related to the timing of the build. If I manually create an empty `dist/css/fabric.components.min.css` file then the build proceeds past the first error, until it starts looking for another nonexistent file:

![image](https://cloud.githubusercontent.com/assets/1382445/16204198/a2ef1dc8-36d2-11e6-8ea8-40ede0511619.png)

**Comment by mikewheaton** [comment]
It's now failing in the Travis build also.

**Comment by mikewheaton** [comment]
Tracked down the issue to an updated version of gulp-header that was released on Friday. PR #676 has been updated to resolve this issue.

**Comment by mikewheaton** [comment]
Fixed by #676
