### ISSUE TITLE
Accordion contextual menu in office ui fabric

### ISSUE THREAD

**Issue by johnnyongesa** [OfficeDev/office-ui-fabric#681]
Hi Guys, We are changing the UI for one of our sharepoint sites to ui fabric. Is there any sample of how to change the contextual to an accordion menu. Like the office 365. See sample screen shot below.
![image](https://cloud.githubusercontent.com/assets/9988770/16271946/9aad63c6-38a4-11e6-93b9-069e85265bb2.png)

**Comment by mikewheaton** [comment]
As you probably saw, the ContextualMenu does support nested menus:

![image](https://cloud.githubusercontent.com/assets/1382445/16273051/fe78e966-3854-11e6-9156-1ef0c3611142.png)

Unfortunately we don't have an existing design pattern for an accordion-style ContextualMenu, or an accordion-style left nav like you show in the screenshot.
