### ISSUE TITLE
Dropdown Angular 2 Binding

### ISSUE THREAD

**Issue by leekaiwei** [OfficeDev/office-ui-fabric#689]
Is this possible at the moment? It seems all the binding is lost when the dropdown is initialised.

**Comment by mikewheaton** [comment]
Sorry, but I'm not quite clear on the issue here. Could you provide some more details on what you're trying to do?

**Comment by leekaiwei** [comment]
Component:

    // import stuff...

    // @Component...
    class MyComponent implements AfterViewInit{
        myForm: ControlGroup;
        selectOptions: [];

        constructor(formBuilder: FormBuilder) {
            this.selectOptions = ['Apple', 'Banana', 'Orange'];

            this.myForm = formBuilder.group({
                selectedOption: ['', Validators.required]
            });
        }

        ngAfterViewInit() {
            var script = document.createElement('script');
            script.innerHTML = "$(document).ready(function() { if ($.fn.Dropdown) { $('.ms-Dropdown').Dropdown(); }});";
            document.body.appendChild(script);
         }

Template:

    <form [ngFormModel]="myForm">
        <div class="ms-Dropdown" tabindex="0">
            <label class="ms-Label">Select Options</label>
            <i class="ms-Dropdown-caretDown ms-Icon ms-Icon--caretDown"></i>
            <select ngControl="selectedOption">
                <option value="">Choose a fruit...</option>
                <option *ngFor="let option of selectOptions" [value]="option">{{option}}</option>                     
            </select>                        
        </div>
    </form>

The dropdown is successfully rebuilt and all the Fabric UI styling is applied. However there is no validation on the dropdown. I've checked that it works on a plain dropdown:

    <select ngControl="selectedOption">
        <option value="">Choose a fruit...</option>
        <option *ngFor="let option of selectOptions" [value]="option">{{option}}</option>
    </select>

I've linked to the `jquery.fabric.min.js` and JQuery. Is this correct?

**Comment by mikewheaton** [comment]
Glad to hear that the dropdown is built and the styles are being applied correctly. What type of validation are you wanting the dropdown to have?

**Comment by leekaiwei** [comment]
Mostly just `required`, which I've specified in the form builder `Validators.required`.

**Comment by mikewheaton** [comment]
For Angular-related questions like this, you might want to try to [ngOfficeUIFabric](https://github.com/ngOfficeUIFabric/ng-officeuifabric/) project. I'm afraid I don't know enough about Angular and form validation to help with debugging this.

**Comment by leekaiwei** [comment]
As far as I know that is for Angular 1.x? If Angular 2 hasn't been considered for this project yet then that's cool. I was just wondering if it was possible and I assume it's not at the moment.

**Comment by mikewheaton** [comment]
Yes, they're using Angular 1.x. I just thought they might have some more insights into what you're trying to accomplish here, even if they don't have the exact code ready to use.

**Comment by leekaiwei** [comment]
Okay thanks for your help! I'll try over there.
