### ISSUE TITLE
Left Navigation Control

### ISSUE THREAD

**Issue by JyotsnaWadhwani** [OfficeDev/office-ui-fabric#690]
I am trying to develop my application using Office UI fabric components. I m curious to know if there is any component for Left Navigation bar also coming up in the upcoming releases of Office UI ?

**Comment by mikewheaton** [comment]
It sounds like this is a similar request to the vertical navigation bar we've had [requested before](https://github.com/OfficeDev/Office-UI-Fabric/issues/122). There are no definite plans to implement this, but we do have it on [our roadmap](https://github.com/OfficeDev/office-ui-fabric/blob/master/ghdocs/ROADMAP.md) as something we'd like to pursue.
