### ISSUE TITLE
Breadcrumb overflow menu wraps item text

### ISSUE THREAD

**Issue by dmitriyyepishin** [OfficeDev/office-ui-fabric#694]
If a breadcrumb item has a long name the text wraps to multiple lines in overflow menu.

See here: http://codepen.io/dyepishin/pen/WwzbwK

![image](https://cloud.githubusercontent.com/assets/13841696/16430468/14221632-3d39-11e6-91a2-1463534750a8.png)

**Comment by mikewheaton** [comment]
Thanks for reporting this and providing the repro link, @dmitriyyepishin. We'll check in with our design team to see what the desired behavior is here and get it fixed.

**Comment by mikewheaton** [comment]
Actually, it turns out that this is an issue with the ContextualMenu (which Breadcrumb uses) and has been reported before: #478. I'll close this one as a duplicate but want to assure you that we are looking into this.

**Comment by dmitriyyepishin** [comment]
Thanks!
