### ISSUE TITLE
Accordion component wanted

### ISSUE THREAD

**Issue by mereagan** [OfficeDev/office-ui-fabric#695]
I would like to see an accordion type component added to the fabric framework. Such a component is a core functionality in nearly all of my UI projects. Having it in the fabric UI framework would alleviate having to load unnecessary additional frameworks and provide standardization and consistency in the UX.

**Comment by mikewheaton** [comment]
An Accordion or TreeView component is on [our roadmap](https://github.com/OfficeDev/office-ui-fabric/blob/master/ghdocs/ROADMAP.md) but we don't have a definite timeline available right now. Could you send us screenshots of what you're trying to achieve? That will help us to ensure that we're designing a component that addresses your needs.

**Comment by mereagan** [comment]
Here's a screenshot (see attachment) - I had to mask some business sensitive stuff-  of a project I'll be working on before long.What I'll want to do is to convert this InfoPath form I built many yarn ago into a SharePoint List form using SharePoint Client Side rendering (CSR) and I hope fabric UI.


Date: Tue, 28 Jun 2016 14:38:18 -0700

**Comment by mikewheaton** [comment]
Looks like GitHub didn't grab the image from your email. Would you mind adding it directly in a comment on GitHub? Thanks

**Comment by mereagan** [comment]
Sure here it is again.
![etformscrnshot](https://cloud.githubusercontent.com/assets/8365100/16460949/a9d884ac-3def-11e6-9f74-9e83e1b546ba.png)

**Comment by rakheejain** [comment]
Hi Team

We are also looking forward for the accordion component in next releases. We are developing our project using Office UI Fabric, and have a requirement where we want to display data in accordion.

**Comment by ericthompson** [comment]
Hey folks - since it's a part of our roadmap, we'll be closing this one. Thanks for all the input and screenshots!
