### ISSUE TITLE
Documentation reference to js and css file path incorrect

### ISSUE THREAD

**Issue by pkbullock** [OfficeDev/office-ui-fabric#697]
Hi

I was looking at the documentation for the dist file and noticed the CSS file for fabric.css and  fabric.components.css is referenced incorrectly.

It looks like a it just needs to be referenced from one level up folder wise in the components and remove 2 level ups in the index file.

I have made the corrections and will be creating a pull request. Hopefully I have followed the procedure correctly.

Paul

**Comment by mikewheaton** [comment]
The strange part is that whether the path is `../../` (2 levels up) or `../../../` (3 levels up) it seems to be finding the file either way. I'm not sure what's going on here. Were the styles not loading correctly for you, or you just noticed that the path seemed incorrect?

**Comment by pkbullock** [comment]
When I downloaded the last build, I built it, loaded the docs and noticed all the styling wasn't working. The developer tools is edge listed all the assets weren't loading. 

I wonder if caching of the files meant that it loaded even though the references were wrong in your case.

**Comment by mikewheaton** [comment]
It must be some sort of caching issue. As far as I know this has been building and working for everyone on the team. Thanks for noticing the issue!

**Comment by Jahnp** [comment]
Thanks for fixing this, @pkbullock! Closing via #698.
