### ISSUE TITLE
Generate typings for output js files for TypeScript

### ISSUE THREAD

**Issue by pkbullock** [OfficeDev/office-ui-fabric#699]
Hi

I am building a Office App with TypeScript using Fabric 2.6.x, the fabric.js or jquery.fabric.js files it would be useful to have a typscript typings file for the output JS files in the dist folder. I cannot see if v3 offers any resolution to this.

My TypeScript knowledge is new so if this is a noob error on my part then ill bury myself in some more reading.

Paul

**Comment by ericthompson** [comment]
Thanks for this suggestion, @pkbullock - we've added it to our [roadmap](https://github.com/OfficeDev/office-ui-fabric/blob/master/ghdocs/ROADMAP.md)!
