### ISSUE TITLE
Additional Icons - Office Suite Logos

### ISSUE THREAD

**Issue by tobiaswest83** [OfficeDev/office-ui-fabric#702]
As per the call-to-action for the request for more icons, it would be great if there were Office Icons (Word, Excel, SharePoint etc. etc). Nothing more to say on this really :)

**Comment by mikewheaton** [comment]
We've received this request many times before and I've added it to [our roadmap] as something we'd like to include in a future release.

**Comment by tobiaswest83** [comment]
Thanks Mike
