### ISSUE TITLE
TreeView Component

### ISSUE THREAD

**Issue by rakheejain** [OfficeDev/office-ui-fabric#705]
Hi 
Looking forward to see TreeView component added to Fabric UI Framework. I am using Office UI framework on one of my project and have a requirement to display data in tree view structure. Having this component embedded in the framework will have consistency in application UI.

**Comment by ericthompson** [comment]
Good suggestion - this is on our [roadmap](https://github.com/OfficeDev/office-ui-fabric/blob/master/ghdocs/ROADMAP.md) as something we'd like to pursue in the future.

Could you provide a screenshot of what you have in mind (or how you'd like to use it)?

**Comment by rakheejain** [comment]
We are looking for similar UI for treeview to be available in Fabric UI framework

[http://www.jqueryscript.net/demo/jQuery-Plugin-To-Create-Multilevel-Collapsible-Table-Rows-Tabelizer/]

**Comment by ericthompson** [comment]
Thanks for the extra context, @rakheejain. We'll go on ahead and close since we're tracking this, but the example helps us understand your intended use and expected behavior/appearance.
