### ISSUE TITLE
Filter in table

### ISSUE THREAD

**Issue by JyotsnaWadhwani** [OfficeDev/office-ui-fabric#707]
Is there any feature of filter on a table coming? The filter can be similar to that used in SharePoint lists, like sorting. Anything similar to it being used currently?

**Comment by ericthompson** [comment]
We've gotten requests for sorting (which are on our [roadmap](https://github.com/OfficeDev/office-ui-fabric/blob/master/ghdocs/ROADMAP.md)), but we could also look into filtering. It's now added to our roadmap, so closing for now.
