### ISSUE TITLE
Pivot.jquery.js component

### ISSUE THREAD

**Issue by mimisasouvanh** [OfficeDev/office-ui-fabric#723]
The .js file here https://dev.office.com/fabric/components/pivot says in the comments that there are parameters and return values. These values don't make sense.

**Comment by Etheryte** [comment]
For reference, it's [`jquery.Pivot.js` on the 2.6.1 branch](https://github.com/OfficeDev/office-ui-fabric/blob/release/2.6.1/src/components/Pivot/jquery.Pivot.js).  
There are two ways to use the given component, the probably more common way without parameters:

    $('.parents .target').Pivot();

and, as is very common in the jQuery realm, with a chain and parameters:

    $('.parent').Pivot('.target');

The comments regarding parameters are for the latter, however the return values hold for both: the elements you used for Pivot are returned so they can be daisychained in a regular jQuery manner.  
For example:

    $('.parent .target').Pivot().show();

See [this Jsfiddle](https://jsfiddle.net/7rwf1gu2/) for a demonstration of using both on some sample DOM.  

As you can probably see, the approaches can be used quite interchangeably, the main value comes from the fact that you can use either depending on how the rest of your code is structured.

**Comment by mikewheaton** [comment]
Our current site is a bit confusing here – the JS that you see on the [pivot's documentation page](https://dev.office.com/fabric/components/pivot) is actually the jQuery plugin that's included with Fabric. It's not the code you need to wire up an actual Pivot in your project. For that you'll want to follow the pattern you see on our [main component page](https://dev.office.com/fabric/components).

If you have any trouble please feel free to post a JSFiddle or similar and I'll help you debug it. You can also email me internally.
