### ISSUE TITLE
Missing fabric.templates.ts file

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-ui-fabric#726]
I'm following the instructions here: https://dev.office.com/docs/add-ins/design/ui-elements/using-office-ui-fabric
to use some Fabric components in my Office add-in project. But the ComponentHost.ts file refers to a class called FabricTemplateLibrary, which is apparently defined at:

../../../dist/js/fabric.templates.ts

But there doesn’t seem to be any such path/file in the office-ui-fabric repo on GitHub. Can you tell me how I can get this file? Also, since it is called in one of the component files. Shouldn’t it be part of the repo?

**Comment by knom** [comment]
+1

**Comment by ericthompson** [comment]
The template.ts file is actually intended for the new 3.0.0 beta that's currently on master - *not* the 2.6.1 (last stable release). If you're following those instructions be sure that you're using [2.6.1](https://github.com/OfficeDev/office-ui-fabric/releases/tag/2.6.1).
