### ISSUE TITLE
Icons 

### ISSUE THREAD

**Issue by barptad** [OfficeDev/Office-UI-Fabric#73]
It seems like there is a problem with displaying Icons in the Icons sample.

**Comment by LezaMax** [comment]
Thanks for letting us know. We are working on it. It does seem to be the same issue as 75

**Comment by Jahnp** [comment]
Just a heads-up that this has been fixed and will be available in the next release, which we hope to have out this week.

**Comment by mikewheaton** [comment]
Looks like this issue has been fixed.
