### ISSUE TITLE
With RTL CSS Toggle control displays labels improperly

### ISSUE THREAD

**Issue by cut2run** [OfficeDev/office-ui-fabric#733]
Use RTL CSS with Hebrew locale and Toggle control looks bad. 
HTML ...

`                            <div class="ms-Toggle">
                                <span class="ms-Toggle-description"></span>
                                <input type="checkbox" id="checkbox_test" class="ms-Toggle-input" />
                                <label for="checkbox_test" class="ms-Toggle-field">
                                    <span class="ms-Label ms-Label--off"></span>
                                    <span class="ms-Label ms-Label--on"></span>
                                </label>
                            </div>
`

Screenshots ...

 
![image](https://cloud.githubusercontent.com/assets/17089974/16997627/3d387d52-4e84-11e6-83e9-9c8eb8cf43bd.png)

**Comment by mikewheaton** [comment]
Unfortunately, none of the Fabric components support right-to-left (RTL) languages at this time. I've added your request to [our roadmap](https://github.com/OfficeDev/office-ui-fabric/blob/master/ghdocs/ROADMAP.md) as something we'd like to include in a future release.

**Comment by cut2run** [comment]
Thanks for adding to the roadmap.
