### ISSUE TITLE
cross origin font requests failing

### ISSUE THREAD

**Issue by joebo** [OfficeDev/Office-UI-Fabric#75]
Fonts are unable to load from the cdn referenced in the dist fabric.css - https://appsforoffice.microsoft.com/fabric/fonts/

CSS3117: @font-face failed cross-origin request. Resource access is restricted.
File: SegoeUI-Regular.eot

**Comment by pascalberger** [comment]
I think this is the same issue as #73

**Comment by LezaMax** [comment]
Thanks for letting us know. We are working on it.

**Comment by LezaMax** [comment]
@pascalberger are you still seeing issues?  I've tried a couple of times on different environments and fonts seem to be downloading fine.  Wondering if when you tried some configs were still propagating. Please let us know if things are working for you.

**Comment by joebo** [comment]
@LezaMax  this is working now. Thanks!

**Comment by pascalberger** [comment]
Icons are now generally shown, but there are quite a lot missing. I've opened #79 for this
