### ISSUE TITLE
0/100 pagespeed google.

### ISSUE THREAD

**Issue by tavorazo** [OfficeDev/office-ui-fabric#750]
I get 0/100 in qualifying google using fabric.

Why is this happening?

Can anyone confirm this?

**Comment by ericthompson** [comment]
HI, @tavorazo - did it give any specific errors/guidance? I don't believe that anyone the team has tried running parts of the toolkit through this.

**Comment by tavorazo** [comment]
So sorry, was a problem with .htaccess and my cache. This solved. Thank you @ericthompson
