### ISSUE TITLE
Suggestion: how to add the app launcher to our own o365 apps/sharepoint add ins?

### ISSUE THREAD

**Issue by levalencia** [OfficeDev/Office-UI-Fabric#81]
I just noticed this sp user voice idea was implemented, however there is another one very related to this.
http://officespdev.uservoice.com/forums/224641-general/suggestions/6785967-please-create-a-my-app-launcher-chrome-control

Is this on the roadmap for this same UI Fabric?,

**Comment by LezaMax** [comment]
There is a chrome control for Office 365 apps in the roadmap yes. It will be part of the JS controls that are built on top of fabric. Once release we'll let the community know but it will be part of its own repo most likely.  Here is the link to the 365 controls currently published: https://msdn.microsoft.com/en-us/office/office365/howto/javascript-controls

**Comment by mikewheaton** [comment]
Any updates on this, @LezaMax? I'm wondering if the App Launcher is used widely enough to be a Fabric component.

**Comment by mikewheaton** [comment]
I've added this to [our roadmap](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md) as a potential component, as we have no plans to build it at this time.
