### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by jfootenewsig** [OfficeDev/Office-UI-Fabric#86]
Followed the getting started instructions, after running npm install received the following error.

npm ERR! Fabric@1.0.0 postinstall: 'node node_modules/bower/bin/bower install'
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Fabric@1.0.0 postinstall script  'node node_modules/bower/bin/bower install'
npm ERR! This is most likely a problem with the Fabric package, not with npm itself.

Running win 8.1

**Comment by Jahnp** [comment]
Thanks for this! This issue is probably because there isn't actually anything to install. Before moving to GitHub, we were consuming some external libs via Bower, but removed those deps while cleaning house; seems we forgot to also remove the `postinstall` script. This will be fixed soon.

**Comment by jfootenewsig** [comment]
Any idea when another update is coming?
Thanks!

**Comment by Jahnp** [comment]
We don't have a firm ETA yet (we're still in the middle of adapting some of our processes for GitHub :)), but I would expect something within the next few weeks.

**Comment by ericthompson** [comment]
The fix is in Master, let us know if you still have trouble and we can reopen. This will definitely be bundled with the next release (soon!).
