### ISSUE TITLE
DatePicker fails on navigating to previous month

### ISSUE THREAD

**Issue by nilobarp** [OfficeDev/Office-UI-Fabric#88]
![image](https://cloud.githubusercontent.com/assets/1141369/9650975/d6738682-523c-11e5-93bc-44e0f018d558.png)

![image](https://cloud.githubusercontent.com/assets/1141369/9650981/eb7ffcd6-523c-11e5-99c7-2d1103748d37.png)

**Comment by Jahnp** [comment]
Ah, that's pretty ugly. Thanks for the report. What OS/browser did you see this in?

**Comment by nilobarp** [comment]
Chrome 44 on Windows 7

**Comment by Jahnp** [comment]
Thanks! We'll look into this. It may be an issue with the plugin powering the Date Picker.

**Comment by wdo3650** [comment]
This should be fixed.

**Comment by ericthompson** [comment]
Just validated and it looks like it's fixed.
