### ISSUE TITLE
Broken styling for underlined & required TextField

### ISSUE THREAD

**Issue by kmees** [OfficeDev/Office-UI-Fabric#94]
Adding `is-required` and `ms-TextField--underlined` to the same TextField component breaks the styling

![screen shot 2015-09-04 at 11 53 44](https://cloud.githubusercontent.com/assets/649769/9681071/9d5ad46c-52fb-11e5-9644-7b34a2f63378.png)

Markup for the screenshot:

```html
<div class="ms-TextField ms-TextField--underlined">
  <label class="ms-Label">Name:</label>
  <input class="ms-TextField-field" type="text">
</div>

<div class="ms-TextField is-required ms-TextField--underlined">
  <label class="ms-Label">Name:</label>
  <input class="ms-TextField-field" type="text">
</div>
```

**Comment by Jahnp** [comment]
That's pretty gross. Thanks for the tip, we'll look into this.

**Comment by philworthington** [comment]
Great catch. Pull request #98 should fix the issue.
