### ISSUE TITLE
Dialog examples missing required CSS classes

### ISSUE THREAD

**Issue by richjbrowne** [OfficeDev/Office-UI-Fabric#95]
The example HTML provided for the LgHeader and Multiline dialogs are missing their required CSS classes, "ms-Dialog--lgHeader" and "ms-Dialog--multiline" respectively.

Also, the class required to reveal the close button in the dialog, "ms-Dialog--close", is never shown in the examples.

**Comment by philworthington** [comment]
@richjbrowne Good catch and thanks for the heads up. It looks like you're looking at our master branch which currently does not include the variant classes as you have pointed out. 

There was a change made earlier in the week to our develop branch, which as of right now includes all of our latest changes, along with all of the dialog variant classes in their applicable template files.

You can find them here: https://github.com/OfficeDev/Office-UI-Fabric/tree/develop/src/components/Dialog

Thanks again, master will be updated with the latest from develop on our next release.
